### ISSUE TITLE
centromere outer repeat transcript [sf#286]

### ISSUE THREAD

**Issue by srynobio** [The-Sequence-Ontology/SO-Ontologies#286]
**Reported by gomidori on 2011-11-28 16:02 UTC**
Hi,

For one of my fission yeast phenotype terms, it looks like I need a term for RNA transcribed from the centromeric outer repeats. I think something like this would work for me, so would it fit into SO?

name: regional\_centromere\_outer\_repeat\_transcript
def: "A transcript that is transcribed from the outer repeat region of a regional centromere." \[PomBase:mah\]
synonym: "regional\_centromere\_outer\_repeat\_region\_transcript" EXACT \[PomBase:mah\]
synonym: "centromeric outer repeat transcript" EXACT \[PomBase:mah\]
intersection\_of: SO:0000673 \! transcript
intersection\_of: derives\_from SO:0001799 \! regional\_centromere\_outer\_repeat\_region

Thanks\!
Midori

**Comment by srynobio** [comment]
Response from @keilbeck 

Hi Midori
I need to think about this more. 
Is there a product of this transcript?
--K

**Comment by srynobio** [comment]
Response from Midori Harris 

Hi Karen,
These transcripts don't code for protein; apparently they're precursors of siRNAs that are required for RNAi-mediated heterochromatin formation in centromeric regions. I'm no expert at all; I'm quoting from the introductions to these papers (carefully selected on the basis of cropping up at the top of my google search):
http://www.nature.com/nature/journal/v451/n7179/full/nature06561.html (PMID:18216783)
http://genesdev.cshlp.org/content/19/19/2301.full (PMID:16204182)
Hope that helps; apologies for not ferreting out references earlier.
cheers,
m

**Comment by srynobio** [comment]
Response from Midori Harris

Hi,
any further word on this one?
thanks,
m

**Comment by keilbeck** [comment]
This was added SO:0001905
