### ISSUE TITLE
New term request for "Fragile site"

### ISSUE THREAD

**Issue by srynobio** [The-Sequence-Ontology/SO-Ontologies#301]
New term request for "Fragile site"
Name: fragile_site
Definition: "A fragile site is a heritable locus on a chromosome that is prone to DNA breakage" (from HGNC definition).
Also, wiki article: https://en.wikipedia.org/wiki/Chromosomal_fragile_site
It might possibly fit as a child of "chromosomal_breakpoint" (SO:0001021), or perhaps a new "biological_region" (SO:0001411).
It seems that there should also be specific subtypes, like: "Common Fragile Site" (CFS) and "Rare Fragile Site" (RFS)
A couple of articles:
https://www.ncbi.nlm.nih.gov/pubmed/16236432
https://www.ncbi.nlm.nih.gov/pubmed/17608616

**Comment by cthoyt** [comment]
@keilbeck @srynobio I'm interested in pushing this forwards - since this is something that HGNC annotates genes with (their description is here: https://www.genenames.org/help/symbol-report)  and I'd like to dump HGNC as well-annotated OBO/OWL ontoloties. Ultimately, it would be important that there was a term under [SO:0000704 (gene)](https://www.ebi.ac.uk/ols/ontologies/so/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSO_0000704)

**Comment by cmungall** [comment]
It would be great to have these in SO - I would question whether they belong under 'gene' though, despite what is in HGNC

**Comment by cthoyt** [comment]
@cmungall im open to any classification. I just hope the HGNC will be receptive to uptaking it

**Comment by keilbeck** [comment]
Hi @egchr - could you look at adding these terms? It looks like Shawn did most of the work years ago.
Again, echoing chris, not sure it belongs under gene as it seems applicable to more parts of the chromosome that the genic regions.
--Karen

**Comment by murphyte** [comment]
I believe HGNC has retired all their "fragile site" entries:
https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:3934

**Comment by cthoyt** [comment]
Just checked, there are 116 entries currently with this locus type:

```
#: A mapping of HGNC identifiers to HGNC gene symbols that are annotated with "fragile site"
fragile_sites = {
    "3868": "FRA1A",
    "3869": "FRA1B",
    "3870": "FRA1C",
    "3871": "FRA1D",
    "3872": "FRA1E",
    "3873": "FRA1F",
    "3874": "FRA1G",
    "3875": "FRA1H",
    "3876": "FRA1I",
    "3877": "FRA1J",
    "3878": "FRA1K",
    "3879": "FRA1L",
    "3880": "FRA1M",
    "3885": "FRA2A",
    "3886": "FRA2B",
    "3887": "FRA2C",
    "3888": "FRA2D",
    "3889": "FRA2E",
    "3890": "FRA2F",
    "3891": "FRA2G",
    "3892": "FRA2H",
    "3893": "FRA2I",
    "3894": "FRA2J",
    "3895": "FRA2K",
    "3896": "FRA3A",
    "3897": "FRA3B",
    "3898": "FRA3C",
    "3899": "FRA3D",
    "3900": "FRA4A",
    "3901": "FRA4B",
    "3902": "FRA4C",
    "3903": "FRA4D",
    "3905": "FRA5A",
    "3906": "FRA5B",
    "3907": "FRA5C",
    "3908": "FRA5D",
    "3909": "FRA5E",
    "3910": "FRA5F",
    "3911": "FRA5G",
    "3912": "FRA6A",
    "3913": "FRA6B",
    "3914": "FRA6C",
    "3915": "FRA6D",
    "3916": "FRA6E",
    "3917": "FRA6F",
    "3918": "FRA6G",
    "3919": "FRA7A",
    "3920": "FRA7B",
    "3921": "FRA7C",
    "3922": "FRA7D",
    "3923": "FRA7E",
    "3924": "FRA7F",
    "3925": "FRA7G",
    "3926": "FRA7H",
    "3927": "FRA7I",
    "3928": "FRA7J",
    "3929": "FRA8A",
    "3930": "FRA8B",
    "3931": "FRA8C",
    "3932": "FRA8D",
    "3933": "FRA8E",
    "3935": "FRA9A",
    "3936": "FRA9B",
    "3937": "FRA9C",
    "3938": "FRA9D",
    "3939": "FRA9E",
    "3940": "FRA9F",
    "3829": "FRA10A",
    "3830": "FRA10B",
    "3831": "FRA10C",
    "3832": "FRA10D",
    "3833": "FRA10E",
    "3834": "FRA10F",
    "3835": "FRA10G",
    "3836": "FRA11A",
    "3837": "FRA11B",
    "3838": "FRA11C",
    "3839": "FRA11D",
    "3840": "FRA11E",
    "3841": "FRA11F",
    "3842": "FRA11G",
    "3843": "FRA11H",
    "3844": "FRA11I",
    "3845": "FRA12A",
    "3846": "FRA12B",
    "3847": "FRA12C",
    "3848": "FRA12D",
    "3849": "FRA12E",
    "3850": "FRA13A",
    "3851": "FRA13B",
    "3852": "FRA13C",
    "3853": "FRA13D",
    "3854": "FRA14B",
    "3855": "FRA14C",
    "3856": "FRA15A",
    "3857": "FRA16A",
    "3858": "FRA16B",
    "3859": "FRA16C",
    "3860": "FRA16D",
    "3861": "FRA16E",
    "3862": "FRA17A",
    "3863": "FRA17B",
    "3864": "FRA18A",
    "3865": "FRA18B",
    "16929": "FRA18C",
    "3866": "FRA19A",
    "3867": "FRA19B",
    "3881": "FRA20A",
    "3882": "FRA20B",
    "3883": "FRA22A",
    "3884": "FRA22B",
    "3945": "FRAXA",
    "3946": "FRAXB",
    "3947": "FRAXC",
    "3948": "FRAXD",
    "3949": "FRAXE"
  },
```

**Comment by keilbeck** [comment]
Thanks for checking.

**Comment by egchr** [comment]
Created "fragile_site" (SO:0002349) as a child of "chromosome_breakpoint" (SO:0001021). Added "common_fragile_site (SO:0002350) and "rare_fragile_site" (SO:0002351) as children of "fragile_site". You should see the changes reflected online sometime in the next 24 hours.

**Comment by cthoyt** [comment]
@egchr cheers! I hope some of my other suggestions recently were written well enough that they’re actionable. I am interested in making it possible to annotate all of the human genes in HGNC with an appropriate SO term via their locus types

**Comment by egchr** [comment]
Apologies for how long it's taking me to go through everything. If you have other ideas beyond what you've submitted as issue requests, I'd be happy to schedule a meeting to discuss them. Let me know.
