### ISSUE TITLE
OWL file is not kept up to date

### ISSUE THREAD

**Issue by srynobio** [The-Sequence-Ontology/SO-Ontologies#303]
Dear Sequence Ontology Project maintainers,
Background:
The DECIPHER platform (http://decipher.sanger.ac.uk/) allows clinical teams and researchers to deposit minimal genetic and phenotypic data, and share these data globally. DECIPHER's initial mission was focused on the interpretation of CNVs discovered in clinical microarray testing, but has now broadened to the full spectrum of sequence and structural variants that can be revealed by capillary or next generation sequencing (genes, panels, exomes, or genomes).
Problem:
We use SO when we run variants through the Ensembl VEP process, and now also when exchanging data through the Global Alliance for Genomic Health MatchMaker Exchange project.
We attempted to load the terms into our database for access, however this has proved difficult to do with the .obo file you provide. I noticed that you link to an .owl version of the SO (On the home page of the project), so we imported the tree using that file. When testing our implementation, we found that the .owl file was incomplete.
For example, the SO term SO:0001910 (frameshift truncation) does not appear in the .owl file. I notice that the .owl file has a last modified date of 12-May-2011. On your homepage you say "[The owl file] is updated nightly and may be slightly out of sync with the current obo file.".
Is there something you can do to re-establish this link for the .owl file being regally updated? In addition, would it be possible to provide an SQL dump of the ontology for database consumption?

**Comment by keilbeck** [comment]
The purl http://purl.obolibrary.org/obo/so.owl seems to be pointing at the right place now
