### ISSUE TITLE
Term SO:0001691 has no textual definition

### ISSUE THREAD

**Issue by jyquinn** [The-Sequence-Ontology/SO-Ontologies#329]
I propose that the following definition be added for term SO:0001691:
"A restriction enzyme recognition site that, when cleaved, results in no overhangs"

**Comment by keilbeck** [comment]
Thanks lots for the input. I am not sure how to best attribute you for the definition. Let me know and I will update the ontology. Usually we do Project:name.

**Comment by jyquinn** [comment]
Project:SBOL probably makes the most sense here. Thanks!
