### ISSUE TITLE
CDS_supported_by_peptide_spectrum_match

### ISSUE THREAD

**Issue by srynobio** [The-Sequence-Ontology/SO-Ontologies#330]
Hi Karen,
I'd like to propose the term CDS_supported_by_peptide_spectrum_match to annotate CDS that are supported by proteomics data.
Parent term: CDS_supported_by_sequence_similarity_data
Or did I overlook an existing term that is better suited.
Best,
Daniel

**Comment by keilbeck** [comment]
SO:0002071 done - will commit today
