### ISSUE TITLE
The 'Request A Term' link on http://www.sequenceontology.org/ should point to github

### ISSUE THREAD

**Issue by dbolser-ebi** [The-Sequence-Ontology/SO-Ontologies#337]
Instead it points me here:
https://sourceforge.net/p/song/term-tracker/

which then points me here:
https://github.com/The-Sequence-Ontology/SO-Ontologies/issues

Better to link directly to the latter.

**Comment by srynobio** [comment]
Thank you for the heads up.  I will fix the link.

**Comment by srynobio** [comment]
Updated, thanks for the heads up!
