### ISSUE TITLE
NTR: long_terminal_repeat_transcript

### ISSUE THREAD

**Issue by mah11** [The-Sequence-Ontology/SO-Ontologies#341]
For PomBase annotation extensions (e.g. GO & phenotype), we could use a term for RNA transcribed from long terminal repeats, such as:

name: long_terminal_repeat_transcript
def: An RNA that is transcribed from a long terminal repeat.
is_a: SO:0000673 ! transcript

many thanks,
midori

**Comment by mah11** [comment]
p.s. synonym: LTR_transcript

**Comment by keilbeck** [comment]
Hi Midori
Would this be an ncRNA transcript? Is there a good ref? I found this http://www.ncbi.nlm.nih.gov/pubmed/7474125
--K

**Comment by mah11** [comment]
Hmm, I'm not sure. I really only have a vaugely-remembered, never-better-than-textbook-level grasp on these things. From a quick poke on PubMed & google, it looks like LTRs often flank coding regions, so transcripts may include some coding .. probably safest jsut to put it under transcript.

That paper looks relevant, and I've just been skimming this more recent review of LTR transposons in fission yeast: http://www.ncbi.nlm.nih.gov/pubmed/24256266

hope that helps a bit, tho I'm out of my depth here!

**Comment by mah11** [comment]
ping
any further word on this?

**Comment by keilbeck** [comment]
Sorry this got lost.
Nicole is adding the term right now
--K

**Comment by nicoleruiz** [comment]
SO:0002208 long_terminal_repeat_transcript has been added as a child of transcript.

**Comment by mah11** [comment]
Thanks! We can use it straight away.
