### ISSUE TITLE
NTRs for mating type cassettes

### ISSUE THREAD

**Issue by Antonialock** [The-Sequence-Ontology/SO-Ontologies#342]
Mat2P silent mating type cassette containing H+ specific information
Mat3M silent mating type cassette containing H- specific information

(the two mating types in S. pombe)

Both is_a SO:0001984 (I think)

thanks!

**Comment by Antonialock** [comment]
PMID:18354497

**Comment by keilbeck** [comment]
Could you define these new terms please?
Is there a PMID?

**Comment by Antonialock** [comment]
I need them for an extension in this paper: PMID:18354497 

The "Mat2P silent mating type cassette" contains H+ mating type specific information
The "Mat3M silent mating type cassette" contains H- mating type specific information

(a copy of one of these cassettes exists in a non-silenced region, determining the if the cell is an M cell or a P cell)

**Comment by Antonialock** [comment]
Hi Karen, do you need anything else? They are both 
Mat2P - A gene cassette array containing H+ mating type specific information
Mat3M - A gene cassette array containing H- mating type specific information

thanks

**Comment by nicoleruiz** [comment]
SO:0002157 - Mat2P
SO:0002158 - Mat3M

Both are children of SO:0001984 - silent_mating_type_cassette_array

**Comment by Antonialock** [comment]
Thanks Nicole
