### ISSUE TITLE
NTR: scaRNA, small Cajal body-specific RNA

### ISSUE THREAD

**Issue by tberardini** [The-Sequence-Ontology/SO-Ontologies#343]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC126017/

**Comment by keilbeck** [comment]
That was not the nicest paper to read without coffee. OK, I think this makes sense for a term. What do you think?

name: scaRNA
syn: smaln cajal body specific RNA

def: A ncRNA, specific to the the cajal body that have been demonstrated to function as guide RNAs in site-specific synthesis of 2′-O-ribose-methylated nucleotides and pseudouridines in the RNA polymerase II-transcribed U1, U2, U4 and U5 spliceosomal small nuclear RNAs (snRNAs).

parent:ncRNA

**Comment by tberardini** [comment]
Minor typo corrections:

name: scaRNA
syn: small Cajal body-specific RNA

def: A ncRNA, specific to the Cajal body, that has been demonstrated to function as a guide RNA in the site-specific synthesis of 2′-O-ribose-methylated nucleotides and pseudouridines in the RNA polymerase II-transcribed U1, U2, U4 and U5 spliceosomal small nuclear RNAs (snRNAs).

**Comment by keilbeck** [comment]
great - we can add it today

**Comment by tberardini** [comment]
Great!  Thanks, Karen.

**Comment by nicoleruiz** [comment]
I have added the term SO:0002095 scaRNA as a child of ncRNA with the definition and synonym provided.

**Comment by mdperry** [comment]
Yes; that sounds like a very good addition.  I had not heard of Cajal body
specific guide RNAs, but I think it makes sense. Sort of analogous to the
snoRNAs that perform a similar function in modifying ribosomal RNA (Sean
Eddy had a nice paper about predicting and testing snoRNAs in S.
cerevisiae).  As I recall there are about a dozen sites in rRNA the get
converted to pseudo-U and if you mutate any of them the ribosome no longer
works(?). When they solved the crystal structures of ribosomes, some of the
pseudo-U sites end up near each other in 3-D (I think).

--Marc Perry
