### ISSUE TITLE
NTR regional_centromere_inner_repeat_region

### ISSUE THREAD

**Issue by Antonialock** [The-Sequence-Ontology/SO-Ontologies#344]
Hello,
I would like to request the new term
regional_centromere_inner_repeat_region

thanks 
Antonia

**Comment by keilbeck** [comment]
This term was added by Val some time ago SO:0001798
regional_centromere_inner_repeat_region  
The inner inverted repeat region of a modular centromere and part of the central core surrounding a non-conserved central region. This region is adjacent to the central core, on each chromosome arm.

Is there something I am missing?

**Comment by Antonialock** [comment]
Ah super, I must have missed it for some reason :)
