### ISSUE TITLE
request for pseudogene terms

### ISSUE THREAD

**Issue by murphyte** [The-Sequence-Ontology/SO-Ontologies#345]
I'd like to request some adjustments to some of the SO pseudogene terms, and one addition. I'm looking at this with regard to how to map INSDC (GenBank) terms to/from SO:
1) the hierarchy of gene-pseudogene-pseudogenic_transcript-pseudogenic_exon should work nicely for us
2) Along those lines, I'd like to propose pseudogene (SO:0000336 ) be added as a second Parent for pseudogenic_tRNA (SO:0000778) and pseudogenic_rRNA (SO:0000777).
3) Similarly, I'd like to propose pseudogenic_exon (SO:0000507) be added as a child for pseudogenic_tRNA (SO:0000778) and pseudogenic_rRNA (SO:0000777).
4) And please add a term for pseudogenic_CDS, as a child of pseudogenic_transcript (SO:0000516). INSDC usage would be similar to CDS usage, where there may either be a set of pseudogene-pseudogenic_transcript-pseudogenic_CDS features, or just pseudogene-pseudogenic_CDS. For GFF3, I would say phase is _not_ required for pseudogenic_CDS features since there may be frameshift disruptions.

I think that should cover the gamut of pseudogene annotations that are observed in INSDC.

Thanks!

-Terence Murphy

**Comment by keilbeck** [comment]
Hi Terrance
Thanks for the comments.

I have moved pseudogenic_tRNA and Pseudogenic rRNA to be child terms of pseudogenic_transcript. Does this make sense? They are now parts of pseudogene. 

Pseudogenic_exon is part of Pseudogenic_transcript so that should satisfy the requirement there.

For the pseudogenic_CDS it looks like you want to have  it be a part of a pseudogenic_transcript but also be independent?

The way we did this with the exons was a decayed_exon can be annotated alone but a psuedogenic_exon is part of a pseudogenic_transcript. DO you want two terms?

--K

**Comment by keilbeck** [comment]
SO:0002087  - new ID for pseudogenic_CDS

**Comment by murphyte** [comment]
Hi Karen,

> I have moved pseudogenic_tRNA and Pseudogenic rRNA to be child terms of pseudogenic_transcript. Does this make sense? They are now parts of pseudogene. 

Yep, that works, if pseudogenic_exon is also below pseudogenic_tRNA and pseudogenic rRNA. I just want to make sure it's legal to have either pseudogenic_transcript, pseudogenic_tRNA, or pseudogenic rRNA with pseudogenic_exon child features.

> For the pseudogenic_CDS it looks like you want to have it be a part of a pseudogenic_transcript but also be independent?

Having pseudogenic_CDS below pseudogenic_transcript is fine, and no need for a second term. I was merely clarifying that expected usage would be either:
1.  pseudogene - pseudogenic_transcript - pseudogenic_CDS 
2.  pseudogene - pseudogenic_CDS 

Thanks!

-Terence

**Comment by keilbeck** [comment]
pseudogenic_CDS SO:0002087
isa pseudogenic_region, partof Pseudogenic_transcript
I think this resolves the issues, unless I missed something.

**Comment by murphyte** [comment]
>  I think this resolves the issues, unless I missed something.

yep, I think so. How long does it take for changes to show up in the public SO browser?
