### ISSUE TITLE
Add term allelic_frequency

### ISSUE THREAD

**Issue by gafiore** [The-Sequence-Ontology/SO-Ontologies#357]

**Comment by keilbeck** [comment]
HI

I'm not sure what kind of thing an allelic frequency is?
I can see it being the property, but it is not a sequence feature. Any thoughts, suggestions for a definition?
It is always going to be dependent on a particular population right?

--Karen

**Comment by thefferon** [comment]
@gafiore,  please follow up with an explanation, definition, and an example of how you would use **allelic_frequency**.

**Comment by bheale** [comment]
Given the presence of allelic state as a separate issue, I'd suggest that allelic frequency is similar to variant frequency. http://www.sequenceontology.org/browser/current_svn/term/SO:0001763
Under sequence attribute/variant quality.  Variant frequency's definition is 
"A physical quality which inheres to the variant by virtue of the number instances of the variant within a population."  
I'm not sure allelic frequency is really different from variant frequency. Or is Allelic frequency more about the occurrence of an allelic state....I'll have to double check the resource to look for implied meaning.

**Comment by keilbeck** [comment]
Hi Bret
thanks, 
It looks like HL7 copied the definition from SO :o)
Does allele frequency need to be a separate entity from allele frequency or should it be a synonym.

--K

**Comment by keilbeck** [comment]
I have added this terms as a child of variant frequency.
The ID is: 
SO:0002119
The definition is:
A physical quality which inheres to the allele by virtue of the number instances of the allele within a population. This is the relative frequency of the allele at a given locus in a population.

**Comment by keilbeck** [comment]
This is checked into the latest revision. I'll keep this open for comments for a couple of days.

**Comment by gafiore** [comment]
Thank you! I'm including the HL7 Clinical Genomics Work Group for feedback.
