### ISSUE TITLE
NTR CArG-box

### ISSUE THREAD

**Issue by Antonialock** [The-Sequence-Ontology/SO-Ontologies#361]
Hi, I'd like to request a new term for CArG-box, a promoter element bound by the MADS family of transciption factors, consensus
5′-(C/T)TA(T/A)4TA(G/A)-3′
PMID:7623803
PMID:1748287

**Comment by keilbeck** [comment]
Hi Antonia
Could you define these please?
THanks
--K

**Comment by keilbeck** [comment]
SO:0002156 - added.

**Comment by Antonialock** [comment]
Hi Karen, sorry I missed your message in August. Thanks for adding the term!
