### ISSUE TITLE
NTRs: early and late origin of replication

### ISSUE THREAD

**Issue by mcourtot** [The-Sequence-Ontology/SO-Ontologies#363]
id: SO:new1
name: early_origin_of_replication
def: "An origin of replication that initiates early in S phase." []
synonym: "early origin" EXACT []
synonym: "early origin of replication" EXACT []
is_a: SO:0000296 ! origin_of_replication

id: SO:new2
name: late_origin_of_replication
def: "An origin of replication that initiates late in S phase." []
synonym: "late origin" EXACT []
synonym: "late origin of replication" EXACT []
is_a: SO:0000296 ! origin_of_replication

needed for https://github.com/geneontology/go-ontology/issues/12533 as requested by @mah11, @ValWood and @Antonialock

**Comment by mcourtot** [comment]
Hi - is there any news on this, or can I be of any help with edits?

**Comment by nicoleruiz** [comment]
The only comment I have is to add early replication origin and late replication origin as synonyms for these terms. @keilbeck - Are you ok with adding these terms?

**Comment by theintuitivesoul** [comment]
I need help. I am not a professional and anything i've done so far is
because I have read all night long until my eyeballs fell out. I really
need some assistance. I learned a lot while reading but not nearly enough.

**Comment by keilbeck** [comment]
yep. We should add these terms

**Comment by nicoleruiz** [comment]
I added these terms:
SO:0002140 early_origin_of_replication
SO:0002141 late_origin_of_replication

**Comment by mcourtot** [comment]
Thanks!
