### ISSUE TITLE
Add SO terms for meiotic and mitotic recombination regions

### ISSUE THREAD

**Issue by catherinefarrell** [The-Sequence-Ontology/SO-Ontologies#364]
INSDC will soon be adding a recombination_class for recombination features, to include class types for both meiotic and mitotic recombination regions, also non_allelic_homologous_recombination (SO:0002094), breakpoint_junction (SO:0001021) and other (SO:0000298). Since the former two currently lack a specific SO term, can you add one for each of those?

The intended INSDC terms and definitions for these are:

**Term:** meiotic_recombination
**Definition:** A genomic region in which there is an exchange of genetic material as a result of the repair of meiosis-specific double strand breaks that occur during meiotic prophase.

**Term:** mitotic_recombination 
**Definition:** A genomic region where there is an exchange of genetic material with another genomic region, occurring in somatic cells.

Thanks for considering these!

Catherine Farrell, Ph.D
Staff Scientist - RefSeq Project
NCBI/NLM/NIH

**Comment by keilbeck** [comment]
How would you feel if we called them mitotic_recombination_region and meiotic_recombination_region?

**Comment by murphyte** [comment]
I'll weigh in for Catherine, who is out on vacation for another week. We discussed it here and agree mitotic_recombination_region and meiotic_recombination_region make sense for the SO terms. Thanks for the additions.

Best regards,

-Terence Murphy, Ph.D.
NCBI/NLM/NIH

**Comment by keilbeck** [comment]
SO:0002154 - mit
SO:0002155 - mei

added - will be checked in shortly
