### ISSUE TITLE
Update gvf_validator.pl to use correct ontology file

### ISSUE THREAD

**Issue by thefferon** [The-Sequence-Ontology/SO-Ontologies#365]
The SO GVF validator, **gvf_validator.pl**, uses the obsolete page:

http://www.sequenceontology.org/resources/obo_files/current_release.obo

Instead, it should be updated to use the following page:

https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/so-xp.obo

Who can do this?

**Comment by thefferon** [comment]
https://github.com/The-Sequence-Ontology/GAL/blob/master/bin/gvf_validator **line 1994**

**Comment by thefferon** [comment]
Closed this as a duplicate of https://github.com/The-Sequence-Ontology/GAL/issues/1

**Comment by barrymoore** [comment]
I've updated to gvf_validator, gff3_validator and gff_tool to point to the PURL location of the SO obo file (http://purl.obolibrary.org/obo/so.obo) as suggested by @thefferon and @cmungall.  Changes committed and pushed to git.

**Comment by barrymoore** [comment]
I've updated to gvf_validator, gff3_validator and gff_tool to point to the PURL location of the SO obo file (http://purl.obolibrary.org/obo/so.obo) as suggested by @thefferon and @cmungall. Changes committed and pushed to git.
