### ISSUE TITLE
URIs of SO properties do not resolve

### ISSUE THREAD

**Issue by arnikz** [The-Sequence-Ontology/SO-Ontologies#367]
For example:
_has_part_ -> http://purl.obolibrary.org/obo/so-xp.obo#has_part does not resolve

Moreover, the SO classes use different (and shorter) URI path to resolve e.g.,
_SO:0000704_ (gene) -> http://purl.obolibrary.org/obo/SO_0000704

Using the `@prefix obo: http://purl.obolibrary.org/obo/` one would like to do the following:

_obo:SO_has_part_
_obo:SO_0000704_

OR

_so:has_part_
_so:0000704_

using `@prefix so: http://purl.obolibrary.org/obo/so.owl#`

**Comment by cmungall** [comment]
We should use RO URIs such as http://purl.obolibrary.org/obo/BFO_0000051

**Comment by theintuitivesoul** [comment]
Thank you so much for replying back, am I asking too much if I ask for your
assistance with this? I will try on my own first and if I run into a
problem...(which I will) is okay for me to email you back?

**Comment by cmungall** [comment]
You can email me but I prefer to keep on the tracker.

Note that I would argue the fix should be made upstream in SO itself. But you can make a local copy and fix it yourself by searching and replacing on IRIs.

You can find more such relations in the [OBO Relations Ontology](https://github.com/oborel/obo-relations). See also the [sequence branch of RO visualized within OLS](http://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002514)

**Comment by theintuitivesoul** [comment]
That is fine by me. I could be wrong but I can't tell the difference
between the two.

**Comment by davidwsant** [comment]
Thank you, Chris for taking care of this one. It looks like you have answered the questions. Feel free to reopen this if you have any more questions.

Thanks,

Dave Sant
