### ISSUE TITLE
Add 'regulatory uORF' synonym to SO:0002027

### ISSUE THREAD

**Issue by catherinefarrell** [The-Sequence-Ontology/SO-Ontologies#368]
RefSeq is annotating regulatory uORFs on mRNAs when there is experimental evidence in the literature for a particular uORF being regulatory to pORF translation, e.g., NM_000671.4 misc_features at 24..86 and 54..86. We want to better format the /note qualifier on these features with a controlled vocabulary string that matches an SO string or an associated synonym. SO:0002027 ('uORF' primary string and 'upstream ORF' synonym) is the appropriate entry and the definition fits our use, but we want to include the word "regulatory" in our feature to help distinguish these uORFs from the many other uORFs present in mRNAs that don't have a known regulatory function.

Since we prefer to have our controlled vocabularies matching either an SO primary term or synonym, can you add 'regulatory uORF' as a synonym to SO:0002027?

Thanks for your help!

Catherine Farrell, Ph.D
Staff Scientist - RefSeq Project
NCBI/NLM/NIH

**Comment by nicoleruiz** [comment]
In addition to adding regulatory uORF as a synonym, I think we could also create the child terms AUG-initiated uORF and non-AUG-initiated uORF.

**Comment by catherinefarrell** [comment]
Having child terms for those makes sense, especially since ribosome profiling shows that some non-AUG-initiated uORFs can undergo translation.

Catherine

**Comment by theintuitivesoul** [comment]
I was not sure but I got in touch with 23&Me. I didn't know if it was something I did or if I did.

**Comment by nicoleruiz** [comment]
Here are my proposed changes:
- Add "regulatory uORF" as a synonym of "uORF"

- Create term "AUG_initiated_uORF" as child of "uORF"
name: AUG_initiated_uORF
Definition: A uORF beginning with the canonical start codon AUG.
synonym: AUG initated uORF EXACT
is_a: SO:0002027 ! uORF

- Create term "non_AUG_initiated_uORF” as child of “uORF"
name: non_AUG_initiated_uORF
Definition: A uORF beginning with a codon other than AUG.
synonym: non AUG initiated uORF EXACT
is_a: SO:0002027 ! uORF

References:
http://www.ncbi.nlm.nih.gov/pubmed/26684391
http://www.ncbi.nlm.nih.gov/pubmed/27313038

**Comment by nicoleruiz** [comment]
I have made the proposed changes. You can see these right away if you download the obo file from github. It should take about a day for the SO browser to update.
