### ISSUE TITLE
Add genome_of property restrictions

### ISSUE THREAD

**Issue by arnikz** [The-Sequence-Ontology/SO-Ontologies#371]
Please add domain/range restrictions for the _genome_of_ property. Thanks.

**Comment by nicoleruiz** [comment]
Could you give an example use case for this?

**Comment by srynobio** [comment]
A example may help here but [genome_of](http://www.sequenceontology.org/browser/current_svn/term/genome_of) is a relationship that relatates two terms, and adding a restriction would imply that the restriction is true everywhere the relationship is used.

**Comment by cmungall** [comment]
I would first start with a textual definition of genome_of!

SO may also be interested in using RO relations here.

**Comment by arnikz** [comment]
An example of use could be:  *URI1 genome_of URI2* where:
_URI1_ is of type _SO:0001026_ (e.g. http://example.com/genome/human/) -> domain
_URI2_ refers to NCBI Taxonomy ID (e.g. http://purl.bioontology.org/ontology/NCBITAXON/9606) -> range. In fact, all relationships (properties) in SO should have defined domain/range (even if these are just of generic type URI or literal). Using RO relations in SO would be great.

**Comment by cmungall** [comment]
How about [RO:0002162](http://purl.obolibrary.org/obo/RO_0002162) ! in 
taxon

It's not specific to genomes. The domain is very generic. For the range 
you would use a class from NCBITaxon (not the bioportal version), see 
http://obofoundry.org/ontology/ncbitaxon.html

**Comment by arnikz** [comment]
@cmungall: I would prefer to use more specific term such as _genome_of_ , which could be subclassed from RO_0002162 (in taxon) with the domain restricted to _SO:0001026_ (genome). However, it depends what the authors of SO think _genome_of should be:)
B.t.w. What's the reason to use the bioportal version of NCBITaxon instead? Thanks.

**Comment by cmungall** [comment]
On 22 Aug 2016, at 2:50, Arnold Kuzniar wrote:

> @cmungall: I would prefer to use more specific term such as 
> _genome_of_ , which could be subclassed from RO_0002162 (in taxon) 
> with the domain restricted to _SO:0001026_ (genome). However, it 
> depends what the authors of SO think _genome_of should be:)

This is fine if it's a subPropertyOf (not subClassOf)

> B.t.w. What's the reason to use the bioportal version of NCBITaxon 
> instead? Thanks.

NCBITaxon is part of the obolibrary obofoundry.org, other ontologies are 
already using it, e.g. for taxon constraints

**Comment by arnikz** [comment]
@cmungall: Thanks. Indeed, the bioportal version of NCBITaxon does not use the aforementioned constraints.

**Comment by davidwsant** [comment]
It appears as though Chris Mungall has answered this one for me as well. Thank you, Chris. If this issue is not resolved, feel free to reopen the issue.

Thanks,

Dave
