### ISSUE TITLE
Minor:  GFF3 specification link broken

### ISSUE THREAD

**Issue by jorvis** [The-Sequence-Ontology/SO-Ontologies#372]
This is relatively minor, but keeps popping up so I thought I'd make a ticket for it.

I use the GFF3 specification in some of my courses, and there are many links all over the web pointing to the GFF3 spec page you have hosted for a long time that was previously [here](http://www.sequenceontology.org/gff3.shtml).  It got removed in the site update, but perhaps consider at least putting a redirection page that points to the [current location](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) of the spec?  Even many GMOD [pages](http://gmod.org/wiki/GFF3) point to this now-missing page.

**Comment by keilbeck** [comment]
Hey. This needs to be fixed. Thanks.
Shawn - can we put a redirect on this page? and same for GVF
Cheers

**Comment by keilbeck** [comment]
https://github.com/srynobio - any progress on this Shawn?

**Comment by srynobio** [comment]
Sorry for the delay in adding the redirect.  Should be fixed now.  Thanks for letting us know @jorvis
