### ISSUE TITLE
STOP_GAINED affects polypeptide length not transcript length

### ISSUE THREAD

**Issue by RadixSeven** [The-Sequence-Ontology/SO-Ontologies#376]
http://www.sequenceontology.org/browser/current_svn/term/SO:0001587 has description:

> A sequence variant whereby at least one base of a codon is changed, resulting in a premature stop codon, leading to a shortened transcript.

The codons affect translation not transcription. Rather than "shortened transcript" it should read "shortened polypeptide".

**Comment by keilbeck** [comment]
Thanks for catching this.
