### ISSUE TITLE
NTR: SHP box

### ISSUE THREAD

**Issue by ValWood** [The-Sequence-Ontology/SO-Ontologies#382]
name: SHP box
child of SO:0100017
conserved Cdc48-interaction motif. The consensus sequence is F.GK..[RK]LG.

PMID: 27655872
PMID: 17083136 

note to self
 rbd2 PMID:27655872
+ dysferlin and ubx3

(aa242-251)

**Comment by ValWood** [comment]
Note from the author:

Thank you for creating a sequence feature in SO. I would suggest consensus for the SHP box as:
F[PI]GKG[TK][RK]LG[GT] 
then relaxed to
F.GKG.[RK]LG

Thank you,

Jiwon 

(If these are out of scope I can put then in our in house vocabulary instead)

**Comment by nicoleruiz** [comment]
Does F[PI]GKG[TK][RK]LG[GT] represent consensus across yeast and F.GKG.[RK]LG represent consensus between yeast and humans?

**Comment by ValWood** [comment]
F[PI]GKG[TK][RK]LG[GT] is the consensus reported in the paper, but I noticed that it did not pull in ubx3 a known cdc48 cofactor cdc48, with a SHP box  I added a bit more ambiguity to cover  this, which was confirmed by the authors.

I haven't checked other species, but as the conservation for specific proteins in different families is closer than within species conservation for different families, I imagine the relaxed consensus will work better species wide.

ubx3 has FSGKGQRLG

looking further afield it might be necessary to relax the K to polar	[CDEHKNQRST]

F.G[CDEHKNQRST]G.[RK]LG (picks up plant ubx3 orthologs). Or you could go with the initially reported and it could be refined later....

Val

**Comment by nicoleruiz** [comment]
I'll go with the consensus sequences suggested by the author of the paper. We can always change it later if we need to. 

Is this ok for the term definition? 

Definition: A conserved Cdc48/p97 interaction motif with strict consensus sequence F[PI]GKG[TK][RK]LG[GT] and relaxed consensus sequence F.GKG.[RK]LG.

**Comment by ValWood** [comment]
Yep, sounds good,

Thanks

Val

**Comment by nicoleruiz** [comment]
SO:0002159 SHP_box has been added.

**Comment by ValWood** [comment]
Thanks!
