### ISSUE TITLE
so.owl PURL returns 404: Not Found

### ISSUE THREAD

**Issue by bill-baumgartner** [The-Sequence-Ontology/SO-Ontologies#383]
Hi there,
It looks like a recent commit moved the so-xp.owl file and consequently broke the so.owl PURL. http://purl.obolibrary.org/obo/so.owl resolves to https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/so-xp.owl

However it appears that so-xp.owl is now in master/releases/so-xp.owl/, i.e. https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/releases/so-xp.owl/so-xp.owl

Best,
Bill

**Comment by srynobio** [comment]
As of our update yesterday we no longer use the -xp. convention in any SO files.  The file you are refering to (master/releases/so-xp.owl) is from our last release.

**Comment by bill-baumgartner** [comment]
Thanks for your response. I think I could have written my initial question more clearly. I'm actually interested in using so.owl and have relied upon http://purl.obolibrary.org/obo/so.owl to point me to the appropriate download in the past. As of your update yesterday, http://purl.obolibrary.org/obo/so.owl resolves to a broken link to the so-xp.owl file. Would it be possible to update http://purl.obolibrary.org/obo/so.owl such that it points to the current release?

**Comment by srynobio** [comment]
Unfortunately, I don't have the ability to create a redirect in github.  The best suggestion I can offer would be to update your link from so-xp.owl to so.owl with the same path.

**Comment by jamesaoverton** [comment]
As @bill-baumgartner points out, this change broke the main SO PURLs. (See also https://github.com/OBOFoundry/purl.obolibrary.org/issues/274 and the [SO PURL configuration file](https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/so.yml).)

Do I have your permission to update the PURLs?

- http://purl.obolibrary.org/obo/so.owl  ->  https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/so.owl
- http://purl.obolibrary.org/obo/so.obo  ->  https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/so.obo

**Comment by nicoleruiz** [comment]
Yes. Thank you for updating this.

**Comment by srynobio** [comment]
Let us know if this does not solve your issue.
