### ISSUE TITLE
New term requests for NCBI controlled vocabularies

### ISSUE THREAD

**Issue by catherinefarrell** [The-Sequence-Ontology/SO-Ontologies#386]
Hi SO,

Related to issues #378 and #379 where NCBI previously requested new terms or synonyms for INSDC terms, RefSeq is also using a few non-INSDC terms as misc_feature controlled vocabularies. Since it will be easier if we can map them to SO terms or synonyms, we'd like to request matches for those too.

New term requests:

**1) repeat_instability_region**
 
This new term is for annotating unstable fragile sites in the reference genome. Such regions may be subject to repeat expansions or contractions (e.g., trinucleotide, tetranucleotide, pentanucleotide, etc.), which are usually caused by slippage during DNA replication and may result in disease-related mutations.

**2) replication_start_site**

This requested term is related to 'origin_of_replication' (SO:0000296), but it differs from it in that it's a more precise replication start site, whereas the origin is generally considered to be a larger genomic region that encompasses ORC complexes and other regulatory binding sites in addition to start sites. 

**3) nucleotide_cleavage_site**

There are SO terms for specific types of nucleotide cleavage sites, e.g., a variety of restriction enzyme cleavage sites (SO:0001688, SO:0001693, SO:0001694 and others), but there is no generic parental term. We'd like to request one, likely as a child term of 'junction' (SO:0000699) above SO:0001688 and the other terms for restriction enzyme cleavage sites.

Thanks for considering these!

Catherine
NCBI - RefSeq

**Comment by catherinefarrell** [comment]
We have been looking at the '**repeat_expansion_region**' term again and thinking about parent:child relationships for it. Since repeat expansion regions may also be subject to repeat contractions, we thought it would be more appropriate to make a new parental term '**repeat_instability_region**', then make new child terms for '**repeat_expansion_region**' and '**repeat_contraction_region**'.

It will be more appropriate for us to use the parental term 'repeat_instability_region' for annotating unstable fragile sites in the reference genome. However, since these play a role in disease, I could see how the two suggested child terms could be of use to variation and genotype/phenotype groups who want to describe disease-associated repeat expansions or contractions in specific sequences.

Catherine
NCBI - RefSeq

**Comment by murphyte** [comment]
FYI, we're now generating public data using these terms, so it would be great if we could get them (and the ones from #379) into SO. Is there anything we can do to help? We can write up full definitions for the terms here (#379 already has definitions for you).

**Comment by nicoleruiz** [comment]
I will make it a priority to add these terms and the terms from #379 by the end of this week. 

@murphyte Thank you for providing the excel spreadsheet with all of the INSDC-SO mappings. Karen and I have gone through it and the thing holding us up is trying to decide how to add the mappings while also including the feature, qualifier and qualifier value information.

**Comment by thefferon** [comment]
**(emphasis mine)**

> **1) repeat_instability_region** 
This new term is for annotating **unstable fragile sites** in the reference genome. Such regions may be subject to repeat expansions or contractions (e.g., **trinucleotide, tetranucleotide, pentanucleotide, etc.**), which are usually caused by slippage during DNA replication and may result in disease-related mutations.

> 

How do this term and its intended usage differ from *short_tandem_repeat* or *microsatellite*? I.e., couldn't your average dinucleotide repeat be considered a 'repeat_instability_region'? The description given above seems to indicate the term should be used only for 'fragile sites', and possibly only those that have previously been associated with disease. 

How would you classify an ordinary trinucleotide repeat that is subject to repeat expansions and contractions (...usually caused by slippage during DNA replication...) but has not been implicated in disease?

Just trying to sort out the distinctions between terms.

**Comment by catherinefarrell** [comment]
To address @thefferon's concerns about the distinctions between terms, the main thing to point out is that we are dealing with two different branches of the SO tree: 

1) The terms for RefSeq functional element annotation are used for feature annotation of the reference genome, so we want to derive those terms from under the sequence_feature branch (specifically under -> region -> biological_region). In other words, we are annotating **features** not **variants**, so we want to avoid using terms from the sequence_variant  branch. 

2) The terms under the sequence_variant branch are appropriate for variant sequences. They include terms like 'short_tandem_repeat_change' (SO:0002161) and children 'short_tandem_repeat_expansion' (SO:0002162) and 'short_tandem_repeat_contraction' (SO:0002163), all of which suggest some change from the reference sequence has already occurred.

Although there are similarities between some of the terms in the sequence_feature and sequence_variant  branches, particularly the repeat-related terms, I think it's important to keep them separate for the above reasons. For our requested 'repeat_instability_region' term, we use it for annotating fragile sites on the reference genome that are prone to alteration. We suggest that the new term be a child term under sequence_feature -> region -> biological_region -> repeat_region -> tandem_repeat, with the following definition:

**repeat_instability_region**
"A repeat region that is prone to expansions and/or contractions"

Also, here are our suggested definitions for the other requested terms above:

**replication_start_site**
"A nucleotide site from which replication initiates"
That should be a child of **origin_of_replication** (SO:0000296), which could be redefined as:
"A region of a nucleic acid molecule where replication initiates"

**nucleotide_cleavage_site**
"A point in nucleic acid where a cleavage event occurs"
As previously suggested, that can be a child of 'junction' (SO:0000699), and a parental term for SO:0001688, SO:0001693, SO:0001694 and other specific types of cleavage sites.

**Comment by thefferon** [comment]
@catherinefarrell , thank you for the clear explanation. My concerns have been allayed.

**Comment by nicoleruiz** [comment]
@catherinefarrell Karen and I are having some trouble with replication_start_site. The definitions for replication_start_site and origin_of_replication you proposed seem very similar. Could you give more detailed definitions for these?

**Comment by nicoleruiz** [comment]
I have added the following terms:
SO:0002202 repeat_instability_region
SO:0002203 replication_start_site
SO:0002204 nucleotide_cleavage_site

In addition, I also updated the definition for SO:0000296 origin_of_replication to the definition you provided and made all of the other changes you suggested.
