### ISSUE TITLE
Issue with SO versionIRI

### ISSUE THREAD

**Issue by mcourtot** [The-Sequence-Ontology/SO-Ontologies#387]
Checking
https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/so.owl

while the ontology IRI is correct there is still an issue with the version IRI:
` <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/so/so-xp/releases/2015-11-24/so-xp.owl/so.owl"/>`

**Comment by julie-sullivan** [comment]
Same issue with the SO.obo file?

**Comment by davidwsant** [comment]
Hi Melanie,

I apologize for the delayed response. SO underwent a change in staff and I am just now getting to many of the old issue requests. 

Five years ago the SO ontology files were moved to GitHub. The link that should now be used for the OWL file is https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/master/Ontology_Files/so.owl
This file will be updated with each term that occurs in SO. I do not believe any files are saved with the PURL link http://purl.obolibrary.org/obo. However, that link now reroutes to the [OBO Foundry GitHub page](https://github.com/OBOFoundry/purl.obolibrary.org/).

Does this answer your question?

Thanks,

Dave

**Comment by mcourtot** [comment]
Thanks @davidwsant - for clarity this was referring to the line 

`<owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/so/2020-07-01/so.owl"/>`

in the OWL file you mention. The IRI value has however been fixed, so all good :)
