### ISSUE TITLE
annotate any sequence using Sequence Ontology

### ISSUE THREAD

**Issue by solo7773** [The-Sequence-Ontology/SO-Ontologies#389]
Hi there. For a sequence, for example, a sequence of somatic deletion,
`chr    start    end    type    seq`
`11    67077296    67077312    deletion    CACAGTGCTGGCCTATG`
I want to map it to a term of children of SO:0000159. Is there a way to achieve this? Thanks.

**Comment by srynobio** [comment]
I'm not 100% sure I understand your question, but if you're trying to map terms in SO to sequences I think it would require and be accomplished programmably.  @barrymoore might have some insight into the possibility of [GAL](https://github.com/The-Sequence-Ontology/GAL) helping you with this.

Also keep in my you can download the complete SO file [here](https://github.com/The-Sequence-Ontology/SO-Ontologies) if you would like to write code against it.

**Comment by solo7773** [comment]
@srynobio Thanks. What I am going to do is to find a SO term for the sample sequence in the first post. I won't use Ensembl VEP which can predict SO's sequence variant terms for that sequence. I need to map that sequence to other SO terms. I read the GAL document. Its input gaff file should include SO information in column 3. That is exactly the problem I have. I don't know the SO info of the sequence. I also read the so_xp.obo file. I'd like to code it but I at present I don't how to find a so term for a sequence.

**Comment by srynobio** [comment]
I don't believe a resource exist which has all know sequences for a given SO term.  Often SO is used to annotate post alignment (to discover any [sequence_alteration](http://www.sequenceontology.org/browser/current_svn/term/SO:0001059))

Also I'm a still a bit fuzzy on what your trying to do "I need to map that sequence to other SO terms"

I would be more than happy to help, if you could give a detailed description of what your doing here.

**Comment by solo7773** [comment]
Dear srynobio, thank you very much. For example, I have a sequence from human reference genome hg19,
`chromosome, start, end, seq`
`11, 67077296, 67077312, CACAGTGCTGGCCTATG`
Assuming my empirical knowledge tells me it should be protein-coding and SO:0000010.

Now, let me describe my problem,
I have the sequence (`11, 67077296, 67077312, CACAGTGCTGGCCTATG`), but **I don't have any knowledge about this sequence**. For me, what SO term this sequence has is unknown. I need to find it. How can I find out the SO term (i.e. SO:0000010 in this case)? I have thousands of sequences, so I have to do this computationally. Could you give me any hint?

**Comment by srynobio** [comment]
One method you could try (as an example) would be to:

* Download the current GFF3 file for humans from [Ensembl](http://uswest.ensembl.org/info/data/ftp/index.html).

If you review the file a exon feature will look similar to this:
```
1       havana  exon    12179   12227   .       +       .     Parent=transcript:ENST00000450305;Name=ENSE00001671638;constitutive=0;ensembl_end_phase=-1;ensembl_phase=-1;exon_id=ENSE00001671638;rank=2;version=2
```

* Now you can cross reference your locations with the locations in the GFF3 file and I will return the SO feature containing your sequence.

**Comment by nerdstrike** [comment]
Drive-by recommendation for @solo7773 - Ensembl does not use SO terms internally, so we do our best to map to the correct SO term. In your case, you will have no difficulty finding protein-coding and related terms, but you more accurate terms are not always used.

Depending on your skills, you might find it easiest to run your data through our hg19/GRCh37 REST server: http://grch37.rest.ensembl.org/documentation/info/overlap_region

We usually report our internal "biotype", but if you apply ?content-type=text/x-gff3 to the request, those are mapped to SO term names, e.g. processed_transcript = SO:0000516

For example: http://grch37.rest.ensembl.org/overlap/region/human/1:12179-12227?feature=exon;feature=transcript;content-type=text/x-gff3

If you'd like more help please contact helpdesk@ensembl.org

**Comment by solo7773** [comment]
Thank you very much @srynobio  and @nerdstrike , your info is very timely and helpful. I'll move forward with your advice and tell you my progress. Thanks again.

**Comment by srynobio** [comment]
@nerdstrike thanks for the additional solution.  Best of luck @solo7773
