### ISSUE TITLE
Add synonym for nc conserved region SO:0000334

### ISSUE THREAD

**Issue by asingeror** [The-Sequence-Ontology/SO-Ontologies#390]
Please add conserved non-coding element (CNE) and conserved non-coding sequence (CNS) as synonyms for term SO:0000334, nc conserved region.  Many researchers use these terms preferentially over the SO term.

**Comment by nicoleruiz** [comment]
conserved non-coding element and conserved non-coding sequence have been added as exact synonyms for the term nc_conserved_region.
