### ISSUE TITLE
NTR: circRNA

### ISSUE THREAD

**Issue by cmungall** [The-Sequence-Ontology/SO-Ontologies#391]
See https://github.com/geneontology/go-ontology/issues/13302

It looks like GO is proposing to treat this as a subtype of SO:0000234 ! mRNA

**Comment by SianGramates** [comment]
FlyBase has very recently annotated circ_mRNAs for 2 gene models (mbl and Pde8). We are hoping that implementation of new circRNA terms can be moved up the priority list.

We would like to point out an advantage of the second option described above: provides an appropriate term ('circRNA') when it is not known whether it is coding or non-coding. 

In addition to the transcript level terms, it would be helpful to have 'gene_with.....' or similar term(s) at the gene level.

**Comment by davidwsant** [comment]
Hi guys,

The terms circular_ncRNA has been assigned ID SO:0002291 and circular_mRNA has been assigned ID SO:0002292. As usual, the [SO Browser](http://sequenceontology.org/browser/current_svn/) should be updated with these terms within about 24 hours. 

Thanks,

Dave
