### ISSUE TITLE
Consequence term for short tandem repeat variants

### ISSUE THREAD

**Issue by rajatshuvro** [The-Sequence-Ontology/SO-Ontologies#392]
Hello,
I work for the Nirvana variant annotator team (https://github.com/Illumina/Nirvana). Currently we are in the process of adding support for repeat expansions or short tandem repeats. We observed that there is a term for the variant (http://www.sequenceontology.org/browser/current_svn/term/SO:0002096) but no corresponding term to describe the consequence. In keeping with CNVs, can we add terms like

1. short_tandem_repeat_change
2. short_tandem_repeat_expansion
3. short_tandem_repeat_contraction.

Please let us know what you think. We will be happy to use any terms you propose.

Thanks
Rajat

**Comment by nicoleruiz** [comment]
Hi! We will look at this and get back to you later this week.

**Comment by nicoleruiz** [comment]
See #359

**Comment by nicoleruiz** [comment]
We have added the following terms for STR variants under sequence_variant:

SO:0002161 short_tandem_repeat_change
SO:0002163 short_tandem_repeat_contraction (child of short_tandem_repeat_change)
SO:0002162 short_tandem_repeat_expansion (child of short_tandem_repeat_change)

**Comment by rajatshuvro** [comment]
Thanks so much
