### ISSUE TITLE
sequence_feature what does it mean?

### ISSUE THREAD

**Issue by simonecarvalho91** [The-Sequence-Ontology/SO-Ontologies#393]
I have some NGS data and almost half of my variants are "sequence_feature". I can't find a proper answer for this classification. Is that exon, is that intron, what is it, by the way? I have done the annotation using SnpEff.

**Comment by srynobio** [comment]
This is the [SO](http://www.sequenceontology.org/browser/current_svn/term/SO:0000110) definition. 
And how the annotation is handled in [SnpEff](http://snpeff.sourceforge.net/SnpEff_manual.html)

**Comment by simonecarvalho91** [comment]
For sure. But when you look for the mean, this is what you find: "Any extent of continuous biological sequence". Is that ANY sequence? Intron, exon, UTR, everything? It's a poor meaning, isn't it?

**Comment by srynobio** [comment]
@simonecarvalho91 Could you possibly add a snippet of your VCF annotated file?

**Comment by simonecarvalho91** [comment]
Did you mean add a command that I used to annotate my vcf file?

**Comment by srynobio** [comment]
no the resulting VCF file that contained the `sequence_feature` annotation.

**Comment by simonecarvalho91** [comment]
![image](https://cloud.githubusercontent.com/assets/27826221/25248145/89fdc28c-25e3-11e7-933d-d30b75d0ac43.png)

**Comment by srynobio** [comment]
They are denoting each feature affected.  Each time `sequence_feature` is noted it the start of a new annotation.  

If you want to add the raw test from one VCF line I can show you how it's broken down.

**Comment by simonecarvalho91** [comment]
I'm sorry, I think I didn't understand well. It appears like as a "EFFECT", with frameshift, missense variant and etc. And in my vcf table in excel it appears that way (in the picture):
![image](https://cloud.githubusercontent.com/assets/27826221/25348790/d357f6b8-28f5-11e7-8bcd-7b498232e09e.png)

**Comment by Bochao1** [comment]
Dear  srynobio, 

I have the same problem with simonecarvalho91. I am wondering is this problem solved?

**Comment by simonecarvalho91** [comment]
Hi Bochao1,

For me it was solved... in the end, I realized that the sequence_feature is just a double annotation of the same variant previously annotated by its effect. It means that the same variant is annotated in two different rows, once with its effect (for example: frameshift_variant) and then in a second row as sequence_feature (that you can see the region affected in another column, like: protein_coding or etc).. If you filter a variant by the HGVS name, you will see that it is "duplicated" with the real effect and the sequence_feature. In resume: you can just erase or simply not consider the sequence_feature annotation.

Hope I have helped you!

**Comment by davidwsant** [comment]
Hi guys,

It appears as though @simonecarvalho91 was able to determine how to work with this, and I would have the same answer. Each time something is annotated it will be marked as a "sequence_feature". It will have a second annotation which is what you are looking for. You can probably remove the "sequence feature" lines. 

I hope your questions have been answered. Feel free to reopen the issue if you need further explanation.

Thanks,

Dave Sant

@simonecarvalho91
@Bochao1
