### ISSUE TITLE
Check RNACentral SO mappings

### ISSUE THREAD

**Issue by cmungall** [The-Sequence-Ontology/SO-Ontologies#394]
Does anyone from SO want to take a look over the proposed set of mappings RNA Central will use to map its vocabulary:

https://github.com/RNAcentral/rnacentral-webcode/issues/63#issuecomment-284364348

In particular, should SO have a miscRNA type?

**Comment by nicoleruiz** [comment]
We will take a look at this and get back to you by the end of the week.

**Comment by murphyte** [comment]
I've finally added our full INSDC:SO mapping file to #378. For misc_RNA, we map to the general SO term "transcript", or "pseudogenic_transcript" if marked up with a /pseudo qualifier (at least that's planned; I think we haven't yet implemented using pseudogenic_transcript in our GFF3 output yet). I wouldn't say using "transcript" is wrong, it's just rather generic but it does cover the spectrum of how misc_RNA is used in INSDC and RefSeq. In particular, misc_RNA covers both "there isn't another INSDC feature type that would be more appropriate" and also "a more specific type wasn't provided" (but perhaps could have been). So IMHO I don't think adding an additional SO type would add anything on top of just using transcript.

**Comment by davidwsant** [comment]
Hi Chris,

I like the way that Terence has dealt with this for INSDC. I have tried to not add any type of miscellaneous terms, but instead I use the parent term which is what Terence has done. Do you feel that this has been answered sufficiently? I am going to close this issue, but please feel free to reopen this if you feel this needs further discussion.

Thanks,

Dave 

@murphyte 
@cmungall

**Comment by cmungall** [comment]
Looks great thanks!
