### ISSUE TITLE
Representation of complex variants

### ISSUE THREAD

**Issue by anleopa** [The-Sequence-Ontology/SO-Ontologies#397]
Which term should be used to represent a complex variation like this one?
An inversion, with a fusion that connects an exon to intron from a different gene, and an abnormal products.
The information of the variation can be found at 
https://www.ncbi.nlm.nih.gov/clinvar/variation/17918/ 
http://www.omim.org/entry/107680#0011 

Thanks.

**Comment by thefferon** [comment]
First, we need to be clear on the nature of this change. The OMIM summary mentions several distinct variants, the last of which appears to be the one to which @anleopa is referring: an inversion involving
> an inversion containing portions of the 3-prime ends of the APOA1 and APOC3 genes, including the DNA between these genes. The breakpoints were located within the fourth exon of the APOA1 gene and the first intron of the APOC3 gene.
> 
<img width="1109" alt="screen shot 2017-05-15 at 9 49 43 am" src="https://cloud.githubusercontent.com/assets/313712/26060894/5d2f1d94-3954-11e7-8c67-6c3eeee3fb09.png">
This variant by itself would appear to be an ordinary inversion, which happens to carry the consequence of creating a fusion gene(s).

The OMIM description also mentions a 6.5kb insertion in a APOA1 intron, and:

> Forte et al. (1984) cited evidence that the 6.5-kb insert in the APOA1 gene is deleted from its normal position in the promoter region for the closely linked APOC3 gene.
>  
It is not clear to me from the OMIM description whether the inversion and the insertion variants are related, nor whether they were seen together, i.e. in some form of complex variant.

As far as I can tell, the variant https://www.ncbi.nlm.nih.gov/clinvar/variation/17918/ is simply the inversion that results in a gene fusion.

@anleopa , do you have a different interpretation?

**Comment by anleopa** [comment]
@thefferon Thank you very much for your answer. I agree with you in the interpretation. My doubt cames from the classification made by ClinVar. They do not consider the variation as an Insertion, but as a Variant which means that it is more complex than a simple insertion. 
Which term should be used to classify this variation, which is and insertion + fusion_gene, according to Sequence Ontology?

**Comment by thefferon** [comment]
Actually I think it is an **inversion** with a consequence of fusion_gene. The SO term for **inversion** is [SO:1000036](http://www.sequenceontology.org/browser/current_svn/term/SO:1000036). The result, or consequence, of this inversion is a fusion gene. The SO term for **fusion_gene** is [SO:0000287](http://www.sequenceontology.org/browser/current_svn/term/SO:0000287).

In contrast, a complex variant might be either [SO:1000005](http://www.sequenceontology.org/browser/current_svn/term/SO:1000005) or perhaps [SO:0001784](http://www.sequenceontology.org/browser/current_svn/term/SO:0001784).

**Comment by nicoleruiz** [comment]
@thefferon I agree with your interpretation of the variant. The only comment I wanted to make was that the consequence of the inversion would be annotated as gene_fusion [SO:0001565](http://www.sequenceontology.org/browser/current_svn/term/SO:0001565) since this is a type of sequence_variant. fusion_gene describes a sequence_feature rather than the type of consequence it is. The similar names of the terms can be confusing.

**Comment by anleopa** [comment]
Yes, both terms can be confusing. I think it is clear now. Thank you both @thefferon and @nicoleruiz
