### ISSUE TITLE
SO term for H2BK5ac

### ISSUE THREAD

**Issue by makostadima** [The-Sequence-Ontology/SO-Ontologies#398]
[Name]: H2BK5_acetylation_site
[Definition]: A kind of histone modification site, whereby the 5th residue (a lysine), from the start of the H2B histone protein is acetylated.
[Synonyms]:	H2BK5 acetylation site, H2BK5ac
[Parent]:	histone_2B_acetylation_site (SO:0002143)

Some information about this histone variant can be found here: http://www.actrec.gov.in/histome/ptm_sp.php?ptm_sp=H2BK5ac 
and the paper cited within: https://www.ncbi.nlm.nih.gov/pubmed/18552846

**Comment by nicoleruiz** [comment]
SO:0002164 H2BK5_acetylation_site has been added. 

Thank you for providing the definition and references!
