### ISSUE TITLE
New term request: Thermoregulator

### ISSUE THREAD

**Issue by AntonPetrov** [The-Sequence-Ontology/SO-Ontologies#404]
I would like to request a new term for **Thermoregulator** RNAs. 

### Background 

These regulatory regions coordinate temperature-dependent gene expression. They are found in 5'UTRs, and their secondary structures change in response to temperature which affects the translation. More information can be found in this [review](http://www.nature.com/nrmicro/journal/v10/n4/full/nrmicro2730.html).

### Place in hierarchy

This term could sit in the same place as [riboswitch](http://www.sequenceontology.org/browser/current_svn/term/SO:0000035) in terms of `is_a` _mRNA_region_ and is `part_of` an _mRNA_.

### Why we need this term

Once the term is created, we will attach it to the following RNA families in [Rfam](http://rfam.xfam.org):
http://rfam.xfam.org/search?q=thermoregulator

Please feel free to let me or @JoannaArgasinska know if you have any questions. Thank you!

**Comment by AntonPetrov** [comment]
I hope the description makes sense. Feel free to let me know if you need more information.

**Comment by nicoleruiz** [comment]
This looks good! Thank you for providing a review paper for us to reference. Do you have a definition to suggest?

**Comment by AntonPetrov** [comment]
Thank you @nicoleruiz! How about this:

> A thermoregulator is a cis element in the 5' end of an mRNA that can change its secondary structure in response to temperature and coordinate temperature-dependent gene expression.

**Comment by nicoleruiz** [comment]
I like the definition. I will use this for the new term. I do have a few questions though.

1. Do you want to use the term thermoregulator? I scanned a few review papers and they all use the term RNA thermometer so it seems like that is the more popular term. I would like the new term to be the name that is most recognized by the community but I will also include alternate names as synonyms.
2. Would it be useful for you if we created child terms like ROSE element or fourU element?

**Comment by AntonPetrov** [comment]
I agree, **RNA thermometer** seems to be more common than *thermoregulator*, so let's use it instead.

As far as creating child terms for specific RNA thermometers, I am not entirely convinced that it's necessary. Rfam currently has [31 thermometer families](http://rfam.xfam.org/search?q=thermoregulator), including FourU and ROSE, so if one would have to create a child term for each of them. On the other hand I can see that it could be useful in some cases.

**Comment by nicoleruiz** [comment]
SO:0002168 RNA_thermometer has been added.
