### ISSUE TITLE
Term Request: Copy number alteration?

### ISSUE THREAD

**Issue by stuppie** [The-Sequence-Ontology/SO-Ontologies#407]
Is there a class for Copy Number Alteration/Variation? This would only include deletion (http://purl.obolibrary.org/obo/SO_0001879) and amplification (http://purl.obolibrary.org/obo/SO_0001880). Currently both are under [structural variant](http://purl.obolibrary.org/obo/SO_0001537) which includes many other kinds of variations. Thanks

**Comment by davidwsant** [comment]
Hi @stuppie,

I apologize that it has taken so long to respond to your request. There was a change in staff and I am now going through old issue requests that have been present for a few years. 

Copy number changes are indeed included under structural variation. Although structural variation includes other terms, these terms fit well as children under structural_variant. The three terms that I recommend using are:

[copy_number_change (SO:0001563)](http://sequenceontology.org/browser/current_svn/term/SO:0001563)
[copy_number_increase (SO:0001911)](http://sequenceontology.org/browser/current_svn/term/SO:0001911)
[copy_number_decrease (SO:0001912)](http://sequenceontology.org/browser/current_svn/term/SO:0001912)

I would recommend using these terms for annotation of copy number alterations. Feel free to reopen this issue if you have further questions.

Thanks,

Dave
