### ISSUE TITLE
SO:0001541 decreased_transcript_level_variant has incorrect definition

### ISSUE THREAD

**Issue by rileygr** [The-Sequence-Ontology/SO-Ontologies#409]
SO:0001541 decreased_transcript_level_variant 
appears to have an incorrect definition:
A sequence variant that **increases** the level of mature, spliced and processed RNA with respect to a reference sequence.

Should presumably be:
A sequence variant that **decreases** the level of mature, spliced and processed RNA with respect to a reference sequence.

George Riley
NCBI - ClinVar

**Comment by nicoleruiz** [comment]
This has been fixed. Thank you for bringing this to our attention.
