### ISSUE TITLE
NTR: 'functional region'

### ISSUE THREAD

**Issue by mbrush** [The-Sequence-Ontology/SO-Ontologies#410]
I am working with the [ClinGen DMWG](http://datamodel.clinicalgenome.org/interpretation/) to build a model supporting clinical variant interpretations, and we are looking to re-use as possible from existing ontologies. We need the concept of a 'functional' sequence region to annotate assertions that a particular region affected by a mutation contributes to the molecular function of a nucleic acid or protein molecule.  
  
If this is a reasonable term to include in SO, please add. The only existing term I found that might possibly define a region based on its being required form some molecular function is restriction_enzyme_region (SO:0001954), def = "A region related to restriction enzyme function."  The proposed term would be much broader, encompassing any region of nucleotide or amino acid sequence that is directly or indirectly (e.g. is first transcribed/translated) required for some molecular function.

### Term Label
functional_region

### Definition
A region that encodes sequence  that contributes to the molecular function of nucleic acid or protein molecule.

### Comment
A functional region can itself perform a function in the context of the macromolecule where it is found, or be transcribed/translated into RNA or protein sequence that is known to contribute to molecular function in the context of the gene product.

### Parent
biological_region (SO:0001411)

**Comment by mbrush** [comment]
@keilbeck is anyone filling new term requests at the moment? Just wondering if this one sounds like a valid term for SO and will eventually be filled.  Thanks!

**Comment by keilbeck** [comment]
Yes, sorry we missed this. I will talk to Nicole in the morning.
--k

**Comment by keilbeck** [comment]
Where do you draw the line at functional? It seems like this is a very wavy line. binding sites, enzymatic regions for sure but what about structural regions that hold the other functional places together? I think there may be a better term - along the lines of variant impact region or something.

**Comment by keilbeck** [comment]
Hey Matt - I didn't hear back from you on this one. Do you have time to talk on the phone this week?

**Comment by mbrush** [comment]
Good questions Karen - I just got of a call with the ClinGen folks where we discussed this.  We intend this term to refer only to regions that code for parts of gene products that **directly** contribute to molecular function.  I added 'directly' to the definition, and also expanded the text in the Comment to be clearer about this.
 

- **Definition:** A region that encodes sequence that **_directly_** contributes to the molecular function of nucleic acid or protein molecule.

- **Comment:** A functional region can itself perform a function in the context of the macromolecule where it is found, or be transcribed/translated into RNA or protein sequence that directly contributes to a molecular function of the gene product. Regions that code for purely structural elements in a gene product that connect such directly functional elements together are not considered functional_regions. Examples of regions considered functional include those encoding enzymatic activity, binding activity, regions required for localization or membrane association,  channel-forming regions, and signal peptides or other elements critical for processing of a gene product.

If this still makes you a bit uncomfortable, we might consider if your idea of a 'variant impact region' would suffice for ClinGen's use case.  By this, I assume you mean a region where mutations have been observed to impact gene or gene product function.  I see how this is perhaps easier to define clearly, but not sure if this is the concept that ClinGen has in mind. I will follow up with them about this and let you know.

**Comment by keilbeck** [comment]
OK, I understand your points. I think there are many terms that could fall under this as child terms and it may mean terms with multiple parents. We will work over it in lab meeting on monday.

**Comment by keilbeck** [comment]
I am still struggling to place this term because it does not fall in the natural hierarchy. Lots of terms in the ontology could compose a functional region. I also think there is potential for there to be sibling terms.

How does something like this feel to you
interpretation_region (or some similar name)
--direct functional region
--indirect functional region
--Other terms that classify the impact like structural impact region, regulation impact region 

What do you think?

**Comment by mbrush** [comment]
Hi Karen.  I think I understand your hesitations here, and you raise good points.  Perhaps the concept we are attempting to define above is too broad, and something narrower will be easier to implement and still suffice for ClinGen's needs.  Consider the more focused concept of a "functional_gene_region", which is defined at the DNA/genome level, and explicitly limited to being part of a gene. This contrasts to the original, broader definition that could include regions on any type of sequence molecule (DNA, RAN, protein), that are not necessarily part of a gene. 
 
**Label:** functional_gene_region (or functional_gene_component_region)
 
**Definition:** A gene_component_region that encodes sequence that directly contributes to the molecular function of its gene or gene product. 
 
**Comment:**  A functional_gene_region is a sequence feature that resides within a gene. But it is typically the corresponding region of translated/transcribed sequence in a gene product, that performs the molecular function qualifying it as a functional_gene_region.  Here, a functional_gene_region must contribute _directly_ to the molecular function of the gene product - regions that code for purely structural elements in a gene product that connect such directly functional elements together are not considered functional_gene_regions. Examples of regions considered 'functional' include those encoding enzymatic activity, binding activity, regions required for localization or membrane association, channel-forming regions, and signal peptides or other elements critical for processing of a gene product. 
In addition, regions that function at the genomic/DNA level are also included - e.g. regions of sequence known to be critical for binding transcription or splicing factors.

--------------

With this more constrained scope, could our requested term be slotted in under gene_component_region without much disruption? (i.e.  limited need to re-classify existing classes, or implement sibling/child terms as you describe above).

**Comment by nicoleruiz** [comment]
We are going to discuss this at lab meeting tomorrow.

**Comment by nicoleruiz** [comment]
SO:0002188 functional_gene_region was added as a child of gene_member_region.

**Comment by davidwsant** [comment]
Hi guys,

It appears as though this issue was resolved in December 2017 but the ticket has not been closed. I am going to close this ticket. If any part of this ticket has not been resolved, please feel free to reopen the issue and comment on what specifically needs to change.

Thanks,

Dave
