### ISSUE TITLE
NTR: mutational hotspot

### ISSUE THREAD

**Issue by mbrush** [The-Sequence-Ontology/SO-Ontologies#411]
I am working with the [ClinGen DMWG](http://datamodel.clinicalgenome.org/interpretation/) to build a model supporting clinical variant interpretations, and we are looking to re-use as possible from existing ontologies. We need the concept of a 'mutational hotspot' sequence region to annotate assertions that a particular region is a locus of frequent mutational events.
  
If this is a reasonable term to include in SO, please add.  Of note, a similarly specified term is recombination_hotspot (SO:0000339)

### Term Label
mutational_hotspot

### Definition
A region of genomic sequence known to undergo mutational events with greater frequency than expected by chance.

### Parent
biological_region (SO:0001411)

**Comment by mbrush** [comment]
@keilbeck is anyone filling new term requests at the moment? Just wondering if this one sounds like a valid term for SO and will eventually be filled.  Thanks!

**Comment by keilbeck** [comment]
This sounds reasonable.  @nicoleruiz could you add this?

**Comment by nicoleruiz** [comment]
SO:0002186 mutational_hotspot has been added.
