### ISSUE TITLE
NTR UNAAAC motif

### ISSUE THREAD

**Issue by Antonialock** [The-Sequence-Ontology/SO-Ontologies#412]
suggested def: A hexameric RNA motif consisting of nucleotides UNAAAC (where N can be any nucleotide) that targets the RNA for degradation. 

is_a SO:0001979 RNA stability element
ref: PMID:28765164 
ref: PMID:22645662

**Comment by nicoleruiz** [comment]
We have created the term SO:0002207 UNAAAC_motif as a child of RNA_stability_element.
