### ISSUE TITLE
new term request: herv insertion

### ISSUE THREAD

**Issue by thefferon** [The-Sequence-Ontology/SO-Ontologies#414]
Please add new term 'herv insertion' as a child of SO:0001837 mobile_element_insertion.

name: HERV_insertion
def: "An insertion of sequence from the HERV family of mobile elements."
is_a: SO:0001837 ! mobile_element_insertion

Thank you!

**Comment by nicoleruiz** [comment]
SO:0002187 HERV_insertion has been added.
