### ISSUE TITLE
term request for mitochondrial control region

### ISSUE THREAD

**Issue by murphyte** [The-Sequence-Ontology/SO-Ontologies#417]
I don't see a term for the mtDNA control region:
https://en.wikipedia.org/wiki/MtDNA_control_region

A short definition could be:
"non-coding region of the mitochondrial genome that controls RNA and DNA synthesis"

I'm indifferent as to what the primary term should be. It looks like most of the mito terms start with "mitochondrial", so how about:
term: mitochondrial_control_region
synonyms: MtDNA_control_region, control_region, mitochondrial noncoding region, NCR, A+T region

The D_loop is a region within the control region, so SO:0000297 could be a child of this new term.

Thanks!
-Terence

**Comment by davidwsant** [comment]
Hi Terrence,

How does this look?


[Term]
id: New_Term
name: mitochondrial_control_region
def: "The non-coding region of the   mitochondrial genome that controls RNA and DNA synthesis."   [PMID:10968878, PMID: 19407924]
synonym: "MtDNA_control_region" EXACT []
synonym: "MtDNA control region" EXACT []
synonym: "Mitochondrial DNA control region" EXACT []
synonym: "control region" EXACT   []
synonym: "Mitochondrial noncoding   region" EXACT []
synonym: "Mitochondrial NCR"   EXACT []
synonym: "Mitochondrial A+T   region" EXACT []
xref:   https://en.wikipedia.org/wiki/MtDNA_control_region "wiki"
is_a: SO:0000737 !   mitochondrial_sequence

Addition of the final line to D-loop:
[Term]
id: SO:0000297
name: D_loop
def: "Displacement loop; a region within mitochondrial DNA in which a short stretch of RNA is paired with one   strand of DNA, displacing the original partner DNA strand in this region;   also used to describe the displacement of a region of one strand of duplex   DNA by a single stranded invader in the reaction catalyzed by RecA   protein."   [http://www.ebi.ac.uk/embl/Documentation/FT_definitions/feature_table.html]
synonym: "D-loop" EXACT []
synonym: "displacement loop"   RELATED []
synonym: "INSDC_feature:D-loop"   EXACT []
xref: http://en.wikipedia.org/wiki/D_loop   "wiki"
is_a: SO:0000296 ! origin_of_replication
relationship: part_of SO:0002293 ! mitochondrial_control_region

Please let me know what you think.

Thanks,

Dave Sant

**Comment by murphyte** [comment]
For the feature_table.html link in the D-loop definition, please reference to this file instead:
http://www.insdc.org/files/feature_table.html
The EMBL link you have is likely the same, but the link itself behaves oddly for me, and I think using the official insdc.org page is preferable.

I'm also wondering about:
> is_a: SO:0000296 ! origin_of_replication
I think not all D-loops are involved in replication, and at best it's a subset of the region that I would call the origin. Is there a better way to capture that than with is_a or part_of? Is there a sometimes_part_of? (just kidding, but only sort of).

-Terence

**Comment by davidwsant** [comment]
Hi Terrence,

I agree about the link. Mine always downloaded the HTML file rather than visiting a page, but I didn't know what page it should have been replaced with. It has been updated for all instances where the old link was present. 

Does the control region always have a D-loop? If so, then maybe a simple fix is to not add the part_of relationship to D-loop, but instead add "relationship: has_part SO:0000297 ! D_loop" to the mitochondrial_control_region term. Is this correct?

Thanks,

Dave

**Comment by murphyte** [comment]
> Does the control region always have a D-loop? If so, then maybe a simple fix is to not add the part_of relationship to D-loop, but instead add "relationship: has_part SO:0000297 ! D_loop" to the mitochondrial_control_region term. Is this correct?

I'm not concerned about the relationship between the D-loop and mitochondrial_control_region. It's the existing relationship with origin_of_replication that I'm concerned about, since it's not always the case.

**Comment by davidwsant** [comment]
Is the mitochondrial_control_region also an origin of replication? Perhaps I should just add another is_a relationship: is_a: SO:0000296 ! origin_of_replication
Is this correct?

**Comment by murphyte** [comment]
sure, that's reasonable.
I think maybe D-loop should also have another parent for the non-mitochondrial use case, but I'm at a loss as to what it would be. So I think this will be fine for now, and if someone else notices the discrepancy then maybe they'll have some ideas on how to improve it.

**Comment by davidwsant** [comment]
Hi Terrence,

I was unable to add a second is_a relationship for mitochondrial_control_region. OwlTools said that the term was "unsatisfiable". I have changed the relationship slightly. What do you think of this updated version?


[Term]
id: (will probably be SO:0002293)
name: mitochondrial_control_region
def: "The non-coding region of the   mitochondrial genome that controls RNA and DNA synthesis."   [PMID:10968878, PMID: 19407924]
comment: Added as per GitHub Issue   Request #417   (https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/417)
synonym: "MtDNA_control_region"   EXACT []
synonym: "MtDNA control region"   EXACT []
synonym: "Mitochondrial DNA control   region" EXACT []
synonym: "control region" EXACT   []
synonym: "Mitochondrial noncoding   region" EXACT []
synonym: "Mitochondrial NCR"   EXACT []
synonym: "Mitochondrial A+T   region" EXACT []
xref:   https://en.wikipedia.org/wiki/MtDNA_control_region "wiki"
is_a:   SO:0000296 ! origin_of_replication
relationship: has_origin   SO:0000737 ! mitochondrial_sequence

As for D_loop, it may need some updating. Currently the is_a relationship that it has is "is_a: SO:0000296 ! origin_of_replication" Do you think it would be better as "relationship: part_of SO:0000296 ! origin_of_replication" and "is_a: SO:0001141 ! biological_region"? 

Thanks,

Dave

**Comment by davidwsant** [comment]
Hi Terence,

I was looking at the terms a little more and I realize that a non-mitochondrial D-loop (telomeric_D_loop SO:0002171) has been added. Does this account for the cases of D-loop that are not mitochondrial?

[Term]
id: SO:0002171
name: telomeric_D_loop
def: "A telomeric D-loop is a three-stranded DNA displacement loop that forms at the site where the telomeric 3' single-stranded DNA overhang (formed of the repeat sequence TTAGGG in mammals) is tucked back inside the double-stranded component of telomeric DNA molecule, thus forming a t-loop or telomeric-loop and protecting the chromosome terminus." [PMID:10338204, PMID:15071557, PMID:24012755]
comment: This definition is from GO:0061820 telomeric D-loop disassembly.
synonym: "telomeric D loop" EXACT []
is_a: SO:0000296 ! origin_of_replication

Thanks,

Dave

**Comment by murphyte** [comment]
That's helpful. 
From the wikipedia page (https://en.wikipedia.org/wiki/D-loop), there is also a description of D-loops in DNA repair, which doesn't really fit under origin_of_replication. If we were starting from scratch, I'd say we want:

1. A general "D_loop" term, higher up in the hierarchy, maybe under biological_region. It's somewhat analogous to Okazaki_fragment. Not all D-loops are origins of replication, so its current position in the hierarchy seems wrong
2. mitochondrial_D_loop, as a child of mitochondrial_control_region which is a child of origin_of_replication, and also a child of D_loop
3. telomeric_D_loop, as a child of D_loop and also telomere. I think these are NOT involved in DNA replication, so I don't think this belongs under origin_of_replication

I don't know what the implications are for moving existing entries around. It seems reasonable to me to do so, since I think the current terms are misplaced given their current definitions.

-Terence

**Comment by davidwsant** [comment]
Hi Terence,

I have added mitochondrial_control_region (SO:0002293) to the ontology as specified above. I agree that a general term "D_loop" sounds like it would be fitting. However, I want this to be consistent with INSDC. Our current term "D_loop" is SO:0000297. Theoretically this could be moved up, but the definition does not fit with that. The definition and name are taken directly from the INSDC page:


id: SO:0000297
name: D_loop
def:   "Displacement loop; a region within mitochondrial DNA in which a short stretch of RNA is paired with one strand of DNA, displacing the original   partner DNA strand in this region; also used to describe the displacement of   a region of one strand of duplex DNA by a single stranded invader in the reaction catalyzed by RecA protein."   [http://www.ebi.ac.uk/embl/Documentation/FT_definitions/feature_table.html]
synonym:   "D-loop" EXACT []
synonym: "displacement loop"   RELATED []
synonym: "INSDC_feature:D-loop"   EXACT []
xref: http://en.wikipedia.org/wiki/D_loop   "wiki"
is_a: SO:0000296 ! origin_of_replication

This specifically mentions that it is a mitochondrial DNA region. This could be renamed "mitochondrial_D_loop", but it is simply "D_loop" on the INSDC page. In an effort to keep things consistent with INSDC, I do not feel comfortable changing the name or the definition unless they are changed in INSDC. I also cannot make a new term "D_loop" because it is already being used here. 

As it is, I think we can move D_loop to "is_a: SO:0002293 ! mitochondrial_control_region".

As for creating another term, I do not think we can use "D_loop" unless it is updated in INSDC. Notice that the synonym "displacement loop" is not exact, but related. I think this should be changed to exact. 

What are your thoughts?

Thanks,

Dave Sant

**Comment by murphyte** [comment]
The INSDC definition already includes: "also used to describe the displacement of a region of one strand of duplex DNA by a single stranded invader in the reaction catalyzed by RecA protein", so the INSDC feature isn't constrained to only mitochondria. It looks like pretty-much everything that's been submitted to INSDC is for mitochondrial sequence, but I did find one exception:
https://www.ncbi.nlm.nih.gov/nuccore/AF007787.1

So I think moving SO D_loop would make it more consistent with the INSDC definition.

-Terence

**Comment by davidwsant** [comment]
I see what you mean. Thanks for pointing that out. 

How do these updates look?


[Term]
id: SO:0000297
name: D_loop
def: "Displacement loop; a region   within mitochondrial DNA in which a short stretch of RNA is paired with one   strand of DNA, displacing the original partner DNA strand in this region;   also used to describe the displacement of a region of one strand of duplex   DNA by a single stranded invader in the reaction catalyzed by RecA   protein."   [http://www.ebi.ac.uk/embl/Documentation/FT_definitions/feature_table.html]
synonym: "D-loop" EXACT []
synonym: "displacement loop"   RELATED []
synonym: "INSDC_feature:D-loop"   EXACT []
xref: http://en.wikipedia.org/wiki/D_loop   "wiki"
** is_a: SO:0001411 !   biological_region **

[Term]
id: New
name: mitochondrial_D_loop
def: "Mitochondrial displacement loop; a region within mitochondrial DNA in which a short stretch of RNA is paired with one strand of DNA, displacing the original partner DNA strand in this region." [http://www.ebi.ac.uk/embl/Documentation/FT_definitions/feature_table.html]
synonym: "Mitochondrial D loop"   EXACT []
synonym: "Mitochondrial displacement   loop" EXACT []
is_a:   SO:0002293 ! mitochondrial_control_region
is_a:   SO:0000297 ! D_loop

Thanks for pointing this out. Is there anything else this would need?

Dave

**Comment by murphyte** [comment]
You've got the old ebi feature_table.html links in these. Otherwise this looks good!

**Comment by davidwsant** [comment]
Hi Terence,

Thanks for responding to help me work through this. The D_loop relationship is now "is_a: SO:0001411 ! biological_region" and  mitochondrial_D_loop has been assigned ID SO:0002294. As with the other changes, this should be visible in the [SO Browser](http://sequenceontology.org/browser/current_release/) within about 24 hours.

Thanks,

Dave
