### ISSUE TITLE
Clarify definitions of "positive" and "negative" strands

### ISSUE THREAD

**Issue by rhdolin** [The-Sequence-Ontology/SO-Ontologies#419]
Greetings,
We are adding a field to the FHIR Sequence resource, to differentiate positive/negative (aka watson/crick) strands. The definitions we are proposing: "An absolute reference to a strand. The Watson strand is the strand whose 5'-end is on the short arm of the chromosome, and the Crick strand as the one whose 5'-end is on the long arm".

HL7 Genomics Committee members suggested that we submit a comment here, to see if it might make sense to include "watson strand" and "crick strand" into Sequence Ontology?
Thank you.

**Comment by murphyte** [comment]
One thing to consider here with definitions is that many genomic sequences aren't oriented relative to chromosome short/long arm. That includes:

1. sequences that aren't part of a genome assembly, like a BAC or a RefSeqGene/LRG genome subsequence
2. genomic sequences that aren't assembled to chromosome level (i.e. unplaced or unlocalized scaffolds)
3. chromosome-level sequences that haven't been oriented relative to cytological (short/long arm) characteristics. This is fairly common with modern assembly techniques that can assemble to chromosome-level without cytological assays. Some or all chromosomes in some species are also impossible to assay by cytological techniques at a resolution that can distinguish centromere locations and short/long arms.

This article may be useful, with a reasonably comprehensive summary of the history and issues:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3055211/

Note the last two paragraphs, where the authors propose top/forward/plus and bottom/reverse/minus to be synonyms of Watson and Crick strand, respectively, but fail to address the situation where the reference strand picked as "plus" in an assembly may not be the actual Watson strand. So in reality I'd say it's safe and reasonable to define the Watson/Crick strands based on the short/long arm definitions (which is the request here), but plus/minus are inevitably based on a reference sequence where it's _preferred_ for plus = Watson, but they shouldn't be treated as strictly synonymous.

-Terence

**Comment by davidwsant** [comment]
Hi @rhdolin and Terrence,

I think it makes sense to add these. What do you think of adding the terms with the following info?


name: Watson_strand
def: "An absolute reference to the   strand. When a chromosome has p and q arms, the Watson strand is the trand   whose 5'-end is on the short arm of the chromosome. Of note, the term 'plus   strand' is typically used for the Watson strand, but can be changed in   reference sequences based and is therefore not an exact synonym."   [PMID:21303550]
comment: Added as per GitHub Issue   Request #419   (https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/419)
synonym: "Watson strand" EXACT   []
synonym: "Top strand" EXACT []
synonym: "Forward strand" EXACT   []
synonym: "Plus strand" BROAD []
is_a: SO:0000830 ! chromosome_part


name: Crick_strand
def: "An absolute reference to the   strand. When a chromosome has p and q arms, the Crick strand is the trand   whose 5'-end is on the long arm of the chromosome. Of note, the term 'minus   strand' is typically used for the Crick strand, but can be changed in   reference sequences based and is therefore not an exact synonym."   [PMID:21303550]
comment: Added as per GitHub Issue   Request #419   (https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/419)
synonym: "Crick strand" EXACT   []
synonym: "Bottom strand" EXACT   []
synonym: "Reverse strand" EXACT   []
synonym: "Minus strand" BROAD   []
is_a: SO:0000830 ! chromosome_part

Thanks,

Dave

**Comment by murphyte** [comment]
> but can be changed in reference sequences based and

this seems like it's missing some wording?

How about:

> Of note, the term "plus strand" is typically based on a reference sequence where it's preferred for the plus strand to be the Watson strand, but might not be and "plus strand" is therefore not an exact synonym." [PMID:21303550]

**Comment by openelimu** [comment]
Thanks @davidwsant. Agree with @murphyte 's revisions, and supportive of the additions.

**Comment by davidwsant** [comment]
Hi guys,

Thanks for the help. How does this look? Also, do you agree with using BROAD synonym for "plus" and "minus"?

name: Watson_strand
def: "An absolute reference to the strand. When a chromosome has p and q arms, the Watson strand is the trand whose 5'-end is on the short arm of the chromosome. Of note, the term "plus strand" is typically based on a reference sequence where it's preferred for the plus strand to be the Watson strand, but might not be and "plus strand" is therefore not an exact synonym." [PMID:21303550]
comment: Added as per GitHub Issue Request #419 (#419)
synonym: "Watson strand" EXACT []
synonym: "Top strand" EXACT []
synonym: "Forward strand" EXACT []
synonym: "Plus strand" BROAD []
is_a: SO:0000830 ! chromosome_part

name: Crick_strand
def: "An absolute reference to the strand. When a chromosome has p and q arms, the Crick strand is the trand whose 5'-end is on the long arm of the chromosome. Of note, the term "minus strand" is typically based on a reference sequence where it's preferred for the minus strand to be the Crick strand, but might not be and "minus strand" is therefore not an exact synonym." [PMID:21303550]
comment: Added as per GitHub Issue Request #419 (#419)
synonym: "Crick strand" EXACT []
synonym: "Bottom strand" EXACT []
synonym: "Reverse strand" EXACT []
synonym: "Minus strand" BROAD []
is_a: SO:0000830 ! chromosome_part

Thanks,

Dave

**Comment by murphyte** [comment]
one typo in both definitions:
"the Watson/Crick strand is the *trand* "

Otherwise that reads well.

**Comment by davidwsant** [comment]
Thank you guys for the suggestions and comments. Watson strand has been given the ID SO:0002262 and Crick strand has been given the ID SO:0002263. As usual, these should be present on the [SO Browser](http://sequenceontology.org/browser/current_svn/) within about 24 hours.

Thanks,

Dave
