### ISSUE TITLE
What is the current SO version?

### ISSUE THREAD

**Issue by julie-sullivan** [The-Sequence-Ontology/SO-Ontologies#420]
I could not find it anywhere. I looked! (Sorry if this is obvious!!)

We need to be able to track the changes in different versions.

Thank you!!!

**Comment by raf64flo** [comment]
Does that answer: https://github.com/The-Sequence-Ontology/SO-Ontologies/releases/latest ?

**Comment by julie-sullivan** [comment]
Yes it does!! Just what I need. Sorry I missed that! Thanks. :)
