### ISSUE TITLE
NTR transcription termination signal

### ISSUE THREAD

**Issue by ValWood** [The-Sequence-Ontology/SO-Ontologies#421]
synonym
polyA site downstream element
polyA site associated transcription termination signal
Nrd1-dependent terminator
Nrd1 binding motif
motif UGUAA/G and UCUUG motifs also reported as (A(U)GUA)

parent transcription_regulatory_region (SO:0001679)

Ref: PMID:28367989 (and references therein)
Def: termination signal preferentially observed downstream of polyadenylation signal

**Comment by nicoleruiz** [comment]
I will work on this and get it added by tomorrow.

**Comment by ValWood** [comment]
Thanks Nicole!

**Comment by nicoleruiz** [comment]
We have SO:0000141 terminator and SO:0000951 eukaryotic_terminator terms as children of transcription_regulatory_region. Would it be better for this term to be placed under one of these terms?

**Comment by ValWood** [comment]
Oh yes please. Under SO:0000951 eukaryotic_terminator
v
