### ISSUE TITLE
New synonym request for ‘ultracontig’ (SO:0000719) for Bayer Crop Science

### ISSUE THREAD

**Issue by luistorricoporto** [The-Sequence-Ontology/SO-Ontologies#422]
**_Could you add the synonym ‘pseudochromosome’ to the term ‘ultracontig’ (SO:0000719)?_**

[Term]
id: SO:0000719
name: ultracontig
def: "An ordered and oriented set of scaffolds based on somewhat weaker sets of inferential evidence such as one set of mate pair reads together with supporting evidence from ESTs or location of markers from SNP or microsatellite maps, or cytogenetic localization of contained markers." [FB:WG]
subset: SOFA
synonym: "superscaffold" RELATED []
synonym: " pseudochromosome" EXACT []
is_a: SO:0001876 ! partial_genomic_sequence_assembly

**Comment by nicoleruiz** [comment]
This has been added.
