### ISSUE TITLE
Definition and synonym for ‘genomic_DNA’ (SO:0000991) for Bayer Crop Science

### ISSUE THREAD

**Issue by luistorricoporto** [The-Sequence-Ontology/SO-Ontologies#423]
**_Could you add a definition to the term ‘genomic_DNA’ (SO:0000991)? We propose the following description:
•	DNA which is located in the genome and is able to be transmitted to the offspring.
Could you also add the synonym ‘gDNA’ to this term?_**

[Term]
id: SO:0000991
name: genomic_DNA
def: "DNA located in the genome and able to be transmitted to the offspring." [BCS:etrwz]
comment: This term is mapped to MGED. Do not obsolete without consulting MGED ontology.
synonym: "genomic DNA" EXACT []
synonym: "gDNA" EXACT []
is_a: SO:0000352 ! DNA

**Comment by nicoleruiz** [comment]
I have added this definition and the requested synonym to SO:0000991 genomic_DNA.
