### ISSUE TITLE
New term request: ‘presence_absence_variation’ (for Bayer Crop Science)

### ISSUE THREAD

**Issue by luistorricoporto** [The-Sequence-Ontology/SO-Ontologies#424]
**_Could you add the term ‘presence_absence_variation’ into SO?
The definition and parent (SO:0001019 ! copy_number_variation) proposed below are based on the following papers:_**
-	High-resolution genetic mapping of maize pan-genome sequence anchors. Author: Fei Lu et. Al. Published: 16 Apr 2015 
-	Maize Inbreds Exhibit High Levels of Copy Number Variation (CNV) and Presence/Absence Variation (PAV) in Genome Content. Author: N.M. Springer et.al. Publication: Nov 2009

**_The term to be added would be:_**

[Term]
id: SO:xxxxxxx
name: presence_absence_variation
def: "A variation qualifying the presence of a sequence in a genome which is entirely missing in another genome." [BCS:bbean]
comment: Requested by Bayer Crop Science March, 2018.
synonym: "PAV" EXACT []
synonym: "presence/absence variation" EXACT []
synonym: "presence-absence variation" EXACT []
synonym: "presence/absence_variation" EXACT []
synonym: "presence-absence_variation" EXACT []
is_a: SO:0001019 ! copy_number_variation

**Comment by nicoleruiz** [comment]
SO:0002210 presence_absence_variation has been added.
