### ISSUE TITLE
New term request: ‘genomic_DNA_contig’ (for Bayer Crop Science)

### ISSUE THREAD

**Issue by luistorricoporto** [The-Sequence-Ontology/SO-Ontologies#425]
**_Could you add the term ‘genomic_DNA_contig into SO?
The parent and the definition proposed below are based on other contig elements described in SO._**

**_The term to be added would be:_**

[Term]
id: SO:xxxxxxx
name: genomic_DNA_contig
def: "A contig composed of genomic DNA derived sequences." [BCS:etrwz]
comment: Requested by Bayer Crop Science March, 2018.
synonym: "genomic DNA contig" EXACT []
synonym: "gDNA contig" EXACT []
synonym: "gDNA_contig" EXACT []
is_a: SO:0000149 ! contig

**Comment by nicoleruiz** [comment]
SO:0002209 genomic_DNA_contig has been added.
