### ISSUE TITLE
Ribozyme_stability_element (requested on behave of the SBOL Developers Group)

### ISSUE THREAD

**Issue by cjmyers** [The-Sequence-Ontology/SO-Ontologies#426]
Name: ribozyme_stability_element
Definition: "A ribozyme motif that affects the stability of RNA.”
Comment: “Requested by the SBOL developers group March 2018.
is_a SO:0000374 (ribozyme)
has_quality SO:0001979 (RNA_stability_element)

**Comment by JS3xton** [comment]
Consider also:

has_quality SO:0001977 (Ribonuclease Site)
