### ISSUE TITLE
NTR mRNA gene

### ISSUE THREAD

**Issue by ValWood** [The-Sequence-Ontology/SO-Ontologies#427]
Hi,

I wonder if it is possible to get  a term for mRNA_gene?

Terms exist for 

rRNA_gene
scRNA_gene
snRNA_gene
snoRNA_gene
tRNA_gene
etc.... so this seems as though it should be added for consistency. I would like to use it in a GO annotation extension.

Def, a gene that encodes for a messenger RNA

Thanks

Val

Note to self, for/f2202f3e99350d80/

**Comment by ValWood** [comment]
Hi,

is it possible to get this term or do you need anything else?

thanks

Val

**Comment by murphyte** [comment]
HI Val -- How would that be different from protein_coding_gene (SO:0001217)? A mRNA is an RNA that encodes a protein, thus any gene encoding a mRNA should express a protein. mRNA (SO:0000234) even has the synonym "protein_coding_transcript".

-Terence

**Comment by ValWood** [comment]
oops, missed it... I though it was strange that it wasn't there, but I was so focussed on the RNA part for the other targets!
