### ISSUE TITLE
Distinguishing term for Circular Plasmid

### ISSUE THREAD

**Issue by jakebeal** [The-Sequence-Ontology/SO-Ontologies#428]
Current term "Plasmid SO:0000155" covers both circular and linear plasmids:

> A self replicating, using the hosts cellular machinery, often circular nucleic acid molecule that is distinct from a chromosome in the organism.

The SBOL Visual community is in the process of adding a glyph to specifically represent circular plasmids, and we would like to be able to associate that glyph with an SO term that is also scoped in this way.

Accordingly, can you please add a child of SO:0000155 that covers only circular plasmids?

**Comment by nicoleruiz** [comment]
SO:0002211 circular_plasmid and SO:0002212 linear_plasmid were added as children of SO:0000155.
