### ISSUE TITLE
Proposing LARD and TRIM for non-autonomous retrotransposons

### ISSUE THREAD

**Issue by sestaton** [The-Sequence-Ontology/SO-Ontologies#429]
The LARD and TRIM retrotransposons are found in many eukaryotes, and were described about 15 years ago. These elements have been shown to be involved in a number of important phenotypes and I propose new terms for properly annotating and distinguishing them from the extremely abundant LTR retrotransposons.

For LARDs:

    SO Term: LARD
    Description: LARD elements range in size from 5.5 kb to 8.5 kb. The LARDs identified in barley and other Triticeae have LTRs ~5.5 kb and an interal domain of ~3.5 kb. LARDs lack coding domains and thus do not encode proteins.
    Synonyms: Large Retrotransposon Derivatives
    DB Xrefs: URL: http://www.genetics.org/content/genetics/166/3/1437.full.pdf
    Parent: LTR_retrotransposon (SO:0000186)

For TRIMs:

    SO Term: TRIM
    Description: TRIM elements have terminal direct repeat sequences of 100-250 bp in length that flank an internal domain of 100–300 bp. TRIMs lack coding domains and thus do not encode proteins.
    Synonyms: Terminal-repeat retrotransposons in minature
    DB Xrefs: URL: http://www.pnas.org/content/pnas/98/24/13778.full.pdf
    Parent: LTR_retrotransposon (SO:0000186)

I am proposing LARD and TRIM as terms to follow the naming of style of [MITEs](http://www.sequenceontology.org/browser/current_svn/term/SO:0000338).  

For reference, I have methods that I've developed for annotating these elements (in [Tephra](https://github.com/sestaton/tephra)) and it would useful to give them a standard term. I know people in the TE community would appreciate this also.

**Comment by davidwsant** [comment]
Hi @sestaton,

I apologize for the delayed response. We had a change in staff and I am just now getting to old issue requests. 

Both terms have been added. LARD has been assigned ID SO:0002260 and TRIM has been assigned ID SO:0002261. These have been pushed to the GitHub page and should be visible on the [SO Browser](http://sequenceontology.org/browser/current_svn/) within about 24 hours. 

Thanks,

Dave

**Comment by sestaton** [comment]
Much appreciated, thanks for the update.
