### ISSUE TITLE
What term should I use for RNaseP?

### ISSUE THREAD

**Issue by dbolser-ebi** [The-Sequence-Ontology/SO-Ontologies#430]
Hello,

I have 11 genes with the biotype 'P_RNA', however, their annotation puts them in 4 different Rfam families:
* http://rfam.xfam.org/family/RF00373 (RNaseP_arch)
* http://rfam.xfam.org/family/RF00009 (Nuclear RNase P)
* http://rfam.xfam.org/family/RF00010 (Bacterial RNase P class A)
* http://rfam.xfam.org/family/RF00011 (Bacterial RNase P class B)

Fortunately, these are all in the same clan:
http://rfam.xfam.org/clan/CL00002 (RNaseP)

I'm looking for a SO compliant biotype, as none of the above names match a search against SO.

Many thanks,
Dan.

**Comment by davidwsant** [comment]
Hi @dbolser-ebi,

I apologize for the delay in response. We had a chance in staff and I am now returning to old issues. 

I believe the best term to use for 'P_RNA' would be the SO term 'RNase_P_RNA' which is [SO:0000386](http://sequenceontology.org/browser/current_svn/term/SO:0000386). I hope this answers your question. If you still have any questions, feel free to open this issue.

Thanks,

Dave
