### ISSUE TITLE
NTR: SUMO interaction motif

### ISSUE THREAD

**Issue by mah11** [The-Sequence-Ontology/SO-Ontologies#434]
Hi,

We've learned of the existence of this, via the discovery that S. pombe Stn1 has one:

id: SO:new
name: SUMO_interaction_motif
def: "A polypeptide region that mediates binding to SUMO. The motif contains a hydrophobic core sequence consisting of three or four Ile, Leu, or Val residues plus one acidic or polar residue at position 2 or 3." [PMID:15388847,PMID:16524884]
synonym: "SUMO interaction motif" EXACT []
synonym: "SUMO binding motif" EXACT []
synonym: "SIM" EXACT []
synonym: "SBM" EXACT []
is_a: SO:0001093 ! protein_protein_contact

(The pombe paper I'm looking at is PMID:29774234, but I didn't use it directly to make up the definition above.)

thanks,
Midori

**Comment by davidwsant** [comment]
Hi @mah11,

I apologize for the delayed response. We had a change in staff and nobody has looked at requests for some time. 

Thank you for this detailed request. It was very easy to process this. The term has been added (SO:0002235) and should be visible in the [SO Browser](http://sequenceontology.org/browser/current_release/) within about 24 hours. 

Thank you,

Dave

**Comment by mah11** [comment]
Great, thank you!
