### ISSUE TITLE
add to def SO:0001860

### ISSUE THREAD

**Issue by Antonialock** [The-Sequence-Ontology/SO-Ontologies#435]
Hello,

could you please add the pombe telomeric repeat consensus TTAC(0-1)A(0-1)G(1-8)
to the term SO:0001860 thanks!

ref page 208 in "Chromatin Structure and Gene Expression":
Sarah C. Elgin, Sarah C. R. Elgin, Jerry L. Workman
Oxford University Press, 2000 - Science 

https://books.google.co.uk/books?id=qtMwAAFVdVQC&pg=PA208&lpg=PA208&dq=pombe+consensus+telomere+repeat&source=bl&ots=cZfRH3bWD_&sig=-iTUOnoir0YOjZEx8ukeT6yggGc&hl=en&sa=X&ved=0ahUKEwi4xffyqdPbAhVJZ8AKHXGyBi04ChDoAQgxMAE#v=onepage&q=pombe%20consensus%20telomere%20repeat&f=false

**Comment by nicoleruiz** [comment]
This has been added.
