### ISSUE TITLE
Zas1_recognition_motif

### ISSUE THREAD

**Issue by ValWood** [The-Sequence-Ontology/SO-Ontologies#436]
A DNA binding motif recognised by the Zas1 protein

A DNA motif to which the S. pombe Zas1 protein binds. The consensus sequence is 5'-(Y)CCCCAY-3'; 

DNA_motif (SO:0000713)

PMID:29735745

**Comment by nicoleruiz** [comment]
SO:0002215 Zas1_recognition_motif has been added as a child of DNA_motif.

**Comment by ValWood** [comment]
thanks!
