### ISSUE TITLE
Update SO:0001900

### ISSUE THREAD

**Issue by Antonialock** [The-Sequence-Ontology/SO-Ontologies#437]
Hello,

I would like the name and def of SO:0001900 tweaked 

new primary name: Atf1/Pcr1 recognition motif
new consensus:  GNVTA**TGACGT**CATNBNC
Reference: PMID:15716492 

Cheers
Antonia

**Comment by davidwsant** [comment]
Hi @Antonialock,

We have had some problems with compatibility when we change names, so I added an exact synonym. This will be available on the [SO Browser](http://sequenceontology.org/browser/current_release/) within the next 24 hours or so. 

Thanks,

Dave
