### ISSUE TITLE
DNaseI_hypersensitive_site (SO:0000685) misspelled

### ISSUE THREAD

**Issue by julie-sullivan** [The-Sequence-Ontology/SO-Ontologies#438]
`DNAseI_hypersensitive_site` is spelled two different ways, and it's breaking my scripts.

This is the type of a feature in the NCBI GFF file:

`DNaseI_hypersensitive_site`

https://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/GFF/

The type in SO is spelled with a different case:

`DNAseI_hypersensitive_site`

http://www.sequenceontology.org/browser/current_svn/term/SO:0000685

Which one is correct? I did a quick google search, and most papers refer to `DNase I`. I understand that this is not conclusive! :)

Thanks!

**Comment by murphyte** [comment]
Hi SO -- could you add a synonym for this one? That seems like a straightforward solution for the ambiguity in proper capitalization.

-Terence

**Comment by davidwsant** [comment]
Hi @julie-sullivan and @murphyte,

Thank you for bringing this to our attention. This has been updated and the term spelling and INSDC qualifier should now be consistent with the NCBI GFF file. 

Thanks,

Dave
