### ISSUE TITLE
pho7 binding site

### ISSUE THREAD

**Issue by Antonialock** [The-Sequence-Ontology/SO-Ontologies#440]
Hello,

could I please have a term for the pho7 binding site present in the promoters of fission yeast phosphate-regulated genes
 [5'-TCG(G/C)(A/T)xxTTxAA]

PMID:28811350

**Comment by Antonialock** [comment]
Hi,

would it be possible for someone to have a look at this anytime soon? It is for a community curation session so we are keen to have the information displayed sooner rather than later.

**Comment by nicoleruiz** [comment]
I apologize for the delay in getting to this request. We are currently in the process of updating our curation process and I'm preparing to graduate and hand over curation tasks to another student. Karen and I are meeting early next week to work on some tickets and I will make sure we take care of this one too.

@keilbeck Let's make sure we get to this ticket next week.

**Comment by Antonialock** [comment]
Thank you! Apologies for chasing, I know everyone is busy.

**Comment by nicoleruiz** [comment]
SO:0002216 Pho7_binding_site has been added as a child of SO:0002216 promoter_element.
