### ISSUE TITLE
true path violation for enhancer descendants

### ISSUE THREAD

**Issue by ValWood** [The-Sequence-Ontology/SO-Ontologies#441]
http://www.sequenceontology.org/browser/current_svn/term/SO:0000165

defined
A cis-acting sequence that increases the utilization of (some) eukaryotic promoters, and can function in either orientation and in any location (upstream or downstream) relative to the promoter.

has descendants
enhancerRNA (SO:0001870)
splice_enhancer (SO:0000344) ??

**Comment by keilbeck** [comment]
So splice_enhancer is not an enhancer in the sense of gene expression and we need to remove that isa relationship.

**Comment by ValWood** [comment]
Yep (although I think that was probably a statement not a question!)
v

**Comment by davidwsant** [comment]
Hi Val,

Thanks for bringing this to our attention. It has been updated. The [SO Browser](http://sequenceontology.org/browser/current_release/) should be updated within about 24 hours. 

Thanks,

Dave
