### ISSUE TITLE
antisense_lncRNA (SO:0001904) vs antisense_RNA (SO:0000644)

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#443]
Hi

I am looking at this term:

**antisense_lncRNA (SO:0001904)**
Def: Non-coding RNA transcribed from the opposite DNA strand compared with other transcripts and overlap in part with sense RNA.
Child of: lnc_RNA (SO:0001877), which itself a child of ncRNA (SO:0000655)

and I am wondering why it is not also a child of this term:
**antisense_RNA (SO:0000644)**
Def: "Antisense RNA is RNA that is transcribed from the coding, rather than the template, strand of DNA. It is therefore complementary to mRNA."
Child of: ncRNA (SO:0000655)

Is it because an 'antisense_RNA' is defined to be specifically transcribed from a 'coding' strand and thus is complementary to 'mRNA', whereas this is not necessarily true of a 'antisense_lncRNA' - i.e. the latter could be antisense to another non-coding RNA?

I ask because there are 100s of D. melanogaster ncRNAs in FlyBase that are >200nt and which are antisense (in part) to a mRNA, and I'm wondering which of these terms we should use to annotate?  As things stand, I think we'd have to use both, but that's not great as several applications require we use a single label for ncRNA type.

Any insights appreciated!

**Comment by keilbeck** [comment]
Hi
I don't have a good answer for this.
I have not thought about this in a while but lncRNA are not usually overlapping with protein coding sequence right? If this premise has changed, then the definitions may not make sense anymore. 

Is there a good reference for lncRNA that overlap CDS? I am wondering if the best solution is to add a child term that has both of those terms you mention as a parent. Something like antisense_lncRNA_CDS_overlap  This would be ugly but could work.

**Comment by sjm41** [comment]
Hi Karen

Here are 5 examples of a D. melanogaster lncRNAs (i.e. ncRNAs >200nt) that are antisense to a mRNA (including coding regions) of an overlapping gene:
asRNA:CR11538-RC (2386 nt) (http://flybase.org/reports/FBtr0347179.html)
asRNA:ASTR-RA (1374 nt) (http://flybase.org/reports/FBtr0309985.html) (see PMID:26504165)
asRNA:CR42254-RG (1372 nt) (http://flybase.org/reports/FBtr0347232.html)
asRNA:CR43637-RA (1117 nt) (http://flybase.org/reports/FBtr0309994.html)
asRNA:CR43820-RA (807 nt) (http://flybase.org/reports/FBtr0332216.html)

I'm also attaching a GBrowse screenshot of the first example below.
![screen shot 2018-09-06 at 07 52 10](https://user-images.githubusercontent.com/16306861/45140869-251dc780-b1ac-11e8-9476-6de7d034f670.png)

So, for these (and many others), it seems that "antisense_lncRNA (SO:0001904)" is most appropriate, given current definition. That's fine, but that means that these guys aren't categorized under "antisense_RNA (SO:0000644)" and so don't show up if you search using that term (because antisense_lncRNA isn't a child of it).

From my (somewhat naive!) point of view, making antisense_lncRNA a child of antisense_RNA (in addition to being a child of lnc_RNA) would work.  Or is that problematic for a reason I'm missing?

**Comment by sjm41** [comment]
Thinking some more...

I guess the main issue is that the def for antisense_RNA says it is "transcribed from the *coding strand*" (i.e. not necessary the *coding region*) and is "complementary to *mRNA*" (i.e. UTRs + CDS). So I think that means a ncRNA (of any length) that is antisense (at least in part) to a UTR and/or a CDS of a protein-coding gene should have this term. The only exclusions would be ncRNAs that are antisense to *introns* of an overlapping gene model.
Would you agree?

If "antisense_lncRNA" follows the same constraints (i.e. the lncRNA must be antisense to a UTR or CDS) then I think making it a child of "antisense_RNA" is correct.
The D. melanogaster antisense lncRNAs I'm talking about are all antisense to UTR/CDS.

**Comment by sjm41** [comment]
Hi, There's been no response to this for over 2 years :-(
Is someone able to review this ticket and implement the proposal above (or suggest a different approach)?

**Comment by keilbeck** [comment]
Dave – can you look at this?
Thanks
--K

**Comment by davidwsant** [comment]
Hi @sjm41,

I have added the relationship 'is_a' antisense_RNA to antisense_lncRNA. If there are any changes requested here that were not addressed, please comment and I will reopen the issue.

Thanks,

Dave

**Comment by sjm41** [comment]
Works for me, thanks!
