### ISSUE TITLE
substitution/complex_alteration : new term request or change in the ontology

### ISSUE THREAD

**Issue by sabrinatoro** [The-Sequence-Ontology/SO-Ontologies#444]
We (The Alliance of Genome Resources, Variants working group) need a term along the lines of:
Proposed definition: “A sequence_alteration which includes multiple mutational events within a contiguous region relative to a reference genome sequence. Generally a region of reference sequence has been deleted and an alternative sequence is present in its place." 
- We would like this term to encompass substitutions of the same length, of a different length, and of an unknown length.  
- We would like the term to be a parent of MNV, ‘multiple nucleotide variant (substitution)’ (SO:0002007).

The term we need basically corresponds to SO:1000005 complex_substitution:
“When no simple or well defined DNA mutation event describes the observed DNA change, the keyword "complex" should be used. Usually there are multiple equally plausible explanations for the change.”
- EXCEPT that the parent of SO:1000005 has the constraint that the length be the same:
SO:1000002 substitution  “A sequence alteration where the length of the change in the variant is the same as that of the reference.”
- Is this requirement that the length of the change be the same for the term ‘substitution’ necessary (or desirable)?

If the constraint that a substitution must be of the same length cannot be removed, we propose a new term: ‘complex_alteration’ for the definition above.
- This would be a child of ‘sequence_alteration’
- We would like the term to be a parent of MNV (SO:0002007), ‘multiple nucleotide variant (substitution)’. (Multiple parents for MNV term.)

(see also ticket #445 )

**Comment by sabrinatoro** [comment]
@keilbeck, we would love to discuss this with you. 
Could you send me an email with your available time? We usually meet on Fridays, 9am PST. However we can meet at a different time too.

**Comment by davidwsant** [comment]
Hi @sabrinatoro,

I am trying to clean up old issue requests. I do not have any notes on whether changes were made to the ontology for this, but Issue #445 indicates that other discussions have taken place which may have included the issues here. I am going to close out the issue, but the issue is not deleted from GitHub. If this issue has not been resolved, please re-open the issue and we can discuss options.

Thanks,
Dave
