### ISSUE TITLE
Clarify text for SO:0001621

### ISSUE THREAD

**Issue by ahwagner** [The-Sequence-Ontology/SO-Ontologies#446]
_SO:0001621 - NMD_transcript_variant_ is described as:

> A variant in a transcript that is the target of NMD.

NMD is not a defined acronym anywhere in this entry. This could be clarified to read instead:

> A variant in a transcript that is the target of nonsense-mediated mRNA decay

**Comment by davidwsant** [comment]
Hi @ahwagner, 

I have updated the term to include the definition of NMD as requested. I apologize for the delay, we had a change in staff. the updated definition should appear on the SO Browser within about 24 hours.

Thanks,

Dave
