### ISSUE TITLE
Spelling mistake in SO_1000142

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#447]
SO_1000142:
dexstrosynaptic_chromosome

Should be "dextrosynaptic_chromosome"

**Comment by davidwsant** [comment]
Hi @sjm41,

Thank you for bringing this spelling error to our attention. This has been corrected. The [SO Browser](http://sequenceontology.org/browser/current_release/) should be updated within about 24 hours. 

Thanks,

Dave

**Comment by sjm41** [comment]
I'd completely forgotten about this Thanks for fixing!
