### ISSUE TITLE
Improved ontology for eukaryotic single-exon coding sequences

### ISSUE THREAD

**Issue by Roddyjocif** [The-Sequence-Ontology/SO-Ontologies#448]
Hi, 
A paper published few days ago propose a new ontology for eukaryotic "single-exon genes" (https://academic.oup.com/database/article/doi/10.1093/database/bay089/5099430) and I would like to know if I can add these new definitions in Sequence Ontology Project. If so, How can I do this?
This new ontology describes the features of biological sequences (~3000 human CDS) used in sequence annotation and biological databases, it could provides the opportunity to improve the detection of gene associations with disorders including cancers, neurological and developmental diseases. 
Many thanks in advance...

**Comment by davidwsant** [comment]
Hi @Roddyjocif,

I apologize for the delay, we had a change in staff. Has this ontology already been built? How many terms are there present in this ontology? It is now possible to use a pull request and update the SO yourself and have us review it afterward, but I think it might require a little more discussion than is allowed through pull requests.  Please let me know any more about the ontology that you would like to merge. 

Thank you,

Dave Sant

**Comment by davidwsant** [comment]
Hi @Roddyjocif,

I am in the process of cleaning up old issue requests. As I have not heard back in approximately 1 month, I am going to mark this as closed. This issue is not deleted, and you are welcome to re-open this issue if you have responses about the ontology.

Thank you,

Dave Sant
