### ISSUE TITLE
xref url in SO:0001587 incorrect

### ISSUE THREAD

**Issue by sramachand** [The-Sequence-Ontology/SO-Ontologies#449]
Hi,
One of the xrefs in SO:0001587 (stop_gained) appears to incorrect. The URL is: xref: http:www.ensembl.org/info/genome/variation/predicted_data.html#consequences. 

It is missing the // but even after adding the http://, I get a Page not found error. Is it supposed to be a link to this page?  http://ensembl.org/info/genome/variation/prediction/predicted_data.html or http://ensembl.org/info/genome/variation/prediction/consequences.jpg. 

Thanks
Sridhar

**Comment by davidwsant** [comment]
Hi @sramachand,

I apologize for the delayed response to your issue request. We had a change in staff. Thank you for bringing the incorrect website to our attention. The xref now been updated to http://ensembl.org/info/genome/variation/prediction/predicted_data.html as you had pointed out.

Thanks,

Dave
