### ISSUE TITLE
term request: polyA_site_cluster

### ISSUE THREAD

**Issue by murphyte** [The-Sequence-Ontology/SO-Ontologies#450]
I'd like to request a new term "polyA_site_cluster"
definition: A region defined by a cluster of experimentally determined polyadenylation sites, typically less than 25 bp in length and associated with a single polyadenylation signal.
parent of: polyA_site (SO:0000553)
child of: three_prime_UTR (SO:0000205)
synonym: "polyA_cluster"

It's common practice to cluster polyA sites, and some studies make that clustering available as a range (e.g. http://polyasite.unibas.ch/) rather than defining each individual polyA site observed within the range. So it would help to have an SO term to associate with the parent cluster region.

Thanks!

**Comment by davidwsant** [comment]
Hi Terrence,

I have looked through the literature, and it appears as though the term polyA cluster is only referenced by the single publication. We typically do not add terms that are associated with specific programs. It is likely that this term will gain traction in the literature, at which time it would be more appropriate to add the term.

Thanks,

Dave

**Comment by murphyte** [comment]
While the exact phrase varies, the process of clustering polyA sites mapped in a small region (often a 24-bp window) is common. Here's a small sampling of papers:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1899096/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3847777/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4407891/

without a specific term, what SO term would you suggest? I don't see anything else applicable other than very generic region terms.

**Comment by davidwsant** [comment]
Hi Terrence,

Thank you for finding those papers. That helped me clear things up. That was all that was needed to show that the term has been around.

The term polyA_site_cluster has now been assigned an ID SO:0002259. It has been pushed to the GitHub site and should be visible on the [SO Browser](http://sequenceontology.org/browser/current_svn/) within about 24 hours. 

Thanks,

Dave

**Comment by murphyte** [comment]
great, thanks!
