### ISSUE TITLE
'stem_loop' children 'stem' and 'loop' - giving the ability to differentiate between the stem and loop regions.

### ISSUE THREAD

**Issue by RichardJActon** [The-Sequence-Ontology/SO-Ontologies#451]
I've been doing some work looking at tRNA genes and it would be useful to be able to create more detailed GFF3 files with a full description of the stem-loop substructure.

A further child of stems might be non-complimentary regions to indicate regions in a stem that are not exact palindromes of it partner.

**Comment by keilbeck** [comment]
First off, sorry we are so late getting back to you on this. 

I think you are asking for parts of stem_loop

stem_loop 
  part stem
    kind of non_complimentary_stem
  part loop

@davidwsant could you help figure out the definitions of these terms? The parts must also be child terms of a different root node probably RNA_sequence_secondary_structure

--K

**Comment by keilbeck** [comment]
stem_loop
--part stem
----kind of non_complimentary_stem
--part loop

**Comment by davidwsant** [comment]
Hi Richard,

I apologize that this has again taken a delay. I thought I had created the terms, but I had not. The terms have now been created. Please let me know if you have any changes to the names or definitions of the terms created. The [SO Browser](http://sequenceontology.org/browser/current_svn/) should be updated within about the next 24 hours.

Thanks,

Dave

id: SO:0002253
name: stem_loop_region
def: "A portion of a stem loop secondary structure in RNA." 
is_a: SO:0000122 !   RNA_sequence_secondary_structure
relationship: part_of SO:0000313 !   stem_loop

id: SO:0002254
name: loop
def: "The loop portion of a stem loop, which is not folded back upon itself. " 
is_a: SO:0002253 !   stem_loop_region


id: SO:0002255
name: stem
def: "The portion of a stem loop where the RNA is folded back upon itself. "
is_a: SO:0002253 ! stem_loop_region


id: SO:0002256
name: non_complimentary_stem
def: "A region of a stem in a stem  loop structure where the sequences are non-complimentary." 
is_a: SO:0002255 ! stem
