### ISSUE TITLE
term request: unaltered_function

### ISSUE THREAD

**Issue by ahwagner** [The-Sequence-Ontology/SO-Ontologies#452]
For describing the functional impact of variants, there needs to be an analogous concept to `wild_type (SO:0000817)`, specifically a `functional_variant` that does not alter the function of the gene product.

I propose the following addition to the sequence ontology to cover this concept:
```
name: unaltered_function
parent: functional_variant (SO:0001536)
definition: A sequence variant whereby the function of the gene product is unchanged.
```

**Comment by davidwsant** [comment]
Hi Alex,

I apologize for the delay in response. We had a transition in the personnel and are just getting to updating some terms in Sequence Ontology. A new term has been created that fulfills this request:

function_retained_variant (SO:0002219): A sequence variant in which the function of a gene product is retained with respect to a reference.
http://www.sequenceontology.org/browser/current_svn/term/SO:0002219

Thank you for your input.
