### ISSUE TITLE
ncRNA of Transposon origin

### ISSUE THREAD

**Issue by Paul-Davis** [The-Sequence-Ontology/SO-Ontologies#453]
Back in 2015 these terms were requested(#299 ):

Transposable_element_pseudogene (SO:0001897)
and
transposable_element_CDS (SO:0001896) 

Do you think it would be appropriate to have:

transposable_element_ncRNA with Parent ncRNA(SO:0000655) and transposable_element (SO:0000101)

This would be used to annotate ncRNAs that reside within the span of a transposable_element.

Background: We have a bacterial transposon that jumped into one of the C. elegans Fosmids used in the generation of the reference genome. This remains marked up in the reference genome and I am in the process of suppressing the ncRNA annotations, but don't want to delete them, just treat them like we do CDSs and Pseudogenes from Transposable elements.

Paul

**Comment by Paul-Davis** [comment]
Now looking at:
transposable_element_pseudogene
transposable_element_CDS
transposable_element_ncRNA

Should these be moved out into their own branch?

**Comment by murphyte** [comment]
Paul -- for the C. elegans Tn10 insertion, I'd be inclined to annotate it as sequence_alteration_artifact (SO:0002172) rather than a transposon, on the basis that it is not a transposon that exists in C. elegans. And with that view, I'm not sure there's value in retaining the two ncRNAs in any form. My 2 cents -- I'm sure there will be many different viewpoints on this.

-Terence

**Comment by Paul-Davis** [comment]
Thanks @murphyte, we are going to be changing the way the region is marked up in our ENA records and removing the ncRNAs from the native transcript set, but as the object has existed in the database we need to retire them inline with what we do with all Transposon genes so having a SO compliant term as a classifier is still desirable.

P

**Comment by davidwsant** [comment]
Hi Paul,

I have looked at the SO terms transposable_element_pseudogene, transposable_element_CDS and transposable_element_ncRNA. All of them have two parents, one of which is transposable_element and the other is the other part of the name of the term. I believe this is the correct way to classify them. I do not believe that these terms should be moved to a separate branch as they do seem to fit within their assigned positions. Please comment with specific suggestions such as the name and location of the branch along with reasoning or publications regarding the matter if you still believe a separate branch must be created.

Thank you,

Dave
