### ISSUE TITLE
splicing_regulatory_region

### ISSUE THREAD

**Issue by ValWood** [The-Sequence-Ontology/SO-Ontologies#454]
should not be is_a 
transcription_regulatory_region (SO:0001679)

http://www.sequenceontology.org/browser/current_svn/term/SO:0001056

**Comment by davidwsant** [comment]
I can understand where you are coming from as the regulation of splicing is not part of regulating the process of transcription, but the definition for the parent term is "A regulatory region that is involved in the control of the process of transcription." I do not see a better location in SO for this term for the time being. If you find a specific parent term that you feel is more more fitting, please feel free to comment again. 

Thanks,

Dave

**Comment by ValWood** [comment]
Yes I think it's fine!
