### ISSUE TITLE
NTR: PRE-element RNA binding 

### ISSUE THREAD

**Issue by ValWood** [The-Sequence-Ontology/SO-Ontologies#455]
A cis-acting element involved in RNA stability found in the 3' UTR of some RNA (consensus UGUAAAUA).

**Comment by ValWood** [comment]
PMID:30601114

parent three_prime_UTR

**Comment by davidwsant** [comment]
Hi Val,

I am not finding very many publications on pre-element RNA-binding. I have found two publications with PMIDs 28236743 and 29625267. Both of these mention that they are MicroRNA-21. Is this what you are referring to? If not, could you please give the reference for a couple of publications that describe pre-element RNA binding? 

Thanks,

Dave

**Comment by ValWood** [comment]
Hi Dave it's the one above PMID:30601114

Here PRE is an abbreviation for Pumilio-response elements  (I  should have included that for exact synonym).

You won't find many papers because it is only recently identified:
https://www.pombase.org/reference/PMID:30601114

cheers

Val

**Comment by davidwsant** [comment]
Hi Val,

Sorry I didn't add this after your response last time. I realized it was open today and just added it. New term SO:0002234 pumilio_response_element has been added. Like the other term, it will probably take a day or so for the [SO Browser](http://sequenceontology.org/browser/current_release/) to be updated and include the term. 

Thanks,

Dave
