### ISSUE TITLE
PURLs for different SO flavours

### ISSUE THREAD

**Issue by Clare72** [The-Sequence-Ontology/SO-Ontologies#456]
You have http://purl.obolibrary.org/obo/so.obo linking to the current so.obo, but I was not able to find a PURL linking to the current so-simple.obo.
Please can you make one if it does not exist and make it easy to find (on repository, wiki and/or obofoundry page).

**Comment by cmungall** [comment]
This is a good suggestion!

Anyone can make a suggestion for new PURLs by making a pull request here: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/so.yml (but only SO team or OBO admins can merge this)

Don't worry if this doesn't make sense - I can go ahead and start the process. First, would it be OK if we called this "so-basic" as this is more in line with standard naming conventions in OBO? It would still resolve to the so-simple file.

**Comment by Clare72** [comment]
Thanks, that would be great!

**Comment by Clare72** [comment]
Is it just a matter of adding:
`- so-basic.obo: https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/so-simple.obo`
under products in the so.yml file?
I could do that and make a pull request if that is all that is needed.

**Comment by cmungall** [comment]
actually it's best under entries rather than a top-level product. Made a PR myself. Sorry for the delay!

**Comment by Clare72** [comment]
Thank you!
