### ISSUE TITLE
RARE Definition and parent term revisions

### ISSUE THREAD

**Issue by RLovering** [The-Sequence-Ontology/SO-Ontologies#458]
Hi
please can the parent and the definition for this term be revised:

SO:0001653 | retinoic_acid_responsive_element 
revise the definition so that the location of the RARE is less specific
NEW Definition: A transcription factor binding site of variable direct repeats of the sequence PuGGTCA spaced by five nucleotides (DR5) found in the **proximal promoter and enhancer regions** of retinoic acid-responsive genes, to which retinoic acid receptors bind.

REMOVE the parent 'promoter' because the RARE is not bound by basal transcription machinery. (see GitHub ticket  #457)

ADD new parent TF_binding_site because it is a binding site for RAR. 

I have asked experts to comment on whether additional other parents are required eg: CRM, or transcriptional_cis_regulatory_region. Can we assume it always acts in 'cis'. I think it is located in both enhancers and promoter flanking regions so the parent term transcriptional_cis_regulatory_region could probably be added.   

Thanks

Ruth

**Comment by davidwsant** [comment]
Hi Ruth,

As suggested, the RARE term has been moved and can now be found under TF_binding_site.
