### ISSUE TITLE
PSE_motif revise definition

### ISSUE THREAD

**Issue by RLovering** [The-Sequence-Ontology/SO-Ontologies#459]
Hi 

please can the parent and the definition for this term be revised:

SO:0000017 | PSE_motif | http://www.sequenceontology.org/browser/current_svn/term/SO:0000017 Please add the following last sentence to the definition so that the role of the PSE_motif is clarified
NEW Definition: A sequence element characteristic of the promoters of snRNA genes transcribed by RNA polymerase II or by RNA polymerase III. Located between -45 and -60 relative to the TSS. The human PSE_motif consensus sequence is TCACCNTNA(C\|G)TNAAAAG(T\|G). **The basal transcription factor, snRNA-activating protein complex (SNAPc), binds the PSE_motif and is required for the transcription of both RNA polymerase II and III transcribed small-nuclear RNA genes.** 

It might also be helpful to add these 2 references PMID:8339931, PMID:12621023

Thanks

Ruth

**Comment by davidwsant** [comment]
Hi Ruth,

This definition has been updated and the new PMIDs have been added.
