### ISSUE TITLE
defining regulatory regions, enhancers, silencers

### ISSUE THREAD

**Issue by RLovering** [The-Sequence-Ontology/SO-Ontologies#461]
Summary of email to 14 Feb 2019

Astrid:
>Did we get suggestions yet from the ‘gene regulatory region’-experts on which ontological terms and hierarchies (DAGs) we should create for the regulatory regions outside of the promoter?
>Would all of these other regulatory regions fall under the categories “enhancer” or “silencer”?
>Do we have good ontological terms for these?
>Will it be correct to state that promoter, enhancer, silencers are non-overlapping regulatory regions (in terms of DNA-sequence), or would they just be distinguished by their function? (I guess the latter is the case)
>Is it correct, that all reglatory motifs (or transcription factor binding sites), like “CRE”, “CCAAT_motif” etc, would be part of either promoter or enhancer or silencer (or other regulatory region to be also defined?)

Jacques:
>About enhancers and silencers, I think the concepts should be discussed: in metazoa, a same region can be enhancer in one tissue art a given development stage, and silencer elsewhere or at some other stage. 
>The definition of silencers / enhancers should be related to the methodology originally used to define them: via progressive deletions of the "promoter" (i.e. upstream region), and by comparing the level of expression each time a piece of regulatory region is deleted. 
>I join a few definitions I wrote in 2014 for the Concise Encyclopaedia of Bioinformatics, they can certainly be improved but they could already serve as a starter. 
> Dictionary of Bioinformatics Jacques van Helden was attached as a pdf to the emails, if anyone would like a copy of this please contact Jacques van Helden directly.

Val:
>I agree,  even in yeast the same motif can be an activator or a repressor in different contexts.
>We have captured repression /activation at the GO MF and BP  level on the gene product, and used the SO motif as a target of the  DNA binding term.

Astrid:
>so, enhancers - via the protein- (and ncRNA?)-binding motifs localized in such regions - can engage protein complexes with varying composition (and post translational modifications) and such complexes can promote or repress transcription at the target gene in question (depending on the nature of the complex which, in turn, is determined by biological context)
>>to my knowledge, these DNA regions' label as "enhancers" does not change depending on the outcome of the influence from complexes bound to them, on transcription; they do not change label to "silencer" even if they engage transcription repressing complexes,  - am I right?

> is it analogous with silencers?
>>Can they engage protein(/RNA?)-assemblages that can either promote or repress transcription?
>>Or do they only engage in transcription repression processes?

Ruth Note:
>Discussion on motif v site etc summarised here: https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/460
>Discussion on promoters https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/457

**Comment by RLovering** [comment]
Current definitions for these 2 terms:


SO:0000165 | enhancer | http://www.sequenceontology.org/browser/current_svn/term/SO:0000165 | A cis-acting sequence that increases the utilization of (some) eukaryotic promoters, and can function in either orientation and in any location (upstream or downstream) relative to the promoter.
-- | -- | -- | --

**Comment by davidwsant** [comment]
Hi @RLovering,

I believe this issue has been cleared up since August 2019, but I never closed the ticket. I am going to close this issue request, but feel free to re-open this request or create another one if anything is still out of place. 

Thanks,

Dave Sant
