### ISSUE TITLE
redefine or merge m26 into cre

### ISSUE THREAD

**Issue by Antonialock** [The-Sequence-Ontology/SO-Ontologies#464]
Hi,

I think you can merge
 M26_binding_site SO:0001900 
A promoter element that contains a core sequence TGACGT, bound by a protein complex that regulates transcription of genes encoding PKA pathway components.

into 
CRE SO:0001843
A promoter element with consensus sequence TGACGTCA; bound by the ATF/CREB family of transcription factors.

M26 is a recombination hotspot in pombe, and it just so happens that it is also part of the CRE TF binding site. Apologies for the confusion, but in this context (TF binding site) these term can be merged.

**Comment by Antonialock** [comment]
I'm moving our annotations where it is used as a transcriptional promoter to the CRE term

we are also using this term as an actual recombination site term, so could the term be redefined instead to reflect this usage?

**Comment by Antonialock** [comment]
Cre-recombination target region, M26 site

**Comment by Antonialock** [comment]
@mah11

**Comment by davidwsant** [comment]
Hi Antonia,
I am a new postdoc and I am helping to update the SO terms. In this case, are you suggesting that we move M26_binding_site to make it a child term of CRE? Or are you suggesting we depricate the term as it is part of CRE?

**Comment by Antonialock** [comment]
Hi David,
I suggest neither of those solutions :-) 

I would like you to merge M26_binding_site SO:0001900 with
CRE SO:0001843

CRE will be the primary name

For us this means that any annotations we have to M26 automatically will display as CRE

Thanks! Let me know if you need any other input

**Comment by davidwsant** [comment]
Hi Anotnia,

Thank you for the suggestions. The terms have been merged, as you suggested. 

Dave
