### ISSUE TITLE
Term request: selection_marker

### ISSUE THREAD

**Issue by bbartley** [The-Sequence-Ontology/SO-Ontologies#468]
Hi,

This is a duplicate of #402, but since it has been 2 years, I want to bump the issue to the top of the queue.

I and my research collaborators have been working on standardizing sequence representation of vectors in the Synthetic Biology Open Language, which leverages SO for annotation.  A major problem with vector maps in Genbank is that selection markers are inconsistently annotated, e.g., gene, CDS, misc_feature, etc.  They are also inconsistently named, e.g., bla, ampR, AmpR, etc.  Therefore I propose adding `selection_marker` as a term.

This would be a big help to us for standardizing representation of vectors and writing software that can reason automatically about the compatibility of plasmids with host strains and with other plasmids, which are common use cases in synthetic biology.

Thanks,
Bryan Bartley
Scientist
Raytheon BBN Technologies

**Comment by davidwsant** [comment]
Hi Bryan,

I apologize for the delay. The previous postdoc that was working on this project has found a new position and there was an interim where no one had been trained to update SO. I will discuss this with the group and let you know about updating it.

Thanks,

Dave

**Comment by davidwsant** [comment]
Hi Bryan,

I apologize that it has taken me this long to get back to looking at SO issues. 

I can see what you mean, where gene and CDS are sometimes used interchangeably but they in fact have different meanings. 

If you were to add the term `selection_marker`, what would you propose for the definition? What would you propose to be the parent term (is_a relationship)? Do you have any publications that you would recommend linking this term to?

Thanks,

Dave

**Comment by bbartley** [comment]
Hi @davidwsant 

Here is my attempt at a definition:

`selection_marker` is a genetic feature that may be used for purpose of artificial selection of a subpopulation in a cell culture through addition or withholding of reagents in the growth medium

This term could be a child of `genetic_marker`, although this term, and subtypes in this branch, sound as if they have previously been used mainly for human biomarker studies.  However the definition, "A measurable sequence feature that varies within a population", is consistent with `selection_marker`.

As for publications, the term has been in use for decades, so it is hard to find an authoritative origin for the term.  Here is a more recent one that illustrates how the term is used in laboratory applications:

Jang CW, Magnuson T. A novel selection marker for efficient DNA cloning and recombineering in E. coli. PloS one. 2013 Feb 20;8(2):e57075.

A synonym for this term is `selectable_marker`

Thanks!
Bryan

**Comment by bbartley** [comment]
Here is a revised, more general definition, because it occurred to me that selection markers are used in plant cultivation, too, not just cell cultures:
`selection_marker` is a genetic feature that encodes a trait used for artificial selection of a subpopulation

**Comment by davidwsant** [comment]
Hi Bryan,

Thanks for the quick response. Let me run these ideas by the group and then I will get back to you.

Thanks,

Dave

**Comment by davidwsant** [comment]
Hi Bryan,

The new term `selection_marker` has been added. It has received the ID SO:0002232. The [SO browser](http://www.sequenceontology.org/browser/obob.cgi) should be updated with this term by tomorrow morning. I apologize that it took so long to have this term updated due to the change in staff. Thank you for your patience. 

Best,

Dave
