### ISSUE TITLE
Spelling, grammar and definition issues.

### ISSUE THREAD

**Issue by LaurensWilming** [The-Sequence-Ontology/SO-Ontologies#469]
I noticed a few issues with terms we are using. Below is the suggested wording for the respective terms. Some changes are as subtle as inserting missing hyphens (e.g. in non-coding, etc.). 

missense_variant | SO:0001583
A sequence variant that changes one or more bases of a codon, resulting in a polypeptide with a different amino acid sequence but no change in length. 
  
stop_gained | SO:0001587
A sequence variant where at least one base of a codon is changed, resulting in the creation of a premature termination (stop) codon and a shortened polypeptide.

stop_lost | SO:0001578
A sequence variant where at least one base of a termination (stop) codon is changed, resulting in an amino acid coding codon and an elongated polypeptide. 

splice_acceptor_variant | SO:0001574
A splice variant that changes the 2 base pair region at the 3' end of an intron. 

splice_region_variant | SO:0001630
A sequence variant occurring in the region of the splice site, either within 1-3 bases of the exon or 3-8 bases of the intron.

frameshift_variant | SO:0001589
A sequence variant where the number of nucleotides inserted or deleted is not a multiple of three, causing a disruption of the translational reading frame.

5_prime_UTR_premature_start_codon_gain_variant | SO:0001988
A 5' UTR variant where a premature start codon is gained, resulting in an elongated polypeptide.

chromosome_number_variation | SO:1000182
A type of chromosome variation where the chromosome complement is not an exact multiple of the haploid number.

coding_transcript_intron_variant | SO:0001969
A sequence variant occurring in an intron of a coding transcript.

conserved_intergenic_variant | SO:0002017
A sequence variant located in a conserved intergenic region.

conserved_intron_variant | SO:0002018
A transcript variant occurring in a conserved region of an intron.

disruptive_inframe_deletion | SO:0001826
A sequence variant that deletes bases in multiples of three from the coding sequence starting and ending in existing codons, resulting in an in-frame decrease in CDS length and altered amino acid sequence at deletion start and/or end codon.

disruptive_inframe_insertion | SO:0001824
A sequence variant that inserts bases in multiples of three into the coding sequence in an existing codon, resulting in an in-frame increase in CDS length and altered amino acid sequence at insertion start and/or end codon.

exon_loss_variant | SO:0001572
A sequence variant where an exon is lost from the transcript.

feature_truncation | SO:0001906
A sequence variant that causes the reduction of a genomic feature, relative to the reference sequence.

inframe_deletion | SO:0001822
A sequence variant that deletes bases in multiples of three from the coding sequence.

inframe_insertion | SO:0001821
A sequence variant that inserts bases in multiples of three into in the coding sequence.

intergenic_variant | SO:0001628
A sequence variant located in the intergenic region. 

internal_feature_elongation | SO:0001908
A sequence variant that causes the extension of a genomic feature from within the feature rather than from the terminus of the feature, with relative to the reference sequence.
 
intragenic_variant | SO:0002011
A variant that occurs within a gene but falls outside of all transcript features. This occurs when alternative transcripts of a gene do not share overlapping sequence. 

intron_variant | SO:0001627
A transcript variant occurring in an intron. 

non_coding_transcript_exon_variant | SO:0001792
A sequence variant occurring in an exon of a non-coding transcript. 

non_coding_transcript_intron_variant | SO:0001970
A sequence variant occurring in an intron of a non-coding transcript. 

non_coding_transcript_variant | SO:0001619
A transcript variant of a non-coding RNA gene. 

rare_amino_acid_variant | SO:0002008
A sequence variant where at least one base of a codon encoding a rare amino acid is changed, resulting in a different encoded amino acid. 

regulatory_region_variant | SO:0001566
A sequence variant located in a regulatory region. 

sequence_variant | SO:0001060
A non-exact copy of a sequence feature or genome, exhibiting one or more sequence alterations. 

stop_retained_variant | SO:0001567
A sequence variant where at least one base in a termination (stop) codon is changed, but it remains a termination codon. 

transcript_ablation | SO:0001893
A feature ablation where the deleted region includes a transcript feature. 
 
transcript_variant | SO:0001576
A sequence variant that changes the structure of a transcript. 

complex_substitution | SO:1000005
When no simple or well-defined DNA mutation event describes the observed DNA change, the keyword "complex" should be used. Usually there are multiple equally plausible explanations for the change. 

Thanks,
Laurens (MGI at Jax)

**Comment by davidwsant** [comment]
Thank you for your post. I am a new postdoc and I am currently in training for updating the SO. I will update the terms and let you know when they are updated.

**Comment by LaurensWilming** [comment]
Hi David,

That’s great.
I’ve only looked at a tiny fraction of all the terms. You may want to do a more global search to find instances of for example “whereby” and replace them with more proper wording (“where”).

whereby > where
within > in
non coding > non-coding
terminator codon > termination codon
etc.

Iffy grammar is of course more difficult to search for… And inconsistencies such as “transcript variant” versus “sequence variant” when describing variants that affect transcripts.

Thanks,
Laurens
