### ISSUE TITLE
Term request: Inert DNA spacer

### ISSUE THREAD

**Issue by jakebeal** [The-Sequence-Ontology/SO-Ontologies#471]
Inert DNA Spacers, comprising inert DNA upstream and/or downstream of a promoter, have been used in multiple studies at this point, including:

1. [Davis et al, _NAR_, 2011](https://www.ncbi.nlm.nih.gov/pubmed/20843779)
2. [Casini et al, _ACS Syn Bio_, 2014](https://www.ncbi.nlm.nih.gov/pubmed/24933158)
3. [Nielsen et al, _Science_, 2016](https://www.ncbi.nlm.nih.gov/pubmed/27034378)
4. [Carr et al, _PLoS One_, 2017](https://www.ncbi.nlm.nih.gov/pubmed/28422998)
5. [Sexton & Tabor, _bioRxiv_, 2019](https://www.biorxiv.org/content/10.1101/584664v1)

The function of these sequences is to decrease regulatory interactions between a promoter, its 5' context, and/or the translational unit(s) it regulates.  Such spacers can thus affect activity in both transcription and translation.  I would thus suggest the term be placed directly under regulatory_region (SO:0005836)

This function is distinct from insulator (SO:0000627), which is currently defined to act specifically on transcriptional enhancement or chromatin encroachment.

**Comment by jakebeal** [comment]
Any response for this request?

**Comment by jakebeal** [comment]
Bump.  Can any maintainer either help fulfill this request or else explain what needs to be changed/clarified before you can do so?

**Comment by davidwsant** [comment]
Hi Jake,

This term has been added and should appear shortly on the SO website. The new term has been assigned an ID SO:0002223. I apologize for the delay.

Thanks,

Dave

**Comment by jakebeal** [comment]
Thank you @davidwsant !
