### ISSUE TITLE
NTR 5/18/28S_rRNA_gene

### ISSUE THREAD

**Issue by Antonialock** [The-Sequence-Ontology/SO-Ontologies#472]
Hi,

I would like to request the terms:

1. 5S_rRNA_gene
2. 18S_rRNA_gene
3. 28S_rRNA_gene
is_a rRNA_gene

in PMID:31294478 it is shown that pombe Sen1 locates to 5s rRNA genes, but not to other rRNA genes.

**Comment by srengel** [comment]
could the S please be capitalized to 5S_rRNA__gene?  The S refers to 'sedimentation coefficient' and these are always uppercase S instead of lowercase.

**Comment by Antonialock** [comment]
Yes of course, thanks

**Comment by Antonialock** [comment]
updated term request based on community curator input

**Comment by Antonialock** [comment]
Hi Stacia, do you need any more information for this? Cheers.

**Comment by srengel** [comment]
Hi @Antonialock i'm not the one who makes SO changes.  that would be @mikebada or @keilbeck or ...?

**Comment by davidwsant** [comment]
Hi @Antonialock,

I apologize that it has taken me so long to get back to looking at term requests. 

I see how these terms would be important. I have a little bit of a question about putting all three of these under [rRNA_gene(SO:0001637)](http://www.sequenceontology.org/browser/current_svn/term/SO:0001637). The other three terms each have something that seems like a parent term under [small_subunit_rRNA(SO:0000650)](http://www.sequenceontology.org/browser/current_svn/term/SO:0000650) or under [large_subunit_rRNA(SO:0000651)](http://www.sequenceontology.org/browser/current_svn/term/SO:0000651). 

[rRNA_5S(SO:0000652)](http://www.sequenceontology.org/browser/current_svn/term/SO:0000652)
[rRNA_18S(SO:0000407)](http://www.sequenceontology.org/browser/current_svn/term/SO:0000407)
[rRNA_28S(SO:0000653)](http://www.sequenceontology.org/browser/current_svn/term/SO:0000653)

I am thinking that I could perhaps put the three new terms under rRNA_gene and mark them as derived from the three terms that I have listed here. Does that sound reasonable? 

Also, could you please comment on my proposed definitions for these terms? I have taken them from the definitions of the terms they will be placed under as derived_from. I would prefer that you check them for accuracy before I add them. 

5S_rRNA_gene: A gene which codes for 5S_rRNA, which is a portion of the large subunit of the ribosome in both eukaryotes and prokaryotes.
18S_rRNA_gene: A gene which codes for 18S_rRNA, which functions as the small subunit of the ribosome in eukaryotes.
28S_rRNA_gene: A gene which codes for 28S_rRNA, which functions as a component of the large subunit of the ribosome in eukaryotes.

Thanks,

Dave

**Comment by Antonialock** [comment]
Hi Dave,
I'm not an expert on ribosomal components but the defs and additional parentage sound fine to me.

Many thanks.

**Comment by murphyte** [comment]
Hi Dave,

From the 2005 SO publication:
https://genomebiology.biomedcentral.com/articles/10.1186/gb-2005-6-5-r44
"If the commonly used name begins with a number, such as 28S RNA, the stem is moved to the front - for example, RNA_28S."

So the gene terms should be rRNA_28S_gene, similar to the rRNA terms, unless that's no longer a rule. I do see some other terms that start with numbers, so maybe that rule is defunct. 

Also, while you're at it, how about adding gene terms for the rest of the specific rRNA types:
rRNA_5_8S_gene
rRNA_21S_gene
rRNA_25S_gene
rRNA_23S_gene
rRNA_16S_gene

-Terence

**Comment by davidwsant** [comment]
Thank you, Terrence, for pointing out that I was not using the correct name convention. The new terms are all is_a: SO:0001637 ! rRNA_gene. Here are the terms that were added:

id: SO:0002236
name: rRNA_18S_gene
def: "A gene which codes for 18S_rRNA, which functions as the small subunit of the ribosome in eukaryotes." []
relationship: derives_from SO:0000407 ! rRNA_18S

id: SO:0002237
name: rRNA_16S_gene
def: "A gene which codes for 16S_rRNA, which functions as the small subunit of the ribosome in prokaryotes." []
relationship: derives_from SO:0001000 ! rRNA_16S

id: SO:0002238
name: rRNA_5S_gene
def: "A gene which codes for 5S_rRNA, which is a portion of the large subunit of the ribosome in both eukaryotes and prokaryotes." []
relationship: derives_from SO:0000652 ! rRNA_5S

id: SO:0002239
name: rRNA_28S_gene
def: "A gene which codes for 28S_rRNA, which functions as a component of the large subunit of the ribosome in eukaryotes." []
relationship: derives_from SO:0000653 ! rRNA_28S

id: SO:0002240
name: rRNA_5_8S_gene
def: "A gene which codes for 5_8S_rRNA (5.8S rRNA), which functions as a component of the large subunit of the ribosome in eukaryotes." []
relationship: derives_from SO:0000375 ! rRNA_5_8S

id: SO:0002241
name: rRNA_21S_gene
def: "A gene which codes for 21S_rRNA, which functions as a component of the large subunit of the ribosome in mitochondria." []
relationship: derives_from SO:0001171 ! rRNA_21S

id: SO:0002242
name: rRNA_25S_gene
def: "A gene which codes for 25S_rRNA, which functions as a component of the large subunit of the ribosome in some eukaryotes." []
relationship: derives_from SO:0001002 ! rRNA_25S

id: SO:0002243
name: rRNA_23S_gene
def: "A gene which codes for 23S_rRNA, which functions as a component of the large subunit of the ribosome in prokaryotes." []
relationship: derives_from SO:0001001 ! rRNA_23S

The changes have been pushed to GitHub. The [SO Browser](http://sequenceontology.org/browser/current_svn/) should be updated within about 24 hours. 

Thanks,

Dave
