### ISSUE TITLE
New TF binding site

### ISSUE THREAD

**Issue by ValWood** [The-Sequence-Ontology/SO-Ontologies#476]
Loz1 response elements
synonym LRE elelments

A conserved sequence   (5ʹ-CGNMGATCNTY-3') transcription repressor binding site  required for gene repression in the presence of  high zinc 

parent
core_eukaryotic_promoter_element (SO:0001660)
(I'm not sure if this will be the parent in the future, but it is where some of the other TF binding sites are?

**Comment by davidwsant** [comment]
Hi Ruth, do you think this might be a better child under TF_binding_site (SO:0000235) instead of core_eukaryotic_promoter_element?  

Thanks,

Dave

**Comment by davidwsant** [comment]
Hi @ValWood,

I apologize, I have been emailing another person named Ruth. Do you think this might be a better child under TF_binding_site (SO:0000235) instead of core_eukaryotic_promoter_element?

Thanks,

Dave

**Comment by ValWood** [comment]
Yes, I think TF_binding site works fine.

...in this case some of the existing binding sites we use might need to be migrated under this term if they are not there already:

https://www.pombase.org/browse-curation/dna-binding-sites

**Comment by davidwsant** [comment]
Hi Val, we found a term for zinc_repressed_element (SO:0002006). Would this new term be a synonym of this, or a child term to this?

**Comment by ValWood** [comment]
Probably a child. There are almost certainly others.

**Comment by davidwsant** [comment]
Hi Val,

A new child term "LOZ1_response_element" has been assigned ID SO:0002225. It has been pushed to the GitHub page and will be updated on the browser when the server refreshes later this week. 

Thanks,

Dave

**Comment by ValWood** [comment]
thanks!
