### ISSUE TITLE
CAAX box

### ISSUE THREAD

**Issue by ValWood** [The-Sequence-Ontology/SO-Ontologies#479]
child of

http://www.sequenceontology.org/browser/current_release/term/SO:0100017

A C-terminus protein motif (CAAX)  serving as a post-translational  prenylation site modified by the attachment of either a farnesyl or a geranyl-geranyl group to a cysteine residue.
Farnesyltransferase recognizes CaaX boxes where X = M, S, Q, A, or C, whereas Geranylgeranyltransferase I recognizes CaaX boxes with X = L or E

**Comment by davidwsant** [comment]
Hi Val,

I am sorry it took me so long to get back to looking at the issue requests. This term has now been added with the definition that you provided. 

Thanks,

Dave

**Comment by ValWood** [comment]
Thanks!

Val

**Comment by ValWood** [comment]
I don't see it yet. Could you pop the SO ID into this ticket?

Thanks

**Comment by davidwsant** [comment]
Hi Val,

Sorry, I forgot to put the info in the comment. The web browser updates once daily and was probably not updated when you responded. 

id: SO:0002230
name: CAAX_box
http://www.sequenceontology.org/browser/current_svn/term/SO:0002230

Sometimes the browser has trouble updating. If browsing does not work then the I will email the manager of the website. 

Thanks,

Dave
