### ISSUE TITLE
NTR: CDS extensions or elongations that translate to elongated polypeptides

### ISSUE THREAD

**Issue by ewallace** [The-Sequence-Ontology/SO-Ontologies#480]
**What is this request referring to?**
A coding extension of a CDS.
A 5' coding extension of a CDS. 
A 3' coding extension of a CDS

**What is the name you would like SO to give the term?**
CDS_extension
CDS_five_prime_extension
CDS_three_prime_extension

**What is the definition that you would like for this term?**
A sequence variant extending the CDS, that causes elongation of the resulting polypeptide sequence.
A sequence variant extending the CDS at the 5' end, that causes elongation of the resulting polypeptide sequence at the N terminus.
A sequence variant extending the CDS at the 3' end, that causes elongation of the resulting polypeptide sequence at the C terminus.

**Synonyms**
CDS_extension = elongated_CDS
CDS_five_prime_extension = elongated_CDS_five_prime
CDS_three_prime_extension = elongated_CDS_three_prime

**Parent Term**
Please put this under CDS (SO:0000316)
CDS_five_prime_extension *is_a* CDS_extension
CDS_three_prime_extension *is_a* CDS_extension

elongated_polypeptide_N_terminal (SO:0001611) should *derive_from* CDS_five_prime_extension
elongated_polypeptide_C_terminal (SO:0001610) should *derive_from* CDS_three_prime_extension

Furthermore, I request amending the definitions of SO:0001609, SO:0001610 and SO:0001611. Currently elongated_polypeptide (SO:0001609) is defined as:

> A sequence variant with in the CDS that causes elongation of the resulting polypeptide sequence.

However, an elongated polypeptide is in fact a translation product of a sequence variant of the CDS. Suggest replacing SO:0001609 definition with:

> An elongation of a polypeptide sequence deriving from a sequence variant extending the CDS.

Suggest updating  SO:0001610 and SO:0001611 analogously

**Relevant Publications**

Reviews:

How can the products of a single gene be localized to more than one intracellular compartment?
Christopher J. Danpure; Trends in Cell Biology, 1995, https://doi.org/10.1016/S0962-8924(00)89016-9

Single translation—dual destination: mechanisms of dual protein targeting in eukaryotes.Sharon Karniely and Ophry Pines; EMBO Reports, 2005, https://doi.org/10.1038/sj.embor.7400394

Beyond the Triplet Code: Context Cues Transform Translation. Gloria A.Brar; Cell 2016, https://doi.org/10.1016/j.cell.2016.09.022

Recent primary papers:
Non-canonical translation initiation in yeast generates a cryptic pool of mitochondrial proteins 
Geoffray Monteuuis, et al;  2019, https://doi.org/10.1093/nar/gkz301

Quantitative global studies reveal differential translational control by start codon context across the fungal kingdom 
Edward W J Wallace, et al; Nucleic Acids Research, 2020, https://doi.org/10.1093/nar/gkaa060

**Remarks**
I am requesting this following several decades of literature showing that translation from alternative start codons can give rise to elongated polypeptides, which have functional significance. These structures came up to a recent paper of mine and we prefer to use SO terms to keep track of them in our gff3 annotations.

This is my first request to SO, I have tried to be constructive, and I hope it is helpful.

**Comment by davidwsant** [comment]
Hi @ewallace,

Thank you for your suggestions. I apologize that it took so long for me to get to the issue requests. Your request was very detailed and contained all of the information needed. Your suggestions have now been incorporated into the SO.

Thank you,

Dave
