### ISSUE TITLE
New SO subset request for the Alliance of Genome Resources

### ISSUE THREAD

**Issue by gildossantos** [The-Sequence-Ontology/SO-Ontologies#481]
The Alliance of Genome Resources, an alliance of various model organism databases, has information for almost 300,000 genes from 7 species. To help our users search and browse this gene set, we have a "Biotype" facet that filters genes based on their primary gene classification. Right now, our facet has about 40 different biotypes, so it's a bit cumbersome.
https://www.alliancegenome.org/search?category=gene

We would like to propose a small "Alliance Gene Biotype" subset of terms (explicitly defined as such in the Sequence Ontology) that would represent the three most commonly annotated types of genes in our database: protein_coding_gene (SO:0001217), ncRNA_gene (SO:0001263) and pseudogene (SO:0000336). We would then use this subset to help organize our Biotype filter. For example, clicking on "ncRNA_gene" in the filter would bring up a sub-menu of child terms like "miRNA_gene" for additional filtering.

Does this seem reasonable? If so, how can we proceed?

Many thanks for your work on the Sequence Ontology!

Gil dos Santos
FlyBase Developer
Alliance Search Optimization Working Group Lead

**Comment by davidwsant** [comment]
Hi Gil,

I apologize for the delay.  It sounds like you have a great database set up and we at SO appreciate that you are using the SO. 

I think I understand what you are asking, and I think I know how to make the ontology files. The SO GitHub page has recently been reorganized so that there is now a ['subsets'](https://github.com/The-Sequence-Ontology/SO-Ontologies/tree/master/subsets) folder that contains the ontology files that contain only the terms from specific databases (currently DBVAR, SOFA, and biosapiens). I think that a simple solution might be to mark all of the terms of interest with a "subset" flag so that those files would be generated in the subsets folder. The terms of interest would not be viewable on the [Sequence Ontology browser](http://www.sequenceontology.org/browser/obob.cgi), but you would have access to the owl and obo files that could be viewed through another tool such as [Prot&eacute;g&eacute;](https://protege.stanford.edu/). Does this sound like the kind of solution that you are looking for? Please let me know and I will speak to the other members of the SO team and we can see how to proceed.

Best,

Dave Sant

**Comment by gildossantos** [comment]
Hi Dave,

Your proposal sounds perfect. Please discuss with your team and let us know where we can go from there.

Many thanks,
Gil

**Comment by davidwsant** [comment]
Hi Gil,

I will email them and see, but I think I can at least start making one. I have a couple of specific questions to help me get started. 

What is the name you would like to use for this (no spaces)? The other ones usually use an acronym (like DBVAR or SOFA), but your web site does not appear to have the acronym AGR written anywhere. I am thinking "Alliance_of_Genome_Resources". It is long, but if that is the common name for the project it is probably what we should use. 

What are the specific terms that you would like to include? You can list them in a reply comment or attach a file with the terms of interest. 

Alternatively, it is possible for you to update the subset terms yourself. If you would like, you are welcome to add the subset info to so.obo or so.owl yourself. Once you are happy with it, you can install OWLTools and run the Makefile in the repository to generate all of the other files (including the new subset files). I don't mind doing it, but you are welcome to try it yourself if you feel like it. 

Good luck,

Dave

**Comment by gildossantos** [comment]
Hi Dave,

That's correct, we don't use the "AGR" acronym. I think it would also be good to incorporate how this set represents a "slim" for our Gene biotypes. So I the most accurate would be this: "Alliance_of_Genome_Resources_Gene_Biotype_Slim"

These are the terms:
protein_coding_gene (SO:0001217)
ncRNA_gene (SO:0001263)
pseudogene (SO:0000336)

It's a small subset with a long name. Hopefully that makes sense.

Thanks,
Gil

**Comment by murphyte** [comment]
> That's correct, we don't use the "AGR" acronym.

Gil -- FYI, speaking from experience, while you may not have created the acronym yourself, it inevitably gets used. Search for:
"AGR" alliance genome resources

e.g.
http://www.informatics.jax.org/mgihome/other/collab_and_acknow.shtml

You may want to just embrace it!

**Comment by gildossantos** [comment]
I see your point @murphyte , and we might be swimming upstream on this, but our project has decided to stick with the full name as much as possible. I hope the proposed subset name works, and if not, then we'll reconsider.

**Comment by davidwsant** [comment]
Hi guys,

I have generated a version on my computer with the subset terms marked. I decided "Alliance of Genome Resources Gene Biotype Slim" was just too long, so I shortened it to "Alliance of Genome Resources" and gave it the following subset definition: 'subsetdef: Alliance_of_Genome_Resources "Alliance of Genome Resources Gene Biotype Slim"'. That way the definition gives you the full name (not AGR), but the file names will be significantly shorter. I have attached zipped versions of the obo and owl subset files. Let me know what you think of these and if you are happy with them then I will show them to my group.  

Best,

Dave

[Alliance_of_Genome_Resources.obo.zip](https://github.com/The-Sequence-Ontology/SO-Ontologies/files/4395425/Alliance_of_Genome_Resources.obo.zip)
[Alliance_of_Genome_Resources.owl.zip](https://github.com/The-Sequence-Ontology/SO-Ontologies/files/4395426/Alliance_of_Genome_Resources.owl.zip)

**Comment by davidwsant** [comment]
Hi Gil,

I sent the files to the members of the group and they have approved of adding the subset. I have pushed the changes to GitHub, so it will be easier for you to view the changes in all of the files. If you would like any more changes, feel free to re-open this issue.

Thanks,

Dave

**Comment by gildossantos** [comment]
Hi Dave,

The files look good.

Many thanks,
Gil
