### ISSUE TITLE
versionIRI no longer contains date

### ISSUE THREAD

**Issue by sbreiff** [The-Sequence-Ontology/SO-Ontologies#482]
Hello,

I noticed recently that the versionIRI was changed and no longer contains a specific release date, which makes it much harder for me to keep track of the version of the ontology in the owl file that I am using. In the meantime I suppose I could use the oboInOwl:date line instead, but would it be possible to move back to a versionIRI with a release date in the future?

Sarah

**Comment by davidwsant** [comment]
Hi Sarah,

Thank you for putting in the issue request. I apologize that this was taken out. Our pipeline had not been updating the date since 2015, so I thought including the date in the version line would not be important. This has been added back into the files.

Thanks,

Dave
