### ISSUE TITLE
NTR: homologous chromosome  recognition and pairing locus

### ISSUE THREAD

**Issue by ValWood** [The-Sequence-Ontology/SO-Ontologies#483]
Name: homologous chromosome  recognition and pairing locus

Definition 
A chromosomal locus where  complementary lncRNA and associated proteins accumulate at the corresponding lncRNA gene loci to tether homologous chromosome during chromosome pairing at meiosis I 

Parents:
chromosome_part
binding_site

References:
Meiosis-specific noncoding RNA mediates robust pairing of homologous chromosomes in meiosis.
Ding DQ, Okamasa K, Yamane M, Tsutsumi C, Haraguchi T, Yamamoto M, Hiraoka Y.
Science. 2012 May 11;336(6082):732-6. doi: 10.1126/science.1219518.
PMID: 22582262 

Chromosome-associated RNA-protein complexes promote pairing of homologous chromosomes during meiosis in Schizosaccharomyces pombe.
Ding DQ, Okamasa K, Katou Y, Oya E, Nakayama JI, Chikashige Y, Shirahige K, Haraguchi T, Hiraoka Y.
Nat Commun. 2019 Dec 6;10(1):5598. doi: 10.1038/s41467-019-13609-0.
PMID: 31811152

**Comment by davidwsant** [comment]
Hi Val,

Thank you for including such detail in your request. I wanted to double-check with you on the relationships with parents. I think this is appropriate:

is_a: SO: 0000409 ! binding_site
relationship: member_of SO: 0000830 ! chromosome_part

Does this sound correct to you? 

Thanks,

Dave

**Comment by ValWood** [comment]
Probably 
I 'm not familiar with member_of (is_a would also work, but maybe member_of is more precise?)

**Comment by davidwsant** [comment]
Hi Val,

I have added the new term homologous_chromosome_recognition_and_pairing_locus, SO:0002233. It will probably take about a day before the [sequence ontology browser](http://sequenceontology.org/browser/current_release/) refreshes with the files from GitHub and has the term. 

Thanks,

Dave

**Comment by ValWood** [comment]
@mah11 poited out the existing term

id: SO:0002025
name: cis_acting_homologous_chromosome_pairing_region
def: "A genome region where chromosome pairing occurs preferentially during homologous chromosome pairing during early meiotic prophase of Meiosis I." [PMID:22582262, PMID:23117617, PMID:24173580, PomBase:vw]
comment: Comment: An example of this is the Sme2 locus in fission yeast S. pombe, where is coincident with an ribonuclear complex termed the "Mei2 dot". This term was Requested by Val Wood, PomBase.
synonym: "cis-acting homologous chromosome pairing region" EXACT []
is_a: SO:0000713 ! DNA_motif

could this term merge into  SO: 0000409

**Comment by mah11** [comment]
Correction: it's SO:0002025 and SO:0002233 that should merge.
