### ISSUE TITLE
sncRNA term request

### ISSUE THREAD

**Issue by murphyte** [The-Sequence-Ontology/SO-Ontologies#485]
name: Small non-coding RNA
term: sncRNA
definition: A non-coding RNA <200 nucleotides in length
parent: ncRNA
children: miRNA, siRNA, piRNA, snoRNA, snRNA, tRNA
paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6046292/

The sncRNA term is older than that publication, but I didn't go looking for who first coined it.

In addition, the definition for lncRNA should be revised to be "greater than or equal to 200 nt in length"

**Comment by srengel** [comment]
searching in textpressocentral.org for 'sncRNA' finds this 2007 paper as earliest mention:

https://www.ncbi.nlm.nih.gov/pubmed/17949481

**Comment by davidwsant** [comment]
I think we have an equivalent term, [small_regulatory_ncRNA (SO:0000370)](http://sequenceontology.org/browser/current_svn/term/SO:0000370). I think that adding a synonym of sncRNA would be sufficient, as the definition lines up. The current definition is "A non-coding RNA less than 200 nucleotides long, usually with a specific secondary structure, that acts to regulate gene expression. These include short ncRNAs such as piRNA, miRNA and siRNAs (among others)". Does that sound sufficient?

**Comment by murphyte** [comment]
sncRNA would be a parent of small_regulatory_ncRNA. It includes those, but doesn't require regulatory function.

**Comment by davidwsant** [comment]
Hi Terrence,

I have updated the SO with the new information. The new term info is as follows: 

id: SO:0002247
name: sncRNA
def: "A non-coding RNA less than 200 nucleotides in length." 

The [SO Browser](http://sequenceontology.org/browser/current_svn/) should be updated with the changes within about 24 hours.

Thanks,

Dave Sant
