### ISSUE TITLE
SO:0001722 (H3K36_monomethylation_site) has "<" in related synonym name "H3K36<Me1"

### ISSUE THREAD

**Issue by chris-grove** [The-Sequence-Ontology/SO-Ontologies#486]
**What is the SO term name and accession?**
Name: H3K36_monomethylation_site
Accession: SO:0001722

**Describe what you would like to change.**
The related synonym is "H3K36<Me1" which appears to be a typo (shouldn't have the "<"); it should probably be "H3K36Me1" to be consistent with the related synonyms for sibling terms:

Accession: SO:0001723
Name: H3K36_dimethylation_site
Related synonym: H3K36Me2

and

Accession: SO:0001724
Name: H3K36_trimethylation_site
Related synonym: H3K36Me3

The added "<" is causing errors when trying to load the SO into our instance of Intermine (WormMine for WormBase).

Thanks!

**Comment by davidwsant** [comment]
Thank you for bringing this to our attention. This has now been fixed.
