### ISSUE TITLE
Terms for transposons are not complete

### ISSUE THREAD

**Issue by oushujun** [The-Sequence-Ontology/SO-Ontologies#487]
### Main issue
**What is this request referring to?**
Many transposons are not included in the SO system. Please add them for a better catalog. For SO naming and relationships please refer to the two citations below.

**Parent Term**
transposable_element SO:0000101

**Relevant Publications**
https://www.nature.com/articles/nrg2165
https://pubmed.ncbi.nlm.nih.gov/26709091/
Relevant discussions: https://github.com/oushujun/EDTA/issues/83

### Other non-transposon repeat terms:
**Parent Term**
repeat_region SO:0000657

**Request Terms**
knob: cytologically observable heterochromatic regions present on chromosomes
Simple_repeat: RepeatMasker defined simple repeat regions

**Comment by davidwsant** [comment]
Hi Shujun,

The term knob has been assigned the ID SO:0002257. The SO Browser is not updating automatically right now, but I have emailed someone to see if that can be fixed. This term is present in the ontology files in GitHub and should be added to the browser soon. 

If you would like new terms as children of transposable_element, please give specific details including specific names and definitions. Please follow the format of [this issue template](https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/master/.github/ISSUE_TEMPLATE/new-term-request.md). Please specify every name of a term along with every definition that you would like added in a single issue request.

As for simple_repeat, we do not typically add terms that refer to a program. If you would like to find a formal definition from RepeatMasker, you can add another issue request and we can look into adding that term. 

Thank you,

Dave Sant
