### ISSUE TITLE
circ_RNA to be added to non-coding class to align with INSDC

### ISSUE THREAD

**Issue by Jeena-Rajan** [The-Sequence-Ontology/SO-Ontologies#490]
**What is this request referring to?**
Addition of circular RNA under both ncRNA and mRNA. This was recently discussed at INSDC and will be added as a valid INSDC value.

**What is the name you would like SO to give the term?**
1. For the non-coding RNA please add circular_ncRNA.

2. For the mRNA please add circular_mRNA

**What is the definition that you would like for this term?**
1. A non-coding RNA that is generated by backsplicing of exons or introns, resulting in a covalently closed loop without a 5’ cap or 3’ polyA tail. 

2. An mRNA that is generated by backsplicing of exons or introns, resulting in a covalently closed loop without a 5’ cap or 3’ polyA tail. 

**Synonyms**
1. INSDC_feature:ncRNA, INSDC_qualifier:circRNA

2. INSDC_feature:mRNA, INSDC_qualifier:circular_RNA

**Parent Term**
1. Please put this under ncRNA-gene (SO:0001263) 

2. Please put this under mRNA (SO:0000234)

**Relevant Publications**
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5723916/

**Comment by murphyte** [comment]
There is an existing ticket #391.
I think this should be circRNA, without the underscore, if matching the INSDC usage. 

For its position in the hierarchy, I think it needs to be a child of both ncRNA and mRNA. Or we'll need two separate terms, for noncoding and coding circular RNAs. If going that route, the terms could be:

1. circular_ncRNA, with the synonyms INSDC_feature:ncRNA, INSDC_qualifier:circRNA
2. circular_mRNA, with the synonyms INSDC_feature:mRNA, INSDC_qualifier:circular_RNA

I'm basing those terms on others like "monocistronic_mRNA"

-Terence

**Comment by davidwsant** [comment]
Hi guys,

I apologize that I have not yet gotten to issue #391. I am trying to keep up with the current requests but work backwards on the old requests that were submitted before I joined the team.

I think you are right and these should be added to be consistent with other databases. 

I like Terence's idea of making two terms. Do you think there should be a third term made that is simply "circRNA" that is a parent to both of the proposed terms? I am thinking this one would go under "transcript" (SO:0000673) and have the definition "Circular RNA in a covalently closed loop without a 5’ cap or 3’ polyA tail." 

This would mean that circular_ncRNA is_a circRNA as well as is_a ncRNA-gene (SO:0001263). circular_mRNA would also have two parents, circRNA and mRNA (SO:0000234).

What do you guys think? Do you think it would be better with just the two terms, or is it most correct to add circRNA as well?

Thanks,

Dave

**Comment by murphyte** [comment]
That would certainly be formally correct, although maybe it should go under "mature_transcript" (SO:0000233). 

I don't really know what the pros and cons are, for this specifically and the general issue of adding complexity to the hierarchy. What comes to mind are:

1. If the extra term circular_RNA exists, is it likely to get used in a context where the user really should use the more specific term? If they do, it creates a problem of how to interpret the feature when you need the specificity. With a GenBank submission, circular_mRNA can be readily interpreted into INSDC terms, but circular_RNA can't without checking for presence/absence of a CDS. 
Or to put it another way, is there a point to having a node that you really don't want anybody to use?
2. Does having multiple parents for a node in the hierarchy make it harder to compute on? For example, say I want to extract out all "transcript" types from a file, and furthermore simplify those types to just a subset by moving up the hierarchy. That poses a problem if there are multiple paths. I don't know if anyone does this -- I can think of places where it would be desirable to do so, but trying to come up with a simple rule to collapse say a rich set of 50 types down to a more tractable set of 5 without having to define everything individually isn't obvious.

I'm somewhat biased towards simpler-is-better, so if there isn't an immediate use case for the extra node I'm inclined to omit.

**Comment by davidwsant** [comment]
Hi Terrence, 

It sounds like it will be both more consistent with INSDC and simpler if only the two terms are added. Below are my suggested changes to SO. Would you mind looking through these and giving and suggested changes before they are added? Especially look at the synonyms and make sure those are correct.

[Term]
id: New
name: circular_ncRNA
def: "A non-coding RNA that is   generated by backsplicing of exons or introns, resulting in a covalently closed loop without a 5’ cap or 3’ polyA tail." [PMID:29230098, PMID:   29626935, PMID: 29576969, PMID: 29086764, PMID: 29182528]
synonym: "circular ncRNA" EXACT   []
synonym: "noncoding circRNA"   EXACT []
synonym: "circRNA" BROAD []
synonym: "INSDC_feature:ncRNA"   EXACT []
synonym:   "INSDC_qualifier:circRNA" EXACT []
is_a: SO:0001263 ! ncRNA_gene
 
[Term]
id: New
name: circular_mRNA
def: "An mRNA that is generated by   backsplicing of exons or introns, resulting in a covalently closed loop without a 5’ cap or 3’ polyA tail." [PMID:29576969, PMID: 29086764, PMID: 29182528]
synonym: "circular mRNA" EXACT   []
synonym: "coding circRNA" EXACT   []
synonym: "INSDC_feature:mRNA"   EXACT []
synonym:   "INSDC_qualifier:circular_RNA" EXACT []
is_a: SO:0000234 ! mRNA

Thanks,

Dave Sant

**Comment by murphyte** [comment]
Hi Dave,

For circular_ncRNA, it should be:
is_a: SO:0000655 ! ncRNA

Everything else looks good to me. Thanks!

**Comment by davidwsant** [comment]
Hi guys,

Thanks for responding and helping me update these. circular_ncRNA has been assigned ID SO:0002291 and circular_mRNA has been assigned ID SO:0002292. As usual, the [SO Browser](http://sequenceontology.org/browser/current_svn/) should be updated with these terms within about 24 hours. 

Thanks,

Dave
