### ISSUE TITLE
RNA_polymerase_promoter (SO:0001203) is redundant of Promoter (SO:0000167)

### ISSUE THREAD

**Issue by davidwsant** [The-Sequence-Ontology/SO-Ontologies#492]
**What is the SO term name and accession?**
RNA_polymerase_promoter (SO:0001203) 
Promoter (SO:0000167)

**Describe what you would like to change.**
Colin Logie has brought it to my attention that "Promoter" infers that it is an RNA polymerase promoter. This is redundant. One possible solution would be to obsolete RNA polymerase promoter and move the children. Below I give the names, IDs, definitions and relationship info about the affected and related terms. This is an awful lot of info, so I have tried to put it into tables and include figures to make it as clear as possible.  

Current:
id: SO:0000167
name: promoter
def: "A regulatory_region composed of the TSS(s) and binding sites for TF_complexes of the basal transcription machinery." 
is_a: SO:0000727 ! CRM

id: SO:0001203
name: RNA_polymerase_promoter
def: "A region (DNA) to which RNA polymerase binds, to begin transcription." [xenbase:jb]
is_a: SO:0000167 ! promoter

is_a children of promoter (SO:0000167):
ID | Term | Definition
--- | --- | ---
SO:0001203 | RNA_polymerase_promoter | A region (DNA) to which RNA polymerase binds, to begin transcription.
SO:0002050 | constitutive_promoter | A promoter that allows for continual transcription of gene.
SO:0002051 | inducible_promoter | A promoter whereby activity is induced by the presence or absence of biotic or abiotic factors.
SO:0002222 | prokaryotic_promoter | A regulatory_region essential for the specific initiation of transcription at a defined location in a DNA molecule, although this location might not be one single base. It is recognized by a specific RNA   polymerase(RNAP)-holoenzyme, and this recognition is not necessarily autonomous.
SO:0002221 | eukaryotic_promoter | A regulatory_region including the Transcription Start Site (TSS) of a   gene and serving as a platform for Pre-Initiation Complex (PIC) assembly,   enabling transcription of a gene under certain conditions.
SO:0000568 | bidirectional_promoter | An unregulated promoter that allows continuous expression.
SO:0002310 | cryptic_promoter | The promoter of a cryptic gene.
id: SO:0002311 | viral_promoter | A regulatory_region including the Transcription Start Site (TSS) of a   gene found in genes of viruses.
id: SO:0002051 | inducible_promoter | A promoter whereby activity is induced by the presence or absence of biotic or abiotic factors.

part_of relationship children of promoter (SO:0000167):
ID | Term | Definition | Other Relationships
--- | --- | --- | ---
SO:0000017 | PSE_motif | A sequence element characteristic of the promoters of snRNA genes transcribed by RNA polymerase II or by RNA   polymerase III. Located between -45 and -60 relative to the TSS. The human   PSE_motif consensus sequence is TCACCNTNA(C\|G)TNAAAAG(T\|G). The basal transcription factor, snRNA-activating protein complex (SNAPc), binds the PSE_motif and is required for the transcription of both RNA polymerase II and III transcribed small-nuclear RNA genes. | is_a: SO:0000713 ! DNA_motif
SO:0001659 | promoter_element | An element that can exist within the promoter region of a gene. | relationship: overlaps SO:0000235 ! TF_binding_site; is_a: SO:0000713 ! DNA_motif

is_a children of RNA_polymerase_promoter (SO:0001203):
ID | Term | Definition
--- | --- | ---
SO:0000169 | RNApol_I_promoter | A DNA sequence in eukaryotic DNA to which RNA polymerase I binds, to begin transcription.
SO:0000170 | RNApol_II_promoter | A DNA sequence in eukaryotic DNA to which RNA polymerase II binds, to begin transcription.
SO:0000171 | RNApol_III_promoter | A DNA sequence in eukaryotic DNA to which RNA polymerase III binds, to begin transcription.
SO:0000613 | bacterial_RNApol_promoter | A DNA sequence to which bacterial RNA polymerase binds, to begin transcription.
SO:0001204 | Phage_RNA_Polymerase_Promoter | A region (DNA) to which Bacteriophage RNA polymerase binds, to begin transcription.

core_promoter_element (SO:0002309) is_a promoter_element (SO:0001659)

is_a children of core_promoter_element (SO:0002309):
ID | Term | Definition | Additional Relationships
--- | --- | --- | ---
SO:0001660 | core_eukaryotic_promoter_element | An element that only exists within the promoter region of a eukaryotic   gene. | relationship: part_of SO:0002221 ! eukaryotic_promoter
SO:0000315 | TSS | The first base where RNA polymerase begins to synthesize the RNA   transcript. | is_a: SO:0000835 ! primary_transcript_region
SO:0002312 | core_prokaryotic_promoter_element | An element that always exists within the promoter region of a prokaryotic gene. | relationship: part_of SO:0002222 ! prokaryotic_promoter
SO:0002313 | core_viral_promoter_element | An element that always exists within the promoter region of a viral gene. | relationship: part_of SO:0002311 ! viral_promoter

[Promoter_Children_Current.pdf](https://github.com/The-Sequence-Ontology/SO-Ontologies/files/5100260/Promoter_Children_Current.pdf)

** Proposed Changes **

[Promoter_Children_Proposed.pdf](https://github.com/The-Sequence-Ontology/SO-Ontologies/files/5100261/Promoter_Children_Proposed.pdf)

Merge RNA_polymerase_promoter (SO:0001203) with Promoter (SO:0000167)
id: SO:0000167
name: promoter
def: "A regulatory_region composed of the TSS(s) and binding sites for TF_complexes of the basal transcription machinery. A region (DNA) to which RNA polymerase binds, to begin transcription." * This combines both definitions *
is_a: SO:0000727 ! CRM

id: SO:0001203
name: RNA_polymerase_promoter
def: "A region (DNA) to which RNA polymerase binds, to begin transcription." [xenbase:jb]
is_a: SO:0000167 ! promoter
* is_obsolete: true *

Move the child terms of RNA_polymerase_promoter (SO:0001203)
[Term]
id: SO:0000169
name: RNApol_I_promoter
def: "A DNA sequence in eukaryotic DNA to which RNA polymerase I binds, to begin transcription." [SO:ke]
synonym: "pol I promoter" EXACT []
synonym: "polymerase I promoter" EXACT []
synonym: "RNA polymerase A promoter" EXACT []
synonym: "RNApol I promoter" EXACT []
is_a: SO:0002221 ! eukaryotic_promoter

[Term]
id: SO:0000170
name: RNApol_II_promoter
def: "A DNA sequence in eukaryotic DNA to which RNA polymerase II binds, to begin transcription." [SO:ke]
synonym: "pol II promoter" RELATED []
synonym: "polymerase II promoter" EXACT []
synonym: "RNA polymerase B promoter" EXACT []
synonym: "RNApol II promoter" EXACT []
is_a: SO:0002221 ! eukaryotic_promoter

[Term]
id: SO:0000171
name: RNApol_III_promoter
def: "A DNA sequence in eukaryotic DNA to which RNA polymerase III binds, to begin transcription." [SO:ke]
synonym: "pol III promoter" EXACT []
synonym: "polymerase III promoter" EXACT []
synonym: "RNA polymerase C promoter" EXACT []
synonym: "RNApol III promoter" EXACT []
is_a: SO:0002221 ! eukaryotic_promoter

[Term]
id: SO:0000613
name: bacterial_RNApol_promoter
def: "A DNA sequence to which bacterial RNA polymerase binds, to begin transcription." [SO:ke]
synonym: "bacterial RNApol promoter" EXACT []
is_a: SO:0002222 ! prokaryotic_promoter
is_a: SO:0001659 ! promoter_element * I think this relationship should be deleted. This is a promoter, not a promoter element *

[Term]
id: SO:0001204
name: Phage_RNA_Polymerase_Promoter
def: "A region (DNA) to which Bacteriophage RNA polymerase binds, to begin transcription." [xenbase:jb]
synonym: "Phage RNA Polymerase Promoter" EXACT []
is_a: SO:0002311 ! viral_promoter

Does this seem accurate to you guys? Are there any other definitions posted here that are not entirely correct?

Thanks,

Dave Sant

@colinlog
@rlovering
@keilbeck

**Comment by colinlog** [comment]
This seems accurate and entirely correct to me Dave.

**Comment by davidwsant** [comment]
Thank you for looking through this. The terms have been updated as discussed. 

Thanks,

Dave
