### ISSUE TITLE
Generalized Inert DNA spacer

### ISSUE THREAD

**Issue by jakebeal** [The-Sequence-Ontology/SO-Ontologies#494]
We have realized that the term SO:0002223, defined in response to #471, is a bit too specific in its definition.  The sense currently is _only_ regulatory interactions, while the usage in practice, including in the supported citing publications, covers all manner of unwanted interactions.

Could you adjust the definition from:

> Sequences that decrease regulatory interactions between a promoter, its 5' context and/or the translational unit(s) it regulated. Spacers can affect both translation and transcription.

to:

> Sequences that decrease unwanted interactions between biological regions, such as between a promoter, its 5' context and/or the translational unit(s) it regulates. Spacers can affect regulation of translation, transcription, and other biological processes.

**Comment by JS3xton** [comment]
I second this request.

**Comment by egchr** [comment]
Thank you for your patience. Commenting here to let @davidwsant know that I'm working on this one. Reading your request...

**Comment by egchr** [comment]
@jakebeal @JS3xton We are thinking we might go a step further and also remove the word "unwanted" from the definition making the new definition: 

> Sequences that decrease interactions between biological regions, such as between a promoter, its 5' context and/or the translational unit(s) it regulates. Spacers can affect regulation of translation, transcription, and other biological processes.

What do you think?

**Comment by jakebeal** [comment]
I'm OK with removing `unwanted`

**Comment by JS3xton** [comment]
Sounds good to me.

**Comment by egchr** [comment]
This is done. You should see the change reflected online within 24 hours. Thank you for your patience.
