### ISSUE TITLE
New sequence assembly terms which are specifically datums

### ISSUE THREAD

**Issue by ddooley** [The-Sequence-Ontology/SO-Ontologies#496]
Over on the OBI issues board https://github.com/obi-ontology/obi/issues/1232 there is a list of terms we are seeking a home for, namely:

amino acid sequence start site (user submitted)
amino acid sequence stop site (user submitted)
nucleic acid sequence start site (user submitted)
nucleic acid sequence stop site (user submitted)
amino acid sequence start site (reference)
amino acid sequence stop site (reference)
nucleic acid sequence start site (reference)
nucleic acid sequence stop site (reference)

But SO doesn't have IAO data item, etc.  So wondering if you want these kinds of relative positional sequence reference terms?

EDIT: we are working on fashioning better definitions that explicitly define "user submitted", "reference" etc.

**Comment by ddooley** [comment]
Anyone there?  I will keep these over in OBI if not.

**Comment by egchr** [comment]
Thank you @ddooley for your patience. Please forgive me for responding to your question with another question, but is there a particular part of the SO you think would house these terms nicely? I am looking at the overall structure of the SO and there might be a place for these somewhere under sequence_feature (SO:0000110), but we'll need to document these terms before we can proceed. We'll need to be able to cite specific publications if we are to include these in the SO (even for the most general terms), so I might ask for some citations? PubMed ID's are preferred, but we're happy to look at any publication you are willing to share.

**Comment by ddooley** [comment]
Hi, thanks for checking in.  We ended up popping them under "sequence data" in OBI.  So I'll close this now!
