### ISSUE TITLE
Change "lnc_RNA" (SO:0001877) to "lncRNA"?

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#503]
Hi,

Can "lnc_RNA" (SO:0001877) be changed to "lncRNA"?
Or is there a good reason/logic for having the underscore there?

"lncRNA" (without the underscore) is the much more common usage, and all other SO term names referring to lncRNAs use that format:
lncRNA_gene (SO:0002127)
lncRNA_primary_transcript (SO:0002035)
lncRNA_with_retained_intron (SO:0002113)
miR_encoding_lncRNA_primary_transcript (SO:0002036)
antisense_lncRNA_gene (SO:0002182)
bidirectional_promoter_lncRNA (SO:0002185)
antisense_lncRNA (SO:0001904)

Apart from a simple consistency argument, having this one lncRNA name with an underscore complicates various text-based searches of SO terms.

Thanks,
Steven.

**Comment by sjm41** [comment]
Also, sncRNA (SO:0002247) has no underscore....

**Comment by davidwsant** [comment]
Thank you for bringing this to our attention. This has now been updated to be consistent with the other terms and with the literature.

**Comment by sjm41** [comment]
Great, thanks!
