### ISSUE TITLE
Tweak 'bidirectional_promoter_lncRNA' term name

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#506]
bidirectional_promoter_lncRNA (SO:0002185)

This term name suggests it's referring to the RNA product.
However, this is a child of 'lncRNA_gene' and the definition states it refers to a 'A non-coding locus' rather than the ncRNA product itself.
Can you change the name to "bidirectional_promoter_lncRNA_gene"? (which would also match the pattern of the other children of 'lncRNA_gene')

Thanks.

**Comment by davidwsant** [comment]
Hi @sjm41 ,

I agree with your assessment, bidirectional_promoter_lncRNA_gene does make more sense. However, this is a Gencode term (https://www.gencodegenes.org/pages/biotypes.html). The notes on adding this term are in Issue #408. While I don't feel comfortable changing the name to differ from Gencode, I have added the synonyms bidirectional_promoter_lncRNA_gene and 'bidirectional promoter lncRNA gene'. If you would like to discuss further the possibility of changing the name, please comment and I will reopen the issue. 

Best,

Dave

**Comment by sjm41** [comment]
Hi Dave - thanks for checking on this.

It's weird that Gencode biotypes don't clearly distinguish between 'RNA' and 'RNA gene' for this and a couple more examples.  Personally, I think SO should dictate the names and logic rather than Gencode!

Also, I notice that https://www.gencodegenes.org/pages/biotypes.html also says this:
**lncRNA**
Generic long non-coding RNA biotype that replaced the following biotypes: 3prime_overlapping_ncRNA, antisense, **bidirectional_promoter_lncRNA**, lincRNA, macro_lncRNA, non_coding, processed_transcript, sense_intronic and sense_overlapping.

So, sounds like Gencode aren't using this term anyway!

**Comment by sjm41** [comment]
Hi @davidwsant / @egchr 

I'd like to re-open this ticket, but don't seem to be able to do that myself.

I was just chatting with Jonathan Mudge, Project Leader at GENCODE.
He confirmed that GENCODE are no longer using 'bidirectional_promoter_lncRNA' as a biotype in their database, and he has no issue with SO changing the name of SO:0002185 to 'bidirectional_promoter_lncRNA_gene'. Can you go ahead and make that change please?

(Then, we should also add a new corresponding term under the ncRNA branch, which _will_ be called 'bidirectional_promoter_lncRNA'! I will make a new ticket for that.)

**Comment by sjm41** [comment]
@egchristensen As per my previous comment, we need to re-open (and then act on!) this ticket.  Can you re-open please?

**Comment by egchristensen** [comment]
Made the change to the term name.
