### ISSUE TITLE
"2S ribosomal RNA gene" & "2S ribosomal RNA"

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#507]
**What is this request referring to?**
i) 2S ribosomal RNA gene
ii) 2S ribosomal RNA

**What is the name you would like SO to give the term?**
The name of the term SO can use. Note, if you include spaces they will be replaced with underscores. Example: rRNA_gene
i) rRNA_2S_gene
ii) rRNA_2S

**What is the definition that you would like for this term?**
i) A gene that encodes for 2S ribosomal RNA, which functions as a component of the large subunit of the ribosome in Drosophila and at least some other Diptera.
ii) A 30 nucleotide rRNA found in Drosophila and at least some other Diptera that is homologous to the 3' part of other 5.8S rRNA molecules. It forms a stable complex with the 5.8S and 26S rRNAs (PMID: 118436).

**Parent Term**
i) rRNA_gene (SO:0001637)
ii) large_subunit_rRNA (SO:0000651)

**Relevant Publications**
Jordan, B.R. (1974). '2S' RNA, a new ribosomal RNA component in cultured Drosophila cells.  FEBS Lett. 44(): 39--42. (PMID:4847940)

Jordan et al., 1976, J. Mol. Biol. 101: 85--105
Late steps in the maturation of Drosophila 26S ribosomal RNA: Generation of 5.8S and 2S RNAs by cleavages occurring in the cytoplasm. (PMID:768488)

Jordan and Glover, 1977, FEBS Lett. 78(2): 271--274
5.8S and 2S rDNA is located in the 'transcribed spacer' region between the 18S and 26S rRNA genes in Drosophila melanogaster.[FBrf0030092] (PMID:407103)

Pavlakis GN, Jordan BR, Wurst RM, Vournakis JN. (1979) Sequence and secondary structure of Drosophila melanogaster 5.8S and 2S rRNAs and of the processing site between them. Nucleic Acids Res. 7(8):2213-38. (PMID: 118436)

Pavlakis GN, Wurst RM, Vournakis JN. (1979) IDENTIFICATION OF DROSOPHILA 2S rRNA AS THE 3′-PART OF 5.8S rRNA (https://doi.org/10.1016/B978-0-12-604450-8.50084-5.)

Tautz D, Hancock JM, Webb DA, Tautz C, Dover GA. Complete sequences of the rRNA genes of Drosophila melanogaster. Mol Biol Evol. 1988 Jul;5(4):366-76. doi: 10.1093/oxfordjournals.molbev.a040500. (PMID: 3136294.)

Hori et al., 2000, FEBS Lett. 472(2-3): 187--190
The catalytic RNA of RNase P from Escherichia coli cleaves Drosophila 2S ribosomal RNA in vitro: a new type of naturally occurring substrate for the ribozyme. (PMID:10788608)

Fowler EK, Mohorianu I, Smith DT, Dalmay T, Chapman T. (2018) Small RNA populations revealed by blocking rRNA fragments in Drosophila melanogaster reproductive tissues. PLoS One. 13(2):e0191966. (PMID: 29474379)

**Comment by sjm41** [comment]
And here are links to the corresponding FlyBase gene reports:
2S ribosomal RNA:CR45864 (https://flybase.org/reports/FBgn0267524)
2S ribosomal RNA:CR45843 (https://flybase.org/reports/FBgn0267503)
2S ribosomal RNA:CR45840 (https://flybase.org/reports/FBgn0267500)
2S ribosomal RNA:CR45836 (https://flybase.org/reports/FBgn0267496)

**Comment by davidwsant** [comment]
Hi @sjm41, 

Thank you for bringing these to our attention. The following two terms have been added:

id: SO:0002336
name: rRNA_2S_gene
def: "A gene that encodes for 2S ribosomal RNA, which functions as a component of the large subunit of the ribosome in Drosophila and at least some other Diptera." [PMID: 118436, PMID: 29474379, PMID: 3136294, PMID:10788608, PMID:407103, PMID:4847940, PMID:768488]
synonym: "2S rRNA gene" EXACT []
synonym: "rRNA 2S gene" EXACT []
is_a: SO:0001637 ! rRNA_gene

id: SO:0002337
name: rRNA_2S
def: "A 30 nucleotide rRNA found in Drosophila and at least some other Diptera that is homologous to the 3' part of other 5.8S rRNA molecules. It forms a stable complex with the 5.8S and 26S rRNAs." [PMID: 118436, PMID: 29474379, PMID: 3136294, PMID:10788608, PMID:407103, PMID:4847940, PMID:768488]
synonym: "2S rRNA" EXACT []
synonym: "rRNA 2S" EXACT []
is_a: SO:0000651 ! large_subunit_rRNA

Best,

Dave

**Comment by sjm41** [comment]
Excellent, thanks!
