### ISSUE TITLE
scaRNA should be a subclass of snoRNA

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#509]
**SO term name and accession**
 scaRNA (SO:0002095)

**Parent term name and accession**
Currently is a child of ncRNA (SO:0000655)

**Suggested new parent term name and accession**
Should be moved to be child of snoRNA (SO_0000275)

**Reason for the change**
For example, see top of https://en.wikipedia.org/wiki/Small_Cajal_body-specific_RNA

*References*
https://pubmed.ncbi.nlm.nih.gov/28869095/
https://pubmed.ncbi.nlm.nih.gov/27775477/

**Comment by davidwsant** [comment]
Hi @sjm41,

Thank you for bringing this to our attention. This has been updated, and the publications you listed have now been linked to scaRNA.

Best,

Dave

**Comment by sjm41** [comment]
Thanks!
