### ISSUE TITLE
NTR: scaRNA_gene

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#510]
**What is this request referring to?**
Small Cajal body-specific RNA gene

**What is the name you would like SO to give the term?**
scaRNA_gene

**What is the definition that you would like for this term?**
A gene that encodes for a scaRNA (small Cajal body-specific RNA).

**Parent Term**
snoRNA_gene (SO_0001267) - also see #509

**Relevant Publications**
https://pubmed.ncbi.nlm.nih.gov/28869095/
https://pubmed.ncbi.nlm.nih.gov/27775477/

**Comment by davidwsant** [comment]
Hi @sjm41 ,

This term has been added and should be visible on the SO Browser within the next 24 hours. 

id: SO:0002339
name: scaRNA_gene
def: "A gene that encodes for a   scaRNA (small Cajal body-specific RNA)." [PMID:28869095, PMID:27775477]
synonym: "scaRNA gene" EXACT []
synonym: "Small Cajal body-specific   RNA gene" EXACT []
is_a: SO:0001267 ! snoRNA_gene

Best,

Dave

**Comment by sjm41** [comment]
Thanks!
