### ISSUE TITLE
Update snoRNA_gene def.

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#511]
**What is the SO term name and accession?**
snoRNA_gene (SO:0001267)

**Describe what you would like to change.**
Current def says "A small noncoding RNA that guides chemical modification of other RNAs."
Should change to something like "A gene encoding a small noncoding RNA that participates in the processing or chemical modifications of many RNAs, including ribosomal RNAs and spliceosomal RNAs." (in order to indicate this is for the gene (not the RNA product) and to better match the definition for snoRNA (SO_0000275).

**Comment by davidwsant** [comment]
Hi @sjm41 ,

Thanks for bringing this to our attention. The definition has been updated to reflect that this is a gene rather than the RNA product. 

best,

Dave

**Comment by sjm41** [comment]
Thanks!
