### ISSUE TITLE
Update rRNA_gene hierarchy to mirror rRNA hierarchy

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#513]
Current rRNA hierarchy looks like this:
```
rRNA
    |_large_subunit_rRNA
        |_rRNA_21S
        |_rRNA_23S
        |_rRNA_25S
        |_rRNA_28S
        |_rRNA_5S
        |_rRNA_5_8S
    |_mt_rRNA
    |_small_subunit_rRNA
        |_rRNA_16S
        |_rRNA_18S
```
(though see request for improvements in #493)

In contrast, the rRNA_gene hierarchy is flatter and lacks any mt_rRNA_gene specification:
```
rRNA_gene
    |_rRNA_16S_gene
    |_rRNA_18S_gene
    |_rRNA_21S_gene
    |_rRNA_23S_gene
    |_rRNA_25S_gene
    |_rRNA_28S_gene
    |_rRNA_5S_gene
    |_rRNA_5_8S_gene
```

Once the rRNA tree has been improved as per #493, can you make the rRNA_gene tree match it?

**Comment by egchr** [comment]
@sjm41 Is there anything left to do on this issue, or did @davidwsant take care of this with his last update?

**Comment by sjm41** [comment]
@egchr There's been no work at all on this ticket AFAIK.  Compare the the tree in my previous comment to that at http://sequenceontology.org/browser/current_svn/term/SO:0001637
Would be very happy if you could implement the new tree (so that the rRNA_gene and rRNA trees then match)!

**Comment by sjm41** [comment]
Hi @egchr Thanks for addressing my other ncRNA tickets!  Would be great if this one could also be addressed ahead of the RNAcentral meeting next week.

**Comment by egchr** [comment]
@sjm I believe I have taken care of the hierarchy as you intended, but could I ask you to double check? 

@keilbeck Just double checking that I’m ok to obsolete the term “rRNA_21S_gene” or do we need to discuss this more? The comments for that term currently read, “Added as per request by Antonia Lock GitHub issue #472 (https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/472) Removed relationship derives_from SO:0001171 on 10 June 2021 when SO:0001171 rRNA_21S was obsoleted into SO:0002345 mt_LSU_rRNA. See GitHub Issue #493.”

**Comment by sjm41** [comment]
Thanks @egchr !

SO:0002241 (rRNA_21S_gene) could be made a secondary ID of the new 'mt_LSU_rRNA_gene' term, to at least preserve the ID for searching etc. (I think that's what happened for the SO:0001171 rRNA_21S term.)

**Comment by sjm41** [comment]
@egchr New rRNA_gene hierarchy looks good, thanks.

I think these parents need adding though:
- mt_rRNA_gene: add 'mt_gene' (SO:0000088) as parent
- plastid_rRNA_gene: add plastid_gene (SO:0000090) as parent

**Comment by sjm41** [comment]
One other thing - all of the 'old' rRNA_gene terms have a 'derives from' relationship to the corresponding rRNA.
E.g.:
id: SO:0002236
name: cytosolic_rRNA_18S_gene
is_a: SO:0002362 (cytosolic_SSU_rRNA_gene)
relationship: derives_from SO:0000407 (cytosolic_18S_rRNA)

I think this must be a mistake - if anything, the relationship should be the other way round - the rRNA derives from the corresponding rRNA_gene.

Terms affected:
cytosolic_rRNA_23S_gene
cytosolic_rRNA_25S_gene
cytosolic_rRNA_28S_gene
cytosolic_rRNA_2S_gene
cytosolic_rRNA_5S_gene
cytosolic_rRNA_5_8S_gene
cytosolic_rRNA_16S_gene
cytosolic_rRNA_18S_gene

**Comment by sjm** [comment]
Just a heads-up; I've been getting some of the alerts which I think should be heading towards @sjm41 - looks like they picked up on the thread, anyway.

Just thought I'd let you know!

**Comment by sjm41** [comment]
Aha, thanks @sjm ! Yes, @egchr please use @sjm41 !

**Comment by egchr** [comment]
@sjm @sjm41 Sorry about that! My mistake.

**Comment by sjm** [comment]
No problem- easily done. I should clearly have chosen a longer username ;-)

**Comment by sjm41** [comment]
Hi @egchr Did you see my comments of 22nd Nov?

**Comment by egchristensen** [comment]
> @egchr New rRNA_gene hierarchy looks good, thanks.
> 
> I think these parents need adding though:
> 
>     * mt_rRNA_gene: add 'mt_gene' (SO:0000088) as parent
> 
>     * plastid_rRNA_gene: add plastid_gene (SO:0000090) as parent

Added these in commit 13f2da99bc2f28dda7d1e8006fd1a5b95d37872a.

**Comment by egchristensen** [comment]
> Thanks @egchr !
> 
> SO:0002241 (rRNA_21S_gene) could be made a secondary ID of the new 'mt_LSU_rRNA_gene' term, to at least preserve the ID for searching etc. (I think that's what happened for the SO:0001171 rRNA_21S term.)

@davidwsant am I ok to obsolete this term?

**Comment by egchristensen** [comment]
> One other thing - all of the 'old' rRNA_gene terms have a 'derives from' relationship to the corresponding rRNA. E.g.: id: SO:0002236 name: cytosolic_rRNA_18S_gene is_a: SO:0002362 (cytosolic_SSU_rRNA_gene) relationship: derives_from SO:0000407 (cytosolic_18S_rRNA)
> 
> I think this must be a mistake - if anything, the relationship should be the other way round - the rRNA derives from the corresponding rRNA_gene.
> 
> Terms affected: cytosolic_rRNA_23S_gene cytosolic_rRNA_25S_gene cytosolic_rRNA_28S_gene cytosolic_rRNA_2S_gene cytosolic_rRNA_5S_gene cytosolic_rRNA_5_8S_gene cytosolic_rRNA_16S_gene cytosolic_rRNA_18S_gene

@sjm41 Corrected the derives_from relationship for the cited terms in commit 60704ed7b0a107356c9daa8b58989bd86feead84.

**Comment by egchristensen** [comment]
OBSOLETED rRNA_21S_gene SO:0002241 and added as a synonym of mt_LSU_rRNA_gene SO:0002364 see GitHub Issue #513. See commit d9afc5372a07fb16815c20c0523fdeb0b385f714.
