### ISSUE TITLE
NTR: sisRNA

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#515]
**What is this request referring to?**
Stable intronic sequence RNA

**What is the name you would like SO to give the term?**
sisRNA

**What is the definition that you would like for this term?**
An intronic sequence derived from the coding strand of a cognate host gene, that is not rapidly degraded. It may contain exonic sequences, 5′ caps, and/or polyA tails. (PMID: 30391089)

**Synonyms**
Stable intronic sequence RNA

**Parent Term**
ncRNA (SO:0000655)

**Relevant Publications**
https://pubmed.ncbi.nlm.nih.gov/27147469/
https://pubmed.ncbi.nlm.nih.gov/29397203/
https://pubmed.ncbi.nlm.nih.gov/30391089/

**Comment by murphyte** [comment]
The proposed definition includes the phrase "coding strand", but the proposed parent is ncRNA. Would "sense strand" be better? 

I'm also wondering about the parent. Is ncRNA proposed as the parent on the assertion that most sisRNAs are likely to be non-coding? There might be exceptions, similar to circRNA, where SO is split into circular_mRNA and circular_ncRNA, although in the absence of an example perhaps separate terms are unnecessary. But to fully think through the relationships, is ncRNA proposed as an is_a relationship, and sisRNA would also be a derived_from relationship from primary_transcript?

**Comment by sjm41** [comment]
Hi terence

_The proposed definition includes the phrase "coding strand", but the proposed parent is ncRNA. Would "sense strand" be better?_
I just took that definition almost verbatim from the quoted paper... It does say "coding strand **of a cognate host gene**", so it's accurate in that context - using 'sense strand' is also fine by me.

_Is ncRNA proposed as the parent on the assertion that most sisRNAs are likely to be non-coding? There might be exceptions, similar to circRNA, where SO is split into circular_mRNA and circular_ncRNA, although in the absence of an example perhaps separate terms are unnecessary._
All the sisRNAs I've seen in the Drosophila literature are non-coding - derived from the introns of a coding host gene/transcript, and then shown/predicted to regulate expression of that gene.

_But to fully think through the relationships, is ncRNA proposed as an is_a relationship, and sisRNA would also be a derived_from relationship from primary_transcript?_
Those relationships both seem appropriate to me. (circular_ncRNA has an is_a relationship to ncRNA, right?)

**Comment by egchr** [comment]
@sjm41 I created `sisRNA (SO:0002352)` as a child of `ncRNA (SO:0000655)`. I went with the "coding strand" definition found in the literature you shared. Please reopen this issue if you and @murphyte would prefer "sense strand". You should see the changes reflected online sometime in the next 24 hours.

**Comment by sjm41** [comment]
Thanks Evan - that all sounds good to me (i.e. it fits the descriptions given in the literature to date, that I'm aware of).
Did you also add the  "derived_from primary_transcript" relationship?

**Comment by egchr** [comment]
The grandparent term `mature_transcript` derives from `primary_transcript`. Does that work, or are you envisioning something else?

**Comment by sjm41** [comment]
Ah, I see.

Looking again, I think the issue @murphyte was raising is that sisRNA is defined as "An intronic sequence...", whereas ncRNA is an is_a child of 'mature_transcript', which is defined as "A transcript which has undergone the necessary modifications, if any, for its function. In eukaryotes this includes, for example, processing of introns..."

So, as defined, 'sisRNA' can't really be a child of 'mature_transcript' -> 'ncRNA'.

Not sure how to solve this....any ideas?

**Comment by murphyte** [comment]
How about defining it as: "A non-coding transcript derived from typically intronic sequence from the sense strand of a cognate host gene, that is not rapidly degraded. It may contain exonic sequences, 5′ caps, and/or polyA tails. (PMID: 30391089)"

I added "typically" because of the 2nd sentence allowing that it could contain exonic sequence.
And by changing the beginning of the definition to say it is first-and-foremost a ncRNA, and the term "intronic" in the name has to do with where it's derived from and not the fact that it is itself still intronic, I think sidesteps the relationship issue. 

What do you think?

**Comment by egchr** [comment]
Alright, I updated the definition to "A non-coding RNA typically derived from intronic sequence of the sense strand of a cognate host gene, that is not rapidly degraded. It may contain exonic sequences, 5′ caps, and/or polyA tails."

Just double checking, do you think we still need to revisit the relationship with the parent term here?

**Comment by sjm41** [comment]
Thanks Evan. With the changed definition, I think the relationships are good.
