### ISSUE TITLE
Typo in siRNA definition.

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#517]
siRNA (SO:0000646) def:
A small RNA molecule that is the product of a longer exogenous or endogenous dsRNA, which is either a bimolecular duplex or very long hairpin, processed (via the Dicer pathway) such that numerous siRNAs accumulate from both strands of the dsRNA. SRNAs trigger the cleavage of their target molecules. [ http://www.ncbi.nlm.nih.gov/pubmed/12592000 ]

'SRNAS' in the last sentence is missing an 'i' and the 'S' should probably be lowercase, i.e. should be 'siRNAs'.

**Comment by sjm41** [comment]
Hi @egchr - this should be a quick and easy one to tick off the list!  Steven.

**Comment by egchr** [comment]
Thanks for your patience. This is done. We were waiting for a fix in owltools to be able to run the change.

**Comment by sjm41** [comment]
Thanks Evan.
