### ISSUE TITLE
scaRNA subtypes

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#519]
**What is this request referring to?**
New scaRNA subtypes to mirror what's already done for snoRNA subtypes.

**What is the name you would like SO to give the term?**
i) C_D_box_scaRNA
ii) H_ACA_box_scaRNA
iii) C-D_H_ACA_box_scaRNA

**What is the definition that you would like for this term?**
i) A scaRNA possessing a box C/D sequence motif, guiding the methylation of snRNAs.
ii) A scaRNA possessing a box H/ACA sequence motif, guiding the pseudouridylation of snRNAs.
iii) A scaRNA possessing both box C/D and box H/ACA sequence motifs, guiding both the methylation and pseudouridylation of snRNAs.

**Synonyms**
i) C/D scaRNA
ii) H/ACA scaRNA
iii) C/D-H/ACA scaRNA

**Parent Term**
scaRNA (SO:0002095)

**Relevant Publications**
https://pubmed.ncbi.nlm.nih.gov/17099227/
https://pubmed.ncbi.nlm.nih.gov/24659245/

Also see #509.

**Comment by sjm41** [comment]
Hi @egchr Thanks for addressing my other ncRNA tickets!  Would be great if this one could also be addressed ahead of the RNAcentral meeting next week.

**Comment by egchr** [comment]
I've added the children of scaRNA you requested and made corresponding _gene entries for each of them under scaRNA_gene. I also added the other children of snoRNA to snoRNA_gene.

**Comment by sjm41** [comment]
Thanks!
