### ISSUE TITLE
snoRNA_primary_transcript issues

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#520]
**What is the SO term name and accession?**
snoRNA_primary_transcript (SO:0000232)

**Describe what you would like to change.**
i) Typo in def. Currently says "A primary transcript encoding a small nucleolar mRNA (SO:0000275)" - 'mRNA' should just be 'RNA'.

ii) Some transcripts encode multiple snoRNAs (i.e. they are polycistronic units.), .e.g. [fly Uhg1](https://flybase.org/reports/FBgn0045800), [human SNHG1](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:32688)
These can't accurately be annotated with this term as it's currently defined.  Can we broaden the definition to "A primary transcript encoding one or more small nucleolar RNAs (SO:0000275)", or should we have a different term to annotate these?  (Maybe they are just 'lncRNA'?)

**Relevant Publications**
https://pubmed.ncbi.nlm.nih.gov/11302516/
https://pubmed.ncbi.nlm.nih.gov/8559254/

**Comment by egchr** [comment]
Steve, thank you for bringing this to our attention. We agree with your new definition and think that no new term needs to be created. I've committed the change and will close this issue. The [SO browser](http://www.sequenceontology.org/browser/current_release/term/SO:0002247) should update within the next 24 hours.

**Comment by sjm41** [comment]
Great, thanks Evan.
