### ISSUE TITLE
name for translational_frameshift

### ISSUE THREAD

**Issue by murphyte** [The-Sequence-Ontology/SO-Ontologies#522]
There's an inconsistency between INSDC and SO for ribosomal_slippage vs translational_frameshift:
http://www.sequenceontology.org/browser/current_release/term/SO:0001210
http://www.insdc.org/files/feature_table.html

The INSDC /ribosomal_slippage qualifier was formally introduced in October 2005 according to the GenBank release notes, and was already in some use as early as April 2003 (U00735.2). It is currently used on >600k sequence records in GenBank.

Renaming SO:0001210 as ribosomal_slippage for consistency in primary terms with INSDC would be ideal. Alternatively, please add ribosomal_slippage as a synonym on SO:0001210

Thanks!
-Terence

**Comment by davidwsant** [comment]
Hi Terrence,

I apologize for the delay, we have had another change in staff and are currently training a couple of people. 

Thanks for bringing this to our attention. I think that the SO term 'translational_frameshift' has been used several times in publications and I fear changing the name, but I think we should definitely at least show that they are synonyms as you suggested. I think we should also add the link to the feature table. 

How does this look?

[Term]
id: SO:0001210
name: translational_frameshift
def: "The region of mRNA (not divisible by 3 bases) that is skipped during the process of translational frameshifting (GO:0006452), causing the reading frame to be different." [SO:ke, http://www.insdc.org/files/feature_table.html]
comment: Added synonym 'ribosomal_slippage' on Feb 1, 2021, a term in INSDC and GenBank. See GitHub Issue #522.
synonym: "ribosomal frameshift" EXACT []
synonym: "translational frameshift" EXACT []
synonym: "INSDC_feature:ribosomal_slippage" EXACT []
synonym: "ribosomal slippage" EXACT []
xref: http://en.wikipedia.org/wiki/Translational_frameshift "wiki"
is_a: SO:0000836 ! mRNA_region

Thanks,

Dave

**Comment by murphyte** [comment]
> synonym: "INSDC_feature:ribosomal_slippage" EXACT []

make that INSDC_qualifier:ribosomal_slippage

The definition, and child features, is also restricted to positive slippage. There are also cases of negative slippage, in which a base is used as part of two codons. Should the definition be expanded to include that, and also add child features for "minus_1_translational_frameshift" and "minus_2_translational_frameshift"? I think there are annotated cases of -2 slippage, but I'm not positive.

**Comment by davidwsant** [comment]
I think you have a point. How about this?

For the INSDC term, does the single term cover both positive and negative slippage? If so, how would you change the definition? Perhaps "The region of mRNA (not divisible by 3 bases) that is skipped or added to a single frame during the process of translational frameshifting (GO:0006452), causing the reading frame to be different." 

As for the terms "minus_1_translational_frameshift" and "minus_2_translational_frameshift", would there also be terms "plus_1_translational_frameshift" and "plus_2_translational_frameshift"?

**Comment by murphyte** [comment]
> For the INSDC term, does the single term cover both positive and negative slippage?

yes, it's both.

> that is skipped or added to

that change seems reasonable.

> would there also be terms "plus_1_translational_frameshift" and "plus_2_translational_frameshift"?

those "plus" child terms already exist.

**Comment by davidwsant** [comment]
Hi Terrence,

How do these term names/definitions sound for the two additional terms?

name: minus_1_translational_frameshift
def: "The region of mRNA 1 base long   that is added during the process of translational frameshifting (GO:0006452),   causing the reading frame to be different." [SO:ds]
synonym: "minus 1 translational   frameshift" EXACT []
synonym: "minus 1 ribosomal   frameshift" EXACT []
synonym: "minus 1 ribosomal   slippage" EXACT []
is_a: SO:0001210 !   translational_frameshift
 
 
name: minus_2_translational_frameshift
def: "The region of mRNA 2 bases   long that is added during the process of translational frameshifting   (GO:0006452), causing the reading frame to be different." [SO:ds]
synonym: "minus 2 translational   frameshift" EXACT []
synonym: "minus 2 ribosomal   frameshift" EXACT []
synonym: "minus 2 ribosomal   slippage" EXACT []
is_a: SO:0001210 !   translational_frameshift

**Comment by murphyte** [comment]
How about "# bases long that is _included as part of two codons_ during the ..."

Does that make sense to you, or is it too jargon-y?
"added" seems like it could be interpreted as the mRNA gets modified, which isn't the case.

**Comment by davidwsant** [comment]
I didn't like my version, and I think your change fixes it. Does this wording look good?

The region of mRNA 2 bases long that is included as part of two separate codons during the process of translational frameshifting (GO:0006452), causing the reading frame to be different.

**Comment by murphyte** [comment]
great!
Writing science definitions is always such a challenge!

**Comment by davidwsant** [comment]
Thanks, Terrence. 

I have updated the definition of 1210, added the synonym "INSDC_qualifier:ribosomal_slippage" and added the two child terms minus_1_translational_frameshift (SO:0002329) and minus_2_translational_frameshift (SO:0002330). These terms should appear on the [SO browser](http://www.sequenceontology.org/browser/obob.cgi) within the next 24 hours.

Thanks,

Dave
