### ISSUE TITLE
enzymatic RNA revisions

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#533]
**Reason for the change**
As far as I can tell (from the current SO definitions and some reading on the subject), the following changes are appropriate:
1. "enzymatic_RNA" should be a child of "ncRNA"
2. "RNase_MRP_RNA" should be a child of "enzymatic_RNA"
3. "RNase_P_RNA" should be a child of "enzymatic_RNA"
4. "RNase_MRP_RNA_gene" should be a child of "enzymatic_RNA_gene"
5. "RNase_P_RNA_gene" should be a child of "enzymatic_RNA_gene"

Doing point 1 will bring the transcript terms into line with the gene-level terms, where 'enzymatic_RNA_gene' is already a child of 'ncRNA_gene'.

Details of the suggested changes are below.

Tagging @AntonPetrov

==

**SO term name and accession**
enzymatic_RNA (SO:0000372)
Def: An RNA sequence that has catalytic activity with or without an associated ribonucleoprotein.

**Current parent term name and accession**
transcript (SO:0000673)

**Suggested new parent term name and accession**
ncRNA (SO:0000655)

==

**SO term name and accession**
RNase_MRP_RNA  (SO:0000385)
def: The RNA molecule essential for the catalytic activity of RNase MRP, an enzymatically active ribonucleoprotein with two distinct roles in eukaryotes. In mitochondria it plays a direct role in the initiation of mitochondrial DNA replication. In the nucleus it is involved in precursor rRNA processing, where it cleaves the internal transcribed spacer 1 between 18S and 5.8S rRNAs.

**Current parent term name and accession**
ncRNA (SO:0000655)

**Suggested new parent term name and accession**
enzymatic_RNA (SO:0000372)
Def: An RNA sequence that has catalytic activity with or without an associated ribonucleoprotein.

==

**SO term name and accession**
RNase_P_RNA (SO:0000386)
Def The RNA component of Ribonuclease P (RNase P), a ubiquitous endoribonuclease, found in archaea, bacteria and eukarya as well as chloroplasts and mitochondria. Its best characterized activity is the generation of mature 5 prime ends of tRNAs by cleaving the 5 prime leader elements of precursor-tRNAs. Cellular RNase Ps are ribonucleoproteins....

**Current parent term name and accession**
ncRNA (SO:0000655)

**Suggested new parent term name and accession**
enzymatic_RNA (SO:0000372)
Def: An RNA sequence that has catalytic activity with or without an associated ribonucleoprotein.

==

**SO term name and accession**
RNase_MRP_RNA_gene (SO:0001640)
def:  A gene that encodes a RNase_MRP_RNA.

**Current parent term name and accession**
ncRNA_gene (SO:0001263)
def: A gene that encodes a non-coding RNA.

**Suggested new parent term name and accession**
enzymatic_RNA_gene (SO:0002180)
def: A gene that encodes an enzymatic RNA.

==

**SO term name and accession**
RNase_P_RNA_gene (SO:0001639)
def:  A gene that encodes an RNase P RNA.

**Current parent term name and accession**
ncRNA_gene (SO:0001263)
def: A gene that encodes a non-coding RNA.

**Suggested new parent term name and accession**
enzymatic_RNA_gene (SO:0002180)
def: A gene that encodes an enzymatic RNA.

**Comment by sjm41** [comment]
Hi @egchr Thanks for addressing my other ncRNA tickets!  Would be great if this one could also be addressed ahead of the RNAcentral meeting next week.

**Comment by egchr** [comment]
This is done.

**Comment by sjm41** [comment]
Great, thanks!
