### ISSUE TITLE
NTR: three stop codon terms

### ISSUE THREAD

**Issue by turbomam** [The-Sequence-Ontology/SO-Ontologies#537]
**What is this request referring to?**
Please add the well characterized stop codons: https://en.wikipedia.org/wiki/Stop_codon
- Amber
- ochre
- opal

**What is the name you would like SO to give the term?**
- "Amber stop codon"
- "Ochre stop codon"
- "Opal stop codon"

**What is the definition that you would like for this term?**
- "A stop codon with the DNA sequence TAG"
- "A stop codon with the DNA sequence TAA"
- "A stop codon with the DNA sequence TGA"

**Synonyms**
"Umber stop codon" is a synonym for "ochre stop codon"

**Parent Term**
"Stop_codon", SO:0000319

**Relevant Publications**
N/A

**Comment by keilbeck** [comment]
Wow, I'm shocked that these are not already there. We will add them.

**Comment by davidwsant** [comment]
Thank you for bringing this to our attention. These terms have now been added to the Sequence Ontology and have received the following IDs: 
amber_stop_codon - SO:0002333
ochre_stop_codon - SO:0002334
opal_stop_codon - SO:0002335
The [MISO Browser](http://www.sequenceontology.org/browser/obob.cgi) should be updated and show these terms as children of stop_codon (SO:0000319) within the next 24 hours.
