### ISSUE TITLE
Current release of the MISO Browser

### ISSUE THREAD

**Issue by roselucia** [The-Sequence-Ontology/SO-Ontologies#538]
Hi,

may I ask what is the release number of the release displayed when selecting "current release" in the browser? Is this release 3.1? Thanks

**Comment by davidwsant** [comment]
Hi @roselucia ,

Yes, the current release is release 3.1. The MISO Browser pulls changes to the ontologies on a daily basis to keep the version updates with any new changes, but no new releases have been made since release 3.1.

Please reopen this issue if you have further questions.

Best,

Dave

**Comment by roselucia** [comment]
Hi Dave, thanks a lot. So if I looked something up yesterday on the browser (current release), the information was matching the release 3.1?
Thanks

**Comment by roselucia** [comment]
Hi @davidwsant, thanks a lot. So if I looked something up the day before yesterday (21.04.2021) on the browser (current release), the information was matching the release 3.1? And there are no changes made to the data available through the brother in between two releases? The only changes made is when there is a new release?
Thanks,
Rose

**Comment by davidwsant** [comment]
Hi @roselucia ,

The browser is updated every 24 hours, so when you accessed the browser the other day it had many updates from the time of the initial 3.1 release. We simply have not made a new release since then. 

Dave

**Comment by roselucia** [comment]
Hi @davidwsant,
thanks for getting back to me. In order to specify the exact data used, I would need to give an access date then? So far I just always specified the release number, when using your browser. 
Thanks

**Comment by davidwsant** [comment]
An exact access date would work. However, if you want someone to be able to manipulate the data from your access date, I would probably recommend using the commit ID. The one that you would have seen on the browser on 21 April would be 7777cdf8b24c8bd28efb3b15741fcf8ff051917a, or 7777cdf for short. This commit was pushed on 16 Feb 2021. For someone to be able to manipulate the files in the state, you can clone the repository then use the git checkout command: `git checkout 7777cdf`
I would recommend using a program [Prot&eacute;g&eacute;](https://protege.stanford.edu/) to view the ontology. 

Does this make enough sense? 

Dave

**Comment by roselucia** [comment]
Hi Dave,
thanks a lot for the detailed information. That makes a lot of sense. I will specify the commit ID matching the version used that day in your browser (7777cdf8b24c8bd28efb3b15741fcf8ff051917a). 
Thanks,
Rose

**Comment by davidwsant** [comment]
Hi Rose,
I am glad to help. I am going to close the comment. If you have further questions you can respond to this same issue. Even if it is closed, I should receive a notification about any new posts.

Best,

Dave
