### ISSUE TITLE
The Sequence Ontology - By whom maintainted

### ISSUE THREAD

**Issue by roselucia** [The-Sequence-Ontology/SO-Ontologies#539]
Hi,

may I ask by which institute(s) or organisation(s) ist the The Sequence Ontology maintained and where they are located?

Thanks a lot.
All the best,
Rose

**Comment by davidwsant** [comment]
Hi Rose,

The Sequence Ontology was originally formed by the Gene Ontology Consortium and is maintained by the Dr. Karen Eilbeck lab at the University of Utah in Salt Lake City, Utah, United States. The majority of changes to the ontology are committed by members of the lab, though most are brought to our attention by users via issues in GitHub. More information about the SO can be found on the [SO website](http://www.sequenceontology.org/).

**Comment by roselucia** [comment]
Hi @davidwsant,

thanks a lot for getting back to me. This information was very helpful.
May I ask you to have another look at the closed issue https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/538#issuecomment-824689918. I am not able to reopen it and didnt want to open a new issue.
Thanks

**Comment by davidwsant** [comment]
Hi Rose,

The issue has been reopened. 

Best,

Dave
