### ISSUE TITLE
Def and parent relationship of 'miRNA'

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#545]
**What is the SO term name and accession?**
SO:0000276 miRNA
http://sequenceontology.org/browser/current_release/term/SO:0000276

**Describe what you would like to change.**
1. 'miRNA' currently has a 'part_of' relationship to 'pre_miRNA (SO:0001244)'.  I think this relationship would be more accurately described as 'derives_from'.

2. Also, the current definition says "Micro RNAs are produced from precursor molecules (SO:0000647) that can form local hairpin structures".  That SO term is for "miRNA_primary_transcript" and should be changed to pre_miRNA (SO:0001244).

[Term]
id: SO:0000276
name: miRNA
def: "Small, ~22-nt, RNA molecule that is the endogenous transcript of a miRNA gene (or the product of other non coding RNA genes. Micro RNAs are produced from precursor molecules (SO:0000647) that can form local hairpin structures, which ordinarily are processed (usually via the Dicer pathway) such that a single miRNA molecule accumulates from one arm of a hairpin precursor molecule. Micro RNAs may trigger the cleavage of their target molecules or act as translational repressors." [PMID:11081512, PMID:12592000]
subset: SOFA
is_a: SO:0000370
relationship: part_of SO:0001244

@AntonPetrov

**Comment by egchr** [comment]
I've made both of these changes. You should see them reflected online sometime within the next 24 hours.
