### ISSUE TITLE
Sequencing Instrument Models

### ISSUE THREAD

**Issue by cmrn-rhi** [The-Sequence-Ontology/SO-Ontologies#549]
Will SO be adding `sequencing instrument model` terms?

GENEPIO is in need of additional sequencing instrument model terms, but is interested to know whether SO is intending on housing any before we risk creating redundancies.

**Comment by egchr** [comment]
I do not believe we will be adding sequencing instrument model terms any time soon. Just to be sure, though, do you have examples of the types of terms you'd include as part of that model?

**Comment by mikebada** [comment]
OBI (Ontology for Biomedical Investigations), a relatively prominent OBO, already has a DNA sequencer class as well as a number of subclasses that appear to be sequencer models (e.g., 454 Genome Sequencer FLX), and I'd bet they'd add any that you need that aren't there, so I suggest looking into that for the sequencer terms you need.

**Comment by cmrn-rhi** [comment]
GENEPIO currently has the OBI branch "DNA sequencer" ([OBI:0400103](http://purl.obolibrary.org/obo/OBI_0400103)) and it's own parallel branch that could be merged into it called "sequencing instrument model" ([GENEPIO:0001921](http://purl.obolibrary.org/obo/GENEPIO_0001921)). We were looking into merging them under OBI, but it was conveyed to me that there had been discussion between OBI and SO that SO might be taking this OBI branch. We wanted to check in with both ontologies on the matter before making sequencer model term requests (e.g., 454 Genome Sequencer FLX) that we require for one of our projects.

**Comment by cmrn-rhi** [comment]
Just had confirmation from my liaison that I should be speaking with SWO rather than SO.
Our mistake.
Thank you for your time!
