### ISSUE TITLE
NTR: Y_RNA_gene

### ISSUE THREAD

**Issue by cthoyt** [The-Sequence-Ontology/SO-Ontologies#550]
**What is this request referring to?**

[SO:0000405 (Y_RNA)](https://www.ebi.ac.uk/ols/ontologies/so/terms?obo_id=SO:0000405) falls under the following transript hierarchy:

<img width="384" alt="Screen Shot 2021-09-16 at 23 21 03" src="https://user-images.githubusercontent.com/5069736/133687325-30ff6ac4-fa82-4fb2-8e12-1fdcb9af0506.png">

The HGNC lists 4 genes as RNA, Y.  However, HGNC refers to genes and not the transcripts they make. Therefore, it would be nice to mint a new term `Y_RNA_gene` the same way that other RNA transcripts have a similarly named `_gene` entry (e.g., [SO:0000655 (ncRNA)](https://bioregistry.io/SO:0000655) has the corresponding gene [SO:0001263 (ncRNA_gene)](https://bioregistry.io/SO:0001263))

**What is the name you would like SO to give the term?**

`Y_RNA_gene`

**What is the definition that you would like for this term?**

A gene that encodes a Y RNA.

**Synonyms**

N/A

**Parent Term**

Please put this under ncRNA-gene (SO:0001263) 

(funny note - the example was exactly what I needed!)

**Relevant Publications**

Here are the four genes from HGNC that are annotated this way, and the publications each uses as references:

## RNA, Y (4)
|   hgnc_id | name   | obsolete   | link                                                               | provenance                                                                               |
|-----------|--------|------------|--------------------------------------------------------------------|------------------------------------------------------------------------------------------|
|     10242 | RNY1   | False      | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/10242 | https://www.ncbi.nlm.nih.gov/pubmed/6187471                                              |
|     10243 | RNY3   | False      | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/10243 | https://www.ncbi.nlm.nih.gov/pubmed/6187471, https://www.ncbi.nlm.nih.gov/pubmed/7539809 |
|     10244 | RNY4   | False      | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/10244 | https://www.ncbi.nlm.nih.gov/pubmed/1698620, https://www.ncbi.nlm.nih.gov/pubmed/7520568 |
|     10248 | RNY5   | False      | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/10248 | https://www.ncbi.nlm.nih.gov/pubmed/6816230, https://www.ncbi.nlm.nih.gov/pubmed/8836182 |

**Comment by egchr** [comment]
I've added the new term 'Y_RNA_gene' (SO:0002359) as a child of ncRNA_gene. You should see the changes reflected online in the next 24 hours.
