### ISSUE TITLE
NTR: vault_RNA_gene

### ISSUE THREAD

**Issue by cthoyt** [The-Sequence-Ontology/SO-Ontologies#552]
**What is this request referring to?**

[SO:0000404 (vault_RNA)](https://www.ebi.ac.uk/ols/ontologies/so/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSO_0000404) falls under the following transcript hierarchy:

<img width="259" alt="Screen Shot 2021-09-17 at 00 14 23" src="https://user-images.githubusercontent.com/5069736/133692647-49f2fb2c-abc0-4793-8eee-7e8c79dd88ee.png">

The HGNC lists 4 genes as RNA, vault. However, HGNC refers to genes and not the transcripts they make. Therefore, it would be nice to mint a new term `vault_RNA_gene` the same way that other RNA transcripts have a similarly named _gene entry (e.g., SO:0000655 (ncRNA) has the corresponding gene SO:0001263 (ncRNA_gene))

**What is the name you would like SO to give the term?**

vault_RNA_gene

**What is the definition that you would like for this term?**

A gene that encodes a vault RNA.

**Synonyms**

N/A

**Parent Term**

Please put this under ncRNA-gene (SO:0001263)

**Relevant Publications**

Here are the four genes from HGNC that are annotated this way, and the publications each uses as references:

## RNA, vault (4)
|   hgnc_id | name     | obsolete   | link                                                               | provenance                                                                                                                                                                             |
|-----------|----------|------------|--------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|     12654 | VTRNA1-1 | False      | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/12654 | https://www.ncbi.nlm.nih.gov/pubmed/9535882, https://www.ncbi.nlm.nih.gov/pubmed/19298825, https://www.ncbi.nlm.nih.gov/pubmed/19491402, https://www.ncbi.nlm.nih.gov/pubmed/30773316  |
|     12655 | VTRNA1-2 | False      | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/12655 | https://www.ncbi.nlm.nih.gov/pubmed/9535882, https://www.ncbi.nlm.nih.gov/pubmed/19298825, https://www.ncbi.nlm.nih.gov/pubmed/19491402                                                |
|     12656 | VTRNA1-3 | False      | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/12656 | https://www.ncbi.nlm.nih.gov/pubmed/9535882, https://www.ncbi.nlm.nih.gov/pubmed/19298825, https://www.ncbi.nlm.nih.gov/pubmed/19491402                                                |
|     37054 | VTRNA2-1 | False      | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/37054 | https://www.ncbi.nlm.nih.gov/pubmed/19298825, https://www.ncbi.nlm.nih.gov/pubmed/19491402, https://www.ncbi.nlm.nih.gov/pubmed/22926522, https://www.ncbi.nlm.nih.gov/pubmed/22058117 |

**Comment by egchr** [comment]
This is done. I've created 'vault_RNA_gene' (SO:0002358) with definition "A gene that encodes a vault RNA". You should see the changes reflected online within the next 24 hours.

**Comment by cthoyt** [comment]
Thanks @egchr!

For future reference, this was addressed by adding this term to the `so-edit.obo` file and running some scripts to rebuild the rest of the resources in commit https://github.com/The-Sequence-Ontology/SO-Ontologies/commit/e4fc3ce4ca4ed94bad4b427e3d3e2c4d80a7c7ab.

**Comment by egchr** [comment]
Correct. At the moment we're editing 'so-edit.obo' using Protégé and updating the rest of the files using Oort, but once I can get the number of issue requests down a bit more we'll look at updating to ODK.
