### ISSUE TITLE
Improve def of scRNA_gene (SO:0001266)

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#553]
**What is the SO term name and accession?**
scRNA_gene (SO:0001266)

**Describe what you would like to change.**
Current def suggests this term is for the RNA product rather than the encoding gene: "A small noncoding RNA that is generally found only in the cytoplasm."  Suggest this is changed to "A gene encoding a small noncoding RNA that is generally found only in the cytoplasm".

**Comment by egchr** [comment]
This is done. The changes should be reflected online within the next 24 hours.
