### ISSUE TITLE
Improve SRP_RNA_gene (SO:0001269) definition

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#554]
**What is the SO term name and accession?**
SRP_RNA_gene (SO:0001269)

**Describe what you would like to change.**
Current def describes the RNA product, rather than the encoding gene: "A noncoding RNA that binds to the ribosome to halt protein synthesis when the signal peptide is present."
Suggest change to "A gene that encodes an RNA that binds to the ribosome to halt protein synthesis when the signal peptide is present." or more simply (following the pattern of other ncRNA_gene definitions): "A gene that encodes an signal recognition particle (SRP) RNA."

**Comment by egchr** [comment]
Changed definition from "A noncoding RNA that binds to the ribosome to halt protein synthesis when the signal peptide is present." to "A gene that encodes an signal recognition particle (SRP) RNA." following the pattern of other ncRNA_gene definitions. You should see the changes reflected online within the next 24 hours.

**Comment by sjm41** [comment]
Thanks Evan.  Can you change "...encodes an signal..." to "...encodes a signal..." (my mistake, sorry).

**Comment by egchr** [comment]
Sorry, I should have caught that. Thanks for mentioning it @sjm41. It should be fixed now.
