### ISSUE TITLE
Improve sncRNA_gene (SO:0002342) definition

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#555]
**What is the SO term name and accession?**
sncRNA_gene (SO:0002342)

**Describe what you would like to change.**
Current def "A ncRNA_gene (SO:0001263) that is less than 200 nucleotides in length." could be clarified to say "A ncRNA_gene (SO:0001263) that encodes an ncRNA less than 200 nucleotides in length."

(I'm not sure if other SO IDs should be quoted in definitions or not - most ncRNA_gene definitions do not, though a couple do.)

**Comment by egchr** [comment]
I changed the definition to "A ncRNA_gene that encodes an ncRNA less than 200 nucleotides in length." I'd like to figure out a way to automatically link to terms mentioned within a definition, but I need to get through the queue of issues first. You should see the changes reflected online within 24 hours.
