### ISSUE TITLE
scRNA (SO:0000013) parentage query

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#556]
**SO term name and accession**
scRNA (SO:0000013)

**Parent term name and accession**
ncRNA (SO:0000655)

**Suggested new parent term name and accession**
scRNA is defined as "A small non coding RNA sequence, present in the cytoplasm."  So, should/could this term be moved under:
sncRNA (SO:0002247) "A non-coding RNA less than 200 nucleotides in length."?

Looks like INSDC originally requested "scRNA", though their current definition is "any one of several small cytoplasmic RNA molecules present in the cytoplasm and (sometimes) nucleus of a eukaryote."

@murphyte - do you think INSDC usage fits of 'scRNA' fits the <200 nts criterion of 'sncRNA', or should 'scRNA' stay where it is?

If it is moved, then the same should happen with scRNA_gene (SO:0001266)

**Comment by murphyte** [comment]
Not all small cytoplasmic RNAs in INSDC are <200 nt, so I wouldn't move this term:
https://www.ncbi.nlm.nih.gov/nuccore/?term=ncrna_scrna%5Bfeature+key%5D+biomol_rna%5Bprop%5D+200%3A1000000%5Bslen%5D

**Comment by sjm41** [comment]
OK, thanks @murphyte !
