### ISSUE TITLE
Hierarchy on SO browser image doesn't always match ontology

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#560]
Eg1.
http://sequenceontology.org/browser/current_svn/term/SO:0002095
Parent of 'scaRNA' is 'snoRNA', but image shows it as 'ncRNA'.

Eg2.
http://sequenceontology.org/browser/current_svn/term/SO:0001001
Parent of 'cytosolic_23S_rRNA' is 'cytosolic_LSU_rRNA', but this isn't reflected in image.

May just be an issue for recently updated terms/relationships?

**Comment by egchr** [comment]
Working with @davidwsant to determine the cause.

**Comment by egchr** [comment]
@sjm41 We've put in a request for the cache to be cleared on the server hosting the sequence ontology browser (MISO). We'll let you know when that has happened so you can see if the issue remains on your end.

**Comment by egchristensen** [comment]
This issue seems to be resolved. Please let me know if you encounter this again in the future and we'll clear the cache again.
