### ISSUE TITLE
NTR: protocadherin_gene

### ISSUE THREAD

**Issue by cthoyt** [The-Sequence-Ontology/SO-Ontologies#562]
**What is this request referring to?**

HGNC marks some genes' locus types as "protocadherin". Their definition on https://www.genenames.org/help/symbol-report/ reads:

> gene segments that constitute the three clustered protocadherins (alpha, beta and gamma)

There are currently 39 genes:

<details>

|   HGNC Identifier | Symbol   | URL                                                                | Links                                                                                      |
|-------------------|----------|--------------------------------------------------------------------|--------------------------------------------------------------------------------------------|
|              8680 | PCDHB1   | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8680  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8687 | PCDHB2   | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8687  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8688 | PCDHB3   | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8688  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8689 | PCDHB4   | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8689  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8690 | PCDHB5   | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8690  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8691 | PCDHB6   | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8691  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8692 | PCDHB7   | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8692  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8693 | PCDHB8   | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8693  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8694 | PCDHB9   | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8694  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8681 | PCDHB10  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8681  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8682 | PCDHB11  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8682  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8683 | PCDHB12  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8683  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8684 | PCDHB13  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8684  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8685 | PCDHB14  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8685  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8686 | PCDHB15  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8686  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|             14546 | PCDHB16  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/14546 | https://www.ncbi.nlm.nih.gov/pubmed/11230163, https://www.ncbi.nlm.nih.gov/pubmed/11322959 |
|              8696 | PCDHGA1  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8696  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8700 | PCDHGA2  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8700  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8701 | PCDHGA3  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8701  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8702 | PCDHGA4  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8702  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8703 | PCDHGA5  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8703  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8704 | PCDHGA6  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8704  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8705 | PCDHGA7  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8705  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8706 | PCDHGA8  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8706  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8707 | PCDHGA9  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8707  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8697 | PCDHGA10 | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8697  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8698 | PCDHGA11 | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8698  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8699 | PCDHGA12 | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8699  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8708 | PCDHGB1  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8708  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8709 | PCDHGB2  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8709  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8710 | PCDHGB3  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8710  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8711 | PCDHGB4  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8711  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8712 | PCDHGB5  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8712  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8713 | PCDHGB6  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8713  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8714 | PCDHGB7  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8714  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8716 | PCDHGC3  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8716  | https://www.ncbi.nlm.nih.gov/pubmed/9360932, https://www.ncbi.nlm.nih.gov/pubmed/8508762   |
|              8717 | PCDHGC4  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8717  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8718 | PCDHGC5  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8718  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |
|              8719 | PCDHGCT  | https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8719  | https://www.ncbi.nlm.nih.gov/pubmed/10380929                                               |

</details>

A related term from the Protein Ontology is [protocadherin (PR:000044515)](http://purl.obolibrary.org/obo/PR_000044515). The relation [has gene product (RO:0002205)](http://purl.obolibrary.org/obo/RO_0002205) could be used to connect the protocadherin gene to this protein term.

More information on Wikipedia: https://en.wikipedia.org/wiki/Protocadherin.

**What is the name you would like SO to give the term?**

protocadherin_gene

**What is the definition that you would like for this term?**

A gene that encodes a protocadherin.

**Synonyms**

N/A

**Parent Term**

I think SO:0001217 (protein coding gene) is appropriate - there are protein crystal structures for the results. I'm not really sure why this gets its own category on HGNC, though.

**Relevant Publications**

I included relevant publications in the table above

**Comment by sartweedie** [comment]
HGNC have reclassified the gene with this locus type so no new term is required.
