### ISSUE TITLE
Add snoRNA_gene subtypes

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#565]
**What is this request referring to?**
Please add additional child terms to snoRNA_gene (SO:0001267) to match subtypes that already exist in other SO branches.

snoRNA_gene (SO:0001267) currently has only one child, scaRNA_gene. In contrast, snoRNA (SO:0000275) also has C_D_box_snoRNA (SO:0000593) and H_ACA_box_snoRNA (SO:0000594) as children, while snoRNA_encoding (SO:0000578) has H_ACA_box_snoRNA_encoding (SO:0000608) and C_D_box_snoRNA_encoding (SO:0000585) as children.

**What is the name you would like SO to give the term?**
C_D_box_snoRNA_gene
H_ACA_box_snoRNA_gene

**What is the definition that you would like for this term?**
A gene that encodes a C/D box snoRNA.
A gene that encodes a H/ACA box snoRNA.

**Parent Term**
 Please put these under snoRNA_gene (SO:0001267)

**Relevant Publications**
PMID: 12457565
PMID: 22065625

**Comment by egchr** [comment]
I went ahead and took care of this as part of Issue #519, but I did add the publications you just cited to C_D_box_snoRNA_gene and H_ACA_box_snoRNA_gene as part of this request.
