### ISSUE TITLE
Make 'rasiRNA' a child of 'piRNA'

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#573]
**SO term name and accession**
rasiRNA (SO:0000454)

**Parent term name and accession**
ncRNA (SO:0000655)

**Suggested new parent term name and accession**
piRNA (SO:0001035)

**Reason for the change**
Quoting from PMID: 18032451:
_Recent studies have revealed a new class of 24- to 30-nt RNAs that are generated by a Dicer-independent mechanism and that interact with a subset of Argonaute proteins related to Piwi (Aravin et al., 2006; Brennecke et al., 2007; Girard et al.,2006; Grivna et al.,2006a; Gunawardane et al.,2007; Houwing et al.,2007; Lau et al.,2006; Saito et al.,2006; Vagin et al.,2006; Watanabe et al.,2006), which is required for female and male fertility in Drosophila (Lin and Spradling,1997). I**n some systems, these Piwi-interacting RNAs (piRNAs) are primarily derived from transposons and other repeated sequence elements(Brennecke et al., 2007; Gunawardane et al., 2007; Saito et al., 2006), leading to their alternative designation as repeat-associated small interfering RNAs(rasiRNAs) (Aravin et al.,2003). It is now clear that piRNAs can be derived from either repeated or complex DNA sequence elements(Aravin et al., 2007; Brennecke et al., 2007; Houwing et al., 2007), and that rasiRNAs are a subset of piRNAs.**_

**Relevant Publications**
PMID: 18032451

**Comment by egchristensen** [comment]
This is done.
