### ISSUE TITLE
Improve definition of 'lncRNA'

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#575]
**What is the SO term name and accession?**
lncRNA (SO:0001877)

**Describe what you would like to change.**
Current definition is "A non-coding RNA over 200nucleotides in length."

Defining based solely on length means that 'lncRNA' effectively includes other well-defined ncRNAs >200nt (e.g. many rRNAs, RNase P, telomerase) that would not be generally called 'lncRNAs' . And the strict cut-off in length (though often quoted in the literature) is too restrictive.

Proposed new definition:
A non-coding RNA generally longer than 200 nucleotides that cannot be classified as any other ncRNA subtype. Similar to mRNAs, lncRNAs are mainly transcribed by RNA polymerase II, are often capped by 7-methyl guanosine at their 5' ends, polyadenylated at their 3' ends and may be spliced. (PMID: 33353982)

**Relevant Publications**
PMID: 33353982

Tagging @murphyte

**Comment by egchristensen** [comment]
This is done.
