### ISSUE TITLE
Synonyms for C_D_box_snoRNA & H_ACA_box_snoRNA.

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#577]
C_D_box_snoRNA (SO:0000593)
- Add "SNORD" as a synonym (PMID: 31828325)

H_ACA_box_snoRNA (SO:0000594)
- Add "SNORA" as a synonym (PMID: 31828325)

**Comment by egchristensen** [comment]
This is done.
