### ISSUE TITLE
Improve snoRNA (SO:0000275) definition.

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#578]
**What is the SO term name and accession?**
snoRNA (SO:0000275)

**Describe what you would like to change.**
Current def: "A snoRNA (small nucleolar RNA) is any one of a class of small RNAs that are associated with the eukaryotic nucleus as components of small nucleolar ribonucleoproteins. They participate in the processing or modifications of many RNAs, mostly ribosomal RNAs (rRNAs) though snoRNAs are also known to target other classes of RNA, including spliceosomal RNAs, tRNAs, and mRNAs via a stretch of sequence that is complementary to a sequence in the targeted RNA."

Some snoRNAs functionally localise to other compartments (cytoplasm or even secreted), so this needs to be acknowledged in the definition.  The current def also lacks an attribution, and is rather wordy.

Suggest we change the definition to the following based on a very recent (2020) review:
Small nucleolar RNAs (snoRNAs) are short non-coding RNAs enriched in the nucleolus as components of small nucleolar ribonucleoproteins. They guide ribose methylation and pseudouridylation of rRNAs and snRNAs, and a subgroup regulate excision of rRNAs from rRNA precursor transcripts. snoRNAs may also guide rRNA acetylation and tRNA methylation, and regulate mRNA abundance and alternative splicing. [PMID: 31828325]

**Relevant Publications**
[PMID: 31828325]

**Comment by egchristensen** [comment]
This is done.
