### ISSUE TITLE
Change 'ncRNA' to 'lncRNA' in sense_intronic_ncRNA & sense_overlap_ncRNA terms.

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#579]
**What is the SO term name and accession?**
sense_intronic_ncRNA (SO:0002131)
sense_overlap_ncRNA (SO:0002132)
sense_overlap_ncRNA_gene (SO:0002183)
sense_intronic_ncRNA_gene (SO:0002184)

**Describe what you would like to change.**
These 4 terms are children of either lncRNA or lncRNA_gene and are defined as subtypes of lncRNA/lncRNA_gene.  So please swap 'ncRNA' for 'lncRNA' in their names.

These changes were previously requested in #408, where the reply was "we can't edit sense_intronic_ncRNA and sense_overlap_ncRNA since these terms have already been mapped to Gencode terms."
But the current GENCODE site (https://www.gencodegenes.org/pages/biotypes.html) uses just 'sense_intronic' and 'sense_overlap' as the term names, and besides that page also states that the generic 'lncRNA' is now used in place of those two terms.

**Comment by sjm41** [comment]
I was just chatting with Jonathan Mudge, Project Leader at GENCODE.
He confirmed that GENCODE are no longer using these terms as biotypes in their database, and he has no issue with SO changing the the 'ncRNA' in these term names to 'lncRNA'.
So can you go ahead and make those changes please?

**Comment by egchristensen** [comment]
This is done.
