### ISSUE TITLE
NTR: bidirectional_promoter_lncRNA

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#582]
**What is this request referring to?**
bidirectional promoter long non-coding RNA

**What is the name you would like SO to give the term?**
bidirectional_promoter_lncRNA

**What is the definition that you would like for this term?**
A long non-coding RNA which is produced using the promoter of a protein-coding gene but with transcription occurring in the opposite direction [PMID: 30175284, PMID: 34956340]

**Synonyms**
bidirectional lncRNA

**Parent Term**
lncRNA (SO:0001877)

**Relevant Publications**
PMID: 30175284
PMID: 26578749 
PMID: 34956340

**Notes**
This request follows on from discussion in #506, and that ticket needs to be addressed first.

**Comment by egchristensen** [comment]
This is done. Created new term "bidirectional_promoter_lncRNA" (SO:0002381).
