### ISSUE TITLE
Typo in PMID xref for U4atac_snRNA

### ISSUE THREAD

**Issue by cmungall** [The-Sequence-Ontology/SO-Ontologies#588]
The def xref in this definition should be changed from `PMID:=12409455` to `PMID:12409455`
https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/868027bfe14758dae78fc3e38f8f5fc8b8427dcc/Ontology_Files/subsets/SOFA.obo#L1242

**Comment by egchr** [comment]
This is done. [Commit 5a1726141c9cad53fe6bb8b038c2dcd7e2e15ca8.](https://github.com/The-Sequence-Ontology/SO-Ontologies/commit/5a1726141c9cad53fe6bb8b038c2dcd7e2e15ca8)
