### ISSUE TITLE
Historical versions of SO

### ISSUE THREAD

**Issue by deepakunni3** [The-Sequence-Ontology/SO-Ontologies#607]
Hi all! I wanted to inquire to see if there is a place one can access historical versions of SO.

I see a release for 2018 in Releases tab (https://github.com/The-Sequence-Ontology/SO-Ontologies/releases/tag/v3.1).

And I see that there is a download link for `so.owl` at https://obofoundry.org/ontology/so.html. But this is the `2021-11-22` version of the SO and it looks like the SO PURL (http://purl.obolibrary.org/obo/so.owl) always points to the latest.

Is there a place one can look at all previous releases of SO?

Many thanks! :)

**Comment by egchristensen** [comment]
We used [SourceForge](https://sourceforge.net/projects/song/) before we started using GitHub. Does that link get you to what you're looking for @deepakunni3?

**Comment by deepakunni3** [comment]
Great! Thank you for the SourceForge link! 👍 

Yes, I think this definitely helps in looking back to older versions of SO.
