### ISSUE TITLE
SO home page appears to be down

### ISSUE THREAD

**Issue by tommystanton** [The-Sequence-Ontology/SO-Ontologies#620]
Thank you for SO! I only recently discovered this resource (via a link in [FHIR's documentation](https://hl7.org/fhir/)) and in the couple of days that I have consulted it, it has been immensely helpful and insightful.

---

I last used the SO home page on Thurs 8/3/2023, at [sequenceontology.org](http://www.sequenceontology.org/).

As of Mon 8/7/2023, the home page returns a generic domain splash page.

**Comment by tommystanton** [comment]
The SO home page appears to be back up! Closing.

**Comment by egchristensen** [comment]
Thanks for messaging us! Our domain expired for a brief moment, but we've renewed it so we should be good to go. If you'd like a quicker way to browse the ontology, you can view the ontology files on your local machine using Protégé (https://protege.stanford.edu/). Once you have Protégé installed, select "file" > "open from URL", enter this URL: https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/Ontology_Files/so.obo, then click "ok".
