### ISSUE TITLE
uORF -  frameshift variant

### ISSUE THREAD

**Issue by sarahhunt** [The-Sequence-Ontology/SO-Ontologies#621]
**What is this request referring to?**
A variant in a ORF in a 5' UTR which causes a frame shift

**What is the name you would like SO to give the term?**
5_prime_UTR_uORF_frameshift_variant

**What is the definition that you would like for this term?**
A 5'UTR variant which disrupts the translation of an upstream open reading frame because the number of nucleotides inserted or deleted is not a multiple of three

**Synonyms**
uFrameshift(UTRannotator)

**Parent Term**
5_prime_UTR_uORF_variant ( #647 )

**Relevant Publications**

PMID: 32461616, Whiffin et al 2020
Characterising the loss-of-function impact of 5' untranslated region variants in 15,708 individuals. (Nature Communications) 

PMID: 32926138, Zhang et al 2021
Annotating high-impact 5'untranslated region variants with the UTRannotator (Bioinformatics)

**Comment by egchristensen** [comment]
This is done. Changes should be reflected on sequenceontology.org in the next 24 hours. If you'd like to inspect the changes right away I'd recommend downloading [Protégé](https://protege.stanford.edu/) and opening the ontology files with "File" > "Open from URL..." > and then entering this URL: https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/Ontology_Files/so.obo
