### ISSUE TITLE
uORF -  stop loss variant

### ISSUE THREAD

**Issue by sarahhunt** [The-Sequence-Ontology/SO-Ontologies#623]
**What is this request referring to?**
A variant which results in the loss of the stop codon of an ORF in a 5'UTR. 

**What is the name you would like SO to give the term?**
5_prime_UTR_uORF_stop_codon_loss_variant 

**What is the definition that you would like for this term?**
A 5'UTR variant where the stop codon of an upstream open reading frame is lost.

**Synonyms**
uSTOP_lost( UTRannotator)

**Parent Term**
5_prime_UTR_uORF_stop_codon_variant
See https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/622

**Relevant Publications**
PMID: 32461616, Whiffin et al 2020
Characterising the loss-of-function impact of 5' untranslated region variants in 15,708 individuals. (Nature Communications) 

PMID: 32926138, Zhang et al 2021
Annotating high-impact 5'untranslated region variants with the UTRannotator (Bioinformatics)

**Comment by CristianRiccio** [comment]
Hello Sarah Hunt,
I support your request. I am working with UTRannotator and it would be useful to have this term relating to 5 prime UTR uORFs.
I hope the term gets accepted.
Thanks.
