### ISSUE TITLE
NTR: oncogenic_variant

### ISSUE THREAD

**Issue by refu6enik** [The-Sequence-Ontology/SO-Ontologies#643]
**What is this request referring to?**
Oncogenic Variant

**What is the name you would like SO to give the term?**
oncogenic_variant

**What is the definition that you would like for this term?**
A variant that has been found to be pathogenic in the context of a neoplastic disease.

**Synonyms**
NA

**Parent Term**
It could go under disease_associated_variant (SO:0001771)?

**Relevant Publications**
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9081216/
https://faq.oncokb.org/data-curation#some-genes-have-an-alteration-called-oncogenic-mutations.-what-does-this-mean

**Comment by egchristensen** [comment]
Created a new term oncogenic_variant (SO:0002383). Changes should be reflected on sequenceontology.org within 24 hours.

**Comment by refu6enik** [comment]
Thanks for your help, Evan.
