### ISSUE TITLE
Fix definition of miRNA (SO:0000276)

### ISSUE THREAD

**Issue by dbolser** [The-Sequence-Ontology/SO-Ontologies#648]
**What is the SO term name and accession?**
Please specify the SO term name and accession. Example: miRNA (SO:0000276)

**Describe what you would like to change.**
There is a ) missing in the definition.

CURRENTLY:
    Small, ~22-nt, RNA molecule that is the endogenous transcript of a miRNA gene (or the product of other non coding RNA genes. Micro RNAs are produced from precursor molecules (SO:0001244) that can form local hairpin structures, which ordinarily are processed (usually via the Dicer pathway) such that a single miRNA molecule accumulates from one arm of a hairpin precursor molecule. Micro RNAs may trigger the cleavage of their target molecules or act as translational repressors.

SHOULD BE:
    Small, ~22-nt, RNA molecule that is the endogenous transcript of a miRNA gene (or the product of other non coding RNA genes). Micro RNAs are produced from precursor molecules (SO:0001244) that can form local hairpin structures, which ordinarily are processed (usually via the Dicer pathway) such that a single miRNA molecule accumulates from one arm of a hairpin precursor molecule. Micro RNAs may trigger the cleavage of their target molecules or act as translational repressors.

**Relevant Publications**
NA

**Comment by egchristensen** [comment]
This is done. You should see the changes reflected on [the SO website](http://www.sequenceontology.org/browser/current_release/term/SO:0000276) within the next 24 hours.
